export const CATEGORIES = [
  { id: 'series',      name: 'Series y TV',    icon: '📺', desc: 'Friends, Breaking Bad, Stranger Things y más' },
  { id: 'fantasia',    name: 'Fantasía y Lore', icon: '🧙', desc: 'GOT, LOTR, Hobbit, The Witcher' },
  { id: 'videojuegos', name: 'Videojuegos',     icon: '🎮', desc: 'Nintendo, Blizzard, Zelda, Pokémon y más' },
  { id: 'scifi',       name: 'Sci-Fi',          icon: '🚀', desc: 'Star Wars, Star Trek, Back to the Future' },
  { id: 'animados',    name: 'Animados',        icon: '🎨', desc: 'Disney, Simpsons, Rick and Morty' },
  { id: 'superheroes', name: 'Superhéroes',     icon: '🦸', desc: 'Marvel, DC, X-Men, Invincible' },
  { id: 'anime',       name: 'Anime',           icon: '🍜', desc: 'Dragon Ball, Naruto, One Piece, Avatar' },
  { id: 'deportes',    name: 'Deportes',        icon: '⚽', desc: 'Fútbol Mundial y más deportes' },
]

export const UNIVERSES = [
  // ── SERIES Y TV ──────────────────────────────────────────────
  {
    id: 'friends', categoryId: 'series', name: 'Friends', icon: '☕',
    color: '#e86030', colorSoft: 'rgba(232,96,48,0.12)', colorBorder: 'rgba(232,96,48,0.3)',
    sub: 'Central Perk, Nueva York', available: true,
    tiers: [
      { min: 0,   label: 'Recién llegado a NY' },
      { min: 25,  label: 'Vecino del pasillo' },
      { min: 50,  label: 'Amigo del grupo' },
      { min: 100, label: 'Roommate de Monica' },
      { min: 200, label: 'Miembro honorario' },
    ],
    achievements: {
      speed1: { name: 'Reacción de Phoebe',      desc: 'Responder en <5s' },
      speed2: { name: 'Joey sabe actuar rápido', desc: '3 rápidas seguidas (<5s)' },
      speed3: { name: 'How you doin?',            desc: '5 consecutivas en <3s' },
      acc1:   { name: 'Sofá naranja',             desc: 'Primera correcta en Friends' },
      acc2:   { name: 'Habitué del Central Perk', desc: '7/10 en una ronda' },
      acc3:   { name: 'Amigo del año',            desc: 'Ronda perfecta 10/10' },
      acc4:   { name: 'Los 6 amigos perfectos',   desc: '3 rondas perfectas' },
      duel1:  { name: 'Primer duelo',             desc: 'Ganar 1 duelo en Friends' },
      duel2:  { name: 'Campeón del foosball',     desc: 'Ganar 5 duelos' },
      duel3:  { name: 'Ross vs Rachel',           desc: 'Ganar 10 duelos' },
      duel4:  { name: 'La boda interrumpida',     desc: 'Ganar 20 duelos' },
    }
  },
  {
    id: 'strangerthings', categoryId: 'series', name: 'Stranger Things', icon: '🔦',
    color: '#e06c6c', colorSoft: 'rgba(224,108,108,0.12)', colorBorder: 'rgba(224,108,108,0.3)',
    sub: 'Hawkins, Indiana — Mundo del Revés', available: true,
    tiers: [
      { min: 0,   label: 'Bienvenido a Hawkins' },
      { min: 25,  label: 'Investigador aficionado' },
      { min: 50,  label: 'Cazador de Demogorgons' },
      { min: 100, label: 'Agente del Laboratorio' },
      { min: 200, label: 'Eleven del saber' },
    ],
    achievements: {
      speed1: { name: 'Reflejos del Upside Down', desc: 'Responder en <5s' },
      speed2: { name: 'Velocidad de Eleven',      desc: '3 rápidas seguidas (<5s)' },
      speed3: { name: 'Escape del laboratorio',   desc: '5 consecutivas en <3s' },
      acc1:   { name: 'Luces navideñas',          desc: 'Primera correcta en ST' },
      acc2:   { name: 'Miembro del grupo',        desc: '7/10 en una ronda' },
      acc3:   { name: 'Hopper lo aprueba',        desc: 'Ronda perfecta 10/10' },
      acc4:   { name: 'Mente Colmena derrotada',  desc: '3 rondas perfectas' },
      duel1:  { name: 'Primer duelo',             desc: 'Ganar 1 duelo en ST' },
      duel2:  { name: 'Bichos del Upside Down',   desc: 'Ganar 5 duelos' },
      duel3:  { name: 'Guardia de Hawkins',       desc: 'Ganar 10 duelos' },
      duel4:  { name: 'Cerraste el portal',       desc: 'Ganar 20 duelos' },
    }
  },
  {
    id: 'breakingbad', categoryId: 'series', name: 'Breaking Bad', icon: '🧪',
    color: '#4ec994', colorSoft: 'rgba(78,201,148,0.12)', colorBorder: 'rgba(78,201,148,0.3)',
    sub: 'Albuquerque, New Mexico', available: true,
    tiers: [
      { min: 0,   label: 'Soy el peligro' },
      { min: 25,  label: 'Estudiante de química' },
      { min: 50,  label: 'Socio de Saul' },
      { min: 100, label: 'El que llama a la puerta' },
      { min: 200, label: 'Yo soy el que cocina' },
    ],
    achievements: {
      speed1: { name: 'Síntesis rápida',          desc: 'Responder en <5s' },
      speed2: { name: 'Velocidad del lab',         desc: '3 rápidas seguidas (<5s)' },
      speed3: { name: 'Heisenberg',               desc: '5 consecutivas en <3s' },
      acc1:   { name: 'Primer cocinado',           desc: 'Primera correcta en BB' },
      acc2:   { name: 'Asistente de Walter',       desc: '7/10 en una ronda' },
      acc3:   { name: 'Azul 99.1%',               desc: 'Ronda perfecta 10/10' },
      acc4:   { name: 'El mejor que jamás existió',desc: '3 rondas perfectas' },
      duel1:  { name: 'Primer duelo',              desc: 'Ganar 1 duelo en BB' },
      duel2:  { name: 'Distribuidor local',        desc: 'Ganar 5 duelos' },
      duel3:  { name: 'Jefe del territorio',       desc: 'Ganar 10 duelos' },
      duel4:  { name: 'Cartel de Albuquerque',     desc: 'Ganar 20 duelos' },
    }
  },
  {
    id: 'bigbangtheory', categoryId: 'series', name: 'Big Bang Theory', icon: '🔬',
    color: '#7b8ec4', colorSoft: 'rgba(123,142,196,0.12)', colorBorder: 'rgba(123,142,196,0.3)',
    sub: 'Pasadena, California', available: true,
    tiers: [
      { min: 0,   label: 'Estudiante de física' },
      { min: 25,  label: 'Compañero de piso' },
      { min: 50,  label: 'Investigador del Caltech' },
      { min: 100, label: 'Colaborador de la NASA' },
      { min: 200, label: 'Bazzinga definitivo' },
    ],
    achievements: {
      speed1: { name: 'Rapidez cuántica',          desc: 'Responder en <5s' },
      speed2: { name: 'Velocidad de Sheldon',       desc: '3 rápidas seguidas (<5s)' },
      speed3: { name: 'Cálculo instantáneo',        desc: '5 consecutivas en <3s' },
      acc1:   { name: 'Primer Bazinga',             desc: 'Primera correcta en BBT' },
      acc2:   { name: 'Pensamiento de Howard',      desc: '7/10 en una ronda' },
      acc3:   { name: 'Genio del Caltech',          desc: 'Ronda perfecta 10/10' },
      acc4:   { name: 'Sheldon Cooper level',       desc: '3 rondas perfectas' },
      duel1:  { name: 'Primer duelo',               desc: 'Ganar 1 duelo en BBT' },
      duel2:  { name: 'Disputa de notas adhesivas', desc: 'Ganar 5 duelos' },
      duel3:  { name: 'Campeón del sótano',         desc: 'Ganar 10 duelos' },
      duel4:  { name: 'El experimento ganador',     desc: 'Ganar 20 duelos' },
    }
  },
  { id: 'theoffice', categoryId: 'series', name: 'The Office', icon: '📋', color: '#8e9fb5', colorSoft: 'rgba(142,159,181,0.12)', colorBorder: 'rgba(142,159,181,0.3)', sub: 'Dunder Mifflin, Scranton PA', available: true,
    tiers: [
      { min: 0,  label: 'Empleado de Dunder Mifflin' },
      { min: 25,  label: 'Vendedor del mes' },
      { min: 50,  label: 'Gerente interino' },
      { min: 100,  label: 'Asistente del gerente regional' },
      { min: 200,  label: 'Michael Scott aprueba' }
    ],
    achievements: {
      speed1: { name: 'Respuesta de Kevin', desc: 'Responder en <5s' },
      speed2: { name: 'Rapidez de Dwight', desc: '3 rápidas seguidas (<5s)' },
      speed3: { name: 'Ingenio de Jim', desc: '5 consecutivas en <3s' },
      acc1: { name: 'Primera venta cerrada', desc: 'Primera correcta en The Office' },
      acc2: { name: 'Reunión de equipo superada', desc: '7/10 en una ronda' },
      acc3: { name: 'Evaluación perfecta', desc: 'Ronda perfecta 10/10' },
      acc4: { name: 'Gerente del año', desc: '3 rondas perfectas' },
      duel1: { name: 'Primer duelo', desc: 'Ganar 1 duelo en The Office' },
      duel2: { name: 'Guerra de bromas con Jim', desc: 'Ganar 5 duelos' },
      duel3: { name: 'Campeón del parking', desc: 'Ganar 10 duelos' },
      duel4: { name: 'Michael vs Toby', desc: 'Ganar 20 duelos' }
    }
  },

  // ── FANTASÍA Y LORE ──────────────────────────────────────────
  {
    id: 'got', categoryId: 'fantasia', name: 'Game of Thrones', icon: '⚔️',
    color: '#cc3030', colorSoft: 'rgba(204,48,48,0.12)', colorBorder: 'rgba(204,48,48,0.3)',
    sub: 'Westeros y más allá', available: true,
    tiers: [
      { min: 0,   label: 'Recién llegado a Desembarco' },
      { min: 25,  label: 'Caminante Blanco' },
      { min: 50,  label: 'Guardián del Muro' },
      { min: 100, label: 'Lord de los Siete Reinos' },
      { min: 200, label: 'El Rey en el Norte' },
    ],
    achievements: {
      speed1: { name: 'Cuervo veloz',           desc: 'Responder en <5s' },
      speed2: { name: 'Tormenta de espadas',    desc: '3 rápidas seguidas (<5s)' },
      speed3: { name: 'Velocidad valyria',       desc: '5 consecutivas en <3s' },
      acc1:   { name: 'Primera sangre',          desc: 'Primera correcta en GOT' },
      acc2:   { name: 'Escudero de la Guardia',  desc: '7/10 en una ronda' },
      acc3:   { name: 'Guardia Real',            desc: 'Ronda perfecta 10/10' },
      acc4:   { name: 'Estratega como Tywin',    desc: '3 rondas perfectas' },
      duel1:  { name: 'Primer duelo',            desc: 'Ganar 1 duelo en GOT' },
      duel2:  { name: 'Bravo de Braavos',        desc: 'Ganar 5 duelos' },
      duel3:  { name: 'Campeón del Torneo',      desc: 'Ganar 10 duelos' },
      duel4:  { name: 'La Montaña vs La Víbora', desc: 'Ganar 20 duelos' },
    }
  },
  {
    id: 'lotr', categoryId: 'fantasia', name: 'Lord of the Rings — Películas', icon: '💍',
    color: '#c9a84c', colorSoft: 'rgba(201,168,76,0.12)', colorBorder: 'rgba(201,168,76,0.3)',
    sub: 'La Comunidad, Las Dos Torres, El Rey', available: true,
    tiers: [
      { min: 0,   label: 'Salida del Shire' },
      { min: 25,  label: 'Portador del Anillo' },
      { min: 50,  label: 'Guardián de Rohan' },
      { min: 100, label: 'Señor de Rivendell' },
      { min: 200, label: 'Rey de Gondor' },
    ],
    achievements: {
      speed1: { name: 'Hobbit ágil',               desc: 'Responder en <5s' },
      speed2: { name: 'Velocidad élfica',           desc: '3 rápidas seguidas (<5s)' },
      speed3: { name: 'Correr como Legolas',        desc: '5 consecutivas en <3s' },
      acc1:   { name: 'Primera flecha',             desc: 'Primera correcta en LOTR' },
      acc2:   { name: 'Ocho Compañeros',            desc: '8/10 en una ronda' },
      acc3:   { name: 'La Comunidad perfecta',      desc: 'Ronda perfecta 10/10' },
      acc4:   { name: 'Portador del Saber',         desc: '3 rondas perfectas' },
      duel1:  { name: 'Primer duelo',               desc: 'Ganar 1 duelo en LOTR' },
      duel2:  { name: 'Guerrero de Rohan',          desc: 'Ganar 5 duelos' },
      duel3:  { name: 'Defensor del Abismo de Helm',desc: 'Ganar 10 duelos' },
      duel4:  { name: 'Gandalf el Blanco',          desc: 'Ganar 20 duelos' },
    }
  },
  {
    id: 'lotrages', categoryId: 'fantasia', name: 'LOTR — 1ª y 2ª Edad', icon: '🌋',
    color: '#a07840', colorSoft: 'rgba(160,120,64,0.12)', colorBorder: 'rgba(160,120,64,0.3)',
    sub: 'Númenor, Morgoth, los Anillos de Poder', available: true,
    tiers: [
      { min: 0,   label: 'Habitante de Arda' },
      { min: 25,  label: 'Superviviente de Beleriand' },
      { min: 50,  label: 'Guerrero de Númenor' },
      { min: 100, label: 'Lore Master de las Edades' },
      { min: 200, label: 'Conocedor del Silmarillion' },
    ],
    achievements: {
      speed1: { name: 'Flechas de Fingolfin',    desc: 'Responder en <5s' },
      speed2: { name: 'Velocidad de Glorfindel', desc: '3 rápidas seguidas (<5s)' },
      speed3: { name: 'Pensamiento de Finrod',   desc: '5 consecutivas en <3s' },
      acc1:   { name: 'Primer silmaril',         desc: 'Primera correcta' },
      acc2:   { name: 'Compañero de Beren',      desc: '8/10 en una ronda' },
      acc3:   { name: 'Cronista de Arda',        desc: 'Ronda perfecta 10/10' },
      acc4:   { name: 'Silmarillion viviente',   desc: '3 rondas perfectas' },
      duel1:  { name: 'Primer duelo',            desc: 'Ganar 1 duelo' },
      duel2:  { name: 'Campeón de Gondolin',     desc: 'Ganar 5 duelos' },
      duel3:  { name: 'Rival de Sauron',         desc: 'Ganar 10 duelos' },
      duel4:  { name: 'Desafiante de Morgoth',   desc: 'Ganar 20 duelos' },
    }
  },
  {
    id: 'hobbit', categoryId: 'fantasia', name: 'The Hobbit', icon: '🐉',
    color: '#5a9e6f', colorSoft: 'rgba(90,158,111,0.12)', colorBorder: 'rgba(90,158,111,0.3)',
    sub: 'Bilbo, Thorin y la Montaña Solitaria', available: true,
    tiers: [
      { min: 0,   label: 'Hobbit de la Comarca' },
      { min: 25,  label: 'Compañero de Bilbo' },
      { min: 50,  label: 'Explorador de Erebor' },
      { min: 100, label: 'Burglar de Thorin' },
      { min: 200, label: 'Portador del Arkenstone' },
    ],
    achievements: {
      speed1: { name: 'Pie rápido de hobbit',     desc: 'Responder en <5s' },
      speed2: { name: 'Velocidad de Gandalf',     desc: '3 rápidas seguidas (<5s)' },
      speed3: { name: 'Acertijo en la oscuridad', desc: '5 consecutivas en <3s' },
      acc1:   { name: 'Primera aventura',         desc: 'Primera correcta en Hobbit' },
      acc2:   { name: 'Compañía de los 13',       desc: '8/10 en una ronda' },
      acc3:   { name: 'Tesoro de Smaug',          desc: 'Ronda perfecta 10/10' },
      acc4:   { name: 'Maestro del monte',        desc: '3 rondas perfectas' },
      duel1:  { name: 'Primer duelo',             desc: 'Ganar 1 duelo en Hobbit' },
      duel2:  { name: 'Cazador de Trolls',        desc: 'Ganar 5 duelos' },
      duel3:  { name: 'Duelo ante Smaug',         desc: 'Ganar 10 duelos' },
      duel4:  { name: 'Señor de Erebor',          desc: 'Ganar 20 duelos' },
    }
  },
  { id: 'harrypotter', categoryId: 'fantasia', name: 'Harry Potter', icon: '⚡', color: '#9b8ec4', colorSoft: 'rgba(155,142,196,0.12)', colorBorder: 'rgba(155,142,196,0.3)', sub: 'El mundo mágico de Hogwarts', available: true,
    tiers: [
      { min: 0,   label: 'Carta de Hogwarts' },
      { min: 25,  label: 'Alumno de 1er año' },
      { min: 50,  label: 'Miembro de la OFA' },
      { min: 100, label: 'Auror del Ministerio' },
      { min: 200, label: 'El Elegido' },
    ],
    achievements: {
      speed1: { name: 'Encantamiento veloz',        desc: 'Responder en <5s' },
      speed2: { name: 'Wingardium rápiosa',          desc: '3 rápidas seguidas (<5s)' },
      speed3: { name: 'Expelliarmus instantáneo',    desc: '5 consecutivas en <3s' },
      acc1:   { name: 'Primera poción',              desc: 'Primera correcta en HP' },
      acc2:   { name: 'Estudiante de Hogwarts',      desc: '7/10 en una ronda' },
      acc3:   { name: 'Prefecto',                    desc: 'Ronda perfecta 10/10' },
      acc4:   { name: 'Sabio como Dumbledore',       desc: '3 rondas perfectas' },
      duel1:  { name: 'Primer duelo',                desc: 'Ganar 1 duelo en HP' },
      duel2:  { name: 'Duelo del Club',              desc: 'Ganar 5 duelos' },
      duel3:  { name: 'Ejército de Dumbledore',      desc: 'Ganar 10 duelos' },
      duel4:  { name: 'Harry vs Voldemort',          desc: 'Ganar 20 duelos' },
    }
  },
  { id: 'witcher', categoryId: 'fantasia', name: 'The Witcher', icon: '🐺',
    color: '#a0a060', colorSoft: 'rgba(160,160,96,0.12)', colorBorder: 'rgba(160,160,96,0.3)',
    sub: 'El Continente', available: true,
    tiers: [
      { min: 0,   label: 'Aprendiz de Kaer Morhen' },
      { min: 25,  label: 'Cazador de monstruos novato' },
      { min: 50,  label: 'Brujo del Continente' },
      { min: 100, label: 'Lobo Blanco de Rivia' },
      { min: 200, label: 'Leyenda del Continente' },
    ],
    achievements: {
      speed1: { name: 'Reflejos de Signo Quen',         desc: 'Responder en <5s' },
      speed2: { name: 'Velocidad de espada de plata',   desc: '3 rápidas seguidas (<5s)' },
      speed3: { name: 'Instinto de mutágeno',           desc: '5 consecutivas en <3s' },
      acc1:   { name: 'Primer contrato de brujo',       desc: 'Primera correcta en Witcher' },
      acc2:   { name: 'Cazador confiable',              desc: '7/10 en una ronda' },
      acc3:   { name: 'Contrato perfecto',              desc: 'Ronda perfecta 10/10' },
      acc4:   { name: 'Leyenda del Continente',         desc: '3 rondas perfectas' },
      duel1:  { name: 'Primer duelo',                   desc: 'Ganar 1 duelo en Witcher' },
      duel2:  { name: 'Guardián de Kaer Morhen',        desc: 'Ganar 5 duelos' },
      duel3:  { name: 'Campeón de Novigrado',           desc: 'Ganar 10 duelos' },
      duel4:  { name: 'Geralt vs la Cacería Salvaje',   desc: 'Ganar 20 duelos' },
    }
  },

  { id: 'motu', categoryId: 'fantasia', name: 'Masters of the Universe', icon: '💪',
    color: '#c87830', colorSoft: 'rgba(200,120,48,0.12)', colorBorder: 'rgba(200,120,48,0.3)',
    sub: 'Eternia y el Castillo de Grayskull', available: true,
    tiers: [
      { min: 0,   label: 'Habitante de Eternia' },
      { min: 25,  label: 'Guerrero en entrenamiento' },
      { min: 50,  label: 'Defensor del Castillo de Grayskull' },
      { min: 100, label: 'Amo del Universo' },
      { min: 200, label: 'Poseedor del Poder de Grayskull' },
    ],
    achievements: {
      speed1: { name: 'Reflejos de Battle Cat',         desc: 'Responder en <5s' },
      speed2: { name: 'Velocidad de la Espada del Poder', desc: '3 rápidas seguidas (<5s)' },
      speed3: { name: 'Instinto de Eternia',            desc: '5 consecutivas en <3s' },
      acc1:   { name: 'Primer secreto de Grayskull',    desc: 'Primera correcta en MOTU' },
      acc2:   { name: 'Aliado de los Masters',          desc: '7/10 en una ronda' },
      acc3:   { name: 'Batalla perfecta',               desc: 'Ronda perfecta 10/10' },
      acc4:   { name: 'Leyenda de Eternia',              desc: '3 rondas perfectas' },
      duel1:  { name: 'Primer duelo',                   desc: 'Ganar 1 duelo en MOTU' },
      duel2:  { name: 'Guardián del castillo',          desc: 'Ganar 5 duelos' },
      duel3:  { name: 'Campeón de Eternia',             desc: 'Ganar 10 duelos' },
      duel4:  { name: 'He-Man vs Skeletor',             desc: 'Ganar 20 duelos' },
    }
  },

  // ── VIDEOJUEGOS ──────────────────────────────────────────────
  {
    id: 'mario', categoryId: 'videojuegos', name: 'Mario & Nintendo', icon: '🍄',
    color: '#e05050', colorSoft: 'rgba(224,80,80,0.12)', colorBorder: 'rgba(224,80,80,0.3)',
    sub: 'Reino Champiñón y más allá', available: true,
    tiers: [
      { min: 0,   label: 'Toad del Reino Champiñón' },
      { min: 25,  label: 'Fontanero en aprendizaje' },
      { min: 50,  label: 'Caballero de la princesa' },
      { min: 100, label: 'Maestro del Kart' },
      { min: 200, label: 'Héroe del Reino Champiñón' },
    ],
    achievements: {
      speed1: { name: 'Salto rápido',              desc: 'Responder en <5s' },
      speed2: { name: 'Super velocidad',            desc: '3 rápidas seguidas (<5s)' },
      speed3: { name: 'Estrella de invencibilidad', desc: '5 consecutivas en <3s' },
      acc1:   { name: 'Primera moneda',             desc: 'Primera correcta en Mario' },
      acc2:   { name: 'Super Champiñón',            desc: '7/10 en una ronda' },
      acc3:   { name: 'Ronda perfecta de Luigi',    desc: 'Ronda perfecta 10/10' },
      acc4:   { name: 'Maestro de los mundos',      desc: '3 rondas perfectas' },
      duel1:  { name: 'Primer duelo',               desc: 'Ganar 1 duelo en Mario' },
      duel2:  { name: 'Corredor del Mario Kart',    desc: 'Ganar 5 duelos' },
      duel3:  { name: 'Campeón de Smash Bros',      desc: 'Ganar 10 duelos' },
      duel4:  { name: 'Bowser derrotado',           desc: 'Ganar 20 duelos' },
    }
  },
  { id: 'blizzard', categoryId: 'videojuegos', name: 'Blizzard', icon: '🔵', color: '#1c5dc8', colorSoft: 'rgba(28,93,200,0.12)', colorBorder: 'rgba(28,93,200,0.3)', sub: 'WoW, Starcraft, Diablo y más', available: true,
    tiers: [
      { min: 0,   label: 'Goblin de taberna' },
      { min: 25,  label: 'Aventurero de Azeroth' },
      { min: 50,  label: 'Héroe de la Alianza' },
      { min: 100, label: 'Comandante Terran' },
      { min: 200, label: 'Lich King del saber' },
    ],
    achievements: {
      speed1: { name: 'Respuesta de Zerg Rush', desc: 'Responder en <5s' },
      speed2: { name: 'Velocidad de Zul Farrak', desc: '3 rápidas seguidas (<5s)' },
      speed3: { name: 'Instinto de Diablo', desc: '5 consecutivas en <3s' },
      acc1:   { name: 'Primera quest completada', desc: 'Primera correcta en Blizzard' },
      acc2:   { name: 'Grupo dungeon coordinado', desc: '7/10 en una ronda' },
      acc3:   { name: 'Raid perfecta', desc: 'Ronda perfecta 10/10' },
      acc4:   { name: 'GM del servidor', desc: '3 rondas perfectas' },
      duel1:  { name: 'Primer duelo', desc: 'Ganar 1 duelo en Blizzard' },
      duel2:  { name: 'Arena PvP', desc: 'Ganar 5 duelos' },
      duel3:  { name: 'Campeón del BG', desc: 'Ganar 10 duelos' },
      duel4:  { name: 'Gladiador de Blizzard', desc: 'Ganar 20 duelos' },
    }
  },
  { id: 'zelda', categoryId: 'videojuegos', name: 'The Legend of Zelda', icon: '🗡️', color: '#c8a800', colorSoft: 'rgba(200,168,0,0.12)', colorBorder: 'rgba(200,168,0,0.3)', sub: 'Hyrule y sus leyendas', available: true,
    tiers: [
      { min: 0,   label: 'Kokiri del bosque' },
      { min: 25,  label: 'Portador de la Trifuerza' },
      { min: 50,  label: 'Explorador de dungeons' },
      { min: 100, label: 'Caballero de Hyrule' },
      { min: 200, label: 'El Héroe del Tiempo' },
    ],
    achievements: {
      speed1: { name: 'Reflejo de Link', desc: 'Responder en <5s' },
      speed2: { name: 'Flechas del tiempo', desc: '3 rápidas seguidas (<5s)' },
      speed3: { name: 'Maestro Espada veloz', desc: '5 consecutivas en <3s' },
      acc1:   { name: 'Rupee de plata', desc: 'Primera correcta en Zelda' },
      acc2:   { name: 'Llave maestra encontrada', desc: '7/10 en una ronda' },
      acc3:   { name: 'Dungeon sin daño', desc: 'Ronda perfecta 10/10' },
      acc4:   { name: 'Sabio de Hyrule', desc: '3 rondas perfectas' },
      duel1:  { name: 'Primer duelo', desc: 'Ganar 1 duelo en Zelda' },
      duel2:  { name: 'Guardian de templo', desc: 'Ganar 5 duelos' },
      duel3:  { name: 'Campeón de Hyrule', desc: 'Ganar 10 duelos' },
      duel4:  { name: 'Link vs Ganondorf', desc: 'Ganar 20 duelos' },
    }
  },
  { id: 'minecraft', categoryId: 'videojuegos', name: 'Minecraft', icon: '⛏️', color: '#5a8a40', colorSoft: 'rgba(90,138,64,0.12)', colorBorder: 'rgba(90,138,64,0.3)', sub: 'Bloques, biomas y el End', available: true,
    tiers: [
      { min: 0,   label: 'Recién spawneado' },
      { min: 25,  label: 'Constructor de madera' },
      { min: 50,  label: 'Minero de diamante' },
      { min: 100, label: 'Explorador del Nether' },
      { min: 200, label: 'Derrotador del Ender Dragon' },
    ],
    achievements: {
      speed1: { name: 'Crafteo rápido', desc: 'Responder en <5s' },
      speed2: { name: 'Velocidad de Creeper', desc: '3 rápidas seguidas (<5s)' },
      speed3: { name: 'TNT instantáneo', desc: '5 consecutivas en <3s' },
      acc1:   { name: 'Primer bloque colocado', desc: 'Primera correcta en Minecraft' },
      acc2:   { name: 'Mesa de trabajo dominada', desc: '7/10 en una ronda' },
      acc3:   { name: 'Mundo perfecto', desc: 'Ronda perfecta 10/10' },
      acc4:   { name: 'Arquitecto de Minecraftia', desc: '3 rondas perfectas' },
      duel1:  { name: 'Primer duelo', desc: 'Ganar 1 duelo en Minecraft' },
      duel2:  { name: 'Guerrero del PvP', desc: 'Ganar 5 duelos' },
      duel3:  { name: 'Campeón del Hunger Games', desc: 'Ganar 10 duelos' },
      duel4:  { name: 'Rey del servidor', desc: 'Ganar 20 duelos' },
    }
  },
  { id: 'retrogaming', categoryId: 'videojuegos', name: 'Retro Gaming', icon: '👾', color: '#8050c8', colorSoft: 'rgba(128,80,200,0.12)', colorBorder: 'rgba(128,80,200,0.3)', sub: 'Arcade, NES, SNES, Atari', available: true,
    tiers: [
      { min: 0,   label: 'Visitante del arcade' },
      { min: 25,  label: 'Jugador de cuartos' },
      { min: 50,  label: 'High Score local' },
      { min: 100, label: 'Campeón del cabinete' },
      { min: 200, label: 'Leyenda del pixel' },
    ],
    achievements: {
      speed1: { name: 'Reflejos de 8 bits', desc: 'Responder en <5s' },
      speed2: { name: 'Combo de joystick', desc: '3 rápidas seguidas (<5s)' },
      speed3: { name: 'Turbo de 16 bits', desc: '5 consecutivas en <3s' },
      acc1:   { name: 'Insert coin', desc: 'Primera correcta en Retro Gaming' },
      acc2:   { name: 'Continue x2', desc: '7/10 en una ronda' },
      acc3:   { name: 'Perfect run', desc: 'Ronda perfecta 10/10' },
      acc4:   { name: 'TAS runner', desc: '3 rondas perfectas' },
      duel1:  { name: 'Primer duelo', desc: 'Ganar 1 duelo en Retro Gaming' },
      duel2:  { name: 'Rival del cabinete', desc: 'Ganar 5 duelos' },
      duel3:  { name: 'Campeón del torneo 8-bit', desc: 'Ganar 10 duelos' },
      duel4:  { name: 'El campeón del high score', desc: 'Ganar 20 duelos' },
    }
  },
  { id: 'pokemon', categoryId: 'videojuegos', name: 'Pokémon', icon: '⚡', color: '#e8c050', colorSoft: 'rgba(232,192,80,0.12)', colorBorder: 'rgba(232,192,80,0.3)', sub: 'Atrápalos a todos', available: true,
    tiers: [
      { min: 0,  label: 'Entrenador principiante' },
      { min: 25,  label: 'Líder de gimnasio' },
      { min: 50,  label: 'Alto Mando' },
      { min: 100,  label: 'Campeón de la Liga' },
      { min: 200,  label: 'Maestro Pokémon' }
    ],
    achievements: {
      speed1: { name: 'Ataque rápido', desc: 'Responder en <5s' },
      speed2: { name: 'Velocidad máxima', desc: '3 rápidas seguidas (<5s)' },
      speed3: { name: 'Movimiento prioritario', desc: '5 consecutivas en <3s' },
      acc1: { name: 'Primera Pokédex completa', desc: 'Primera correcta en Pokémon' },
      acc2: { name: 'Equipo equilibrado', desc: '7/10 en una ronda' },
      acc3: { name: 'Ronda sin KO', desc: 'Ronda perfecta 10/10' },
      acc4: { name: 'Entrenador perfecto', desc: '3 rondas perfectas' },
      duel1: { name: 'Primer duelo', desc: 'Ganar 1 duelo en Pokémon' },
      duel2: { name: 'Rival del gimnasio', desc: 'Ganar 5 duelos' },
      duel3: { name: 'Retador de la Liga', desc: 'Ganar 10 duelos' },
      duel4: { name: 'Pikachu vs Mewtwo', desc: 'Ganar 20 duelos' }
    }
  },

  { id: 'sonic', categoryId: 'videojuegos', name: 'Sonic the Hedgehog', icon: '💨', color: '#1a6fc4', colorSoft: 'rgba(26,111,196,0.12)', colorBorder: 'rgba(26,111,196,0.3)', sub: 'Gotta go fast — Classic a Frontiers', available: true,
    tiers: [
      { min: 0,   label: 'Recién llegado a Green Hill' },
      { min: 25,  label: 'Corredor principiante' },
      { min: 50,  label: 'Rival de Metal Sonic' },
      { min: 100, label: 'Guardian de las Esmeraldas' },
      { min: 200, label: 'Forma de Vida Suprema' },
    ],
    achievements: {
      speed1: { name: 'Gotta go fast',               desc: 'Responder en <5s' },
      speed2: { name: 'Velocidad sónica',             desc: '3 rápidas seguidas (<5s)' },
      speed3: { name: 'Rompe la barrera del sonido',  desc: '5 consecutivas en <3s' },
      acc1:   { name: 'Primera Esmeralda del Caos',   desc: 'Primera correcta en Sonic' },
      acc2:   { name: 'Compañero de Tails',           desc: '7/10 en una ronda' },
      acc3:   { name: 'Special Stage perfecto',       desc: 'Ronda perfecta 10/10' },
      acc4:   { name: 'Super Sonic desbloqueado',     desc: '3 rondas perfectas' },
      duel1:  { name: 'Primer duelo',                 desc: 'Ganar 1 duelo en Sonic' },
      duel2:  { name: 'Desafío de Angel Island',      desc: 'Ganar 5 duelos' },
      duel3:  { name: 'Campeón del ARK',              desc: 'Ganar 10 duelos' },
      duel4:  { name: 'Sonic vs Shadow',              desc: 'Ganar 20 duelos' },
    }
  },

  // ── SCI-FI ───────────────────────────────────────────────────
  { id: 'starwars', categoryId: 'scifi', name: 'Star Wars', icon: '🌟', color: '#4e8ce8', colorSoft: 'rgba(78,140,232,0.12)', colorBorder: 'rgba(78,140,232,0.3)', sub: 'Una galaxia muy lejana', available: true,
    tiers: [
      { min: 0,  label: 'Youngling del Templo Jedi' },
      { min: 25,  label: 'Padawan en entrenamiento' },
      { min: 50,  label: 'Caballero Jedi' },
      { min: 100,  label: 'Maestro del Consejo' },
      { min: 200,  label: 'Gran Maestro' }
    ],
    achievements: {
      speed1: { name: 'Fuerza instintiva', desc: 'Responder en <5s' },
      speed2: { name: 'Reflejos Jedi', desc: '3 rápidas seguidas (<5s)' },
      speed3: { name: 'Velocidad hiperespacial', desc: '5 consecutivas en <3s' },
      acc1: { name: 'Primer midi-chlorian', desc: 'Primera correcta en Star Wars' },
      acc2: { name: 'Padawan del Templo', desc: '7/10 en una ronda' },
      acc3: { name: 'Caballero Jedi', desc: 'Ronda perfecta 10/10' },
      acc4: { name: 'Maestro del Consejo', desc: '3 rondas perfectas' },
      duel1: { name: 'Primer duelo', desc: 'Ganar 1 duelo en SW' },
      duel2: { name: 'Guardia Imperial', desc: 'Ganar 5 duelos' },
      duel3: { name: 'Inquisidor Sith', desc: 'Ganar 10 duelos' },
      duel4: { name: 'Vader vs Obi-Wan', desc: 'Ganar 20 duelos' }
    }
  },
  { id: 'startrek',  categoryId: 'scifi', name: 'Star Trek',         icon: '🖖', color: '#2060b0', colorSoft: 'rgba(32,96,176,0.12)',  colorBorder: 'rgba(32,96,176,0.3)',  sub: 'La Federación de Planetas', available: true,
    tiers: [
      { min: 0,   label: 'Cadete de la Flota Estelar' },
      { min: 25,  label: 'Oficial de la Federación' },
      { min: 50,  label: 'Teniente de la USS Enterprise' },
      { min: 100, label: 'Capitán condecorado' },
      { min: 200, label: 'Leyenda de la Flota Estelar' },
    ],
    achievements: {
      speed1: { name: 'Reflejos de teletransportador',  desc: 'Responder en <5s' },
      speed2: { name: 'Velocidad de curvatura',         desc: '3 rápidas seguidas (<5s)' },
      speed3: { name: 'Instinto vulcano',               desc: '5 consecutivas en <3s' },
      acc1:   { name: 'Primera misión de exploración',  desc: 'Primera correcta en Star Trek' },
      acc2:   { name: 'Oficial confiable de la nave',   desc: '7/10 en una ronda' },
      acc3:   { name: 'Misión perfecta sin bajas',      desc: 'Ronda perfecta 10/10' },
      acc4:   { name: 'Leyenda de la Flota Estelar',    desc: '3 rondas perfectas' },
      duel1:  { name: 'Primer duelo',                   desc: 'Ganar 1 duelo en Star Trek' },
      duel2:  { name: 'Guardián de la nave nodriza',    desc: 'Ganar 5 duelos' },
      duel3:  { name: 'Campeón de la Federación',       desc: 'Ganar 10 duelos' },
      duel4:  { name: 'Kirk vs Khan',                   desc: 'Ganar 20 duelos' },
    }
  },
  { id: 'bttf', categoryId: 'scifi', name: 'Back to the Future', icon: '⚡', color: '#8040c8', colorSoft: 'rgba(128,64,200,0.12)', colorBorder: 'rgba(128,64,200,0.3)', sub: '88 mph — Doc Brown y Marty McFly', available: true,
    tiers: [
      { min: 0,   label: 'Recién llegado a 1985' },
      { min: 25,  label: 'Pasajero del DeLorean' },
      { min: 50,  label: 'Viajero del tiempo' },
      { min: 100, label: 'Compañero de Doc Brown' },
      { min: 200, label: 'Maestro del Flux Capacitor' },
    ],
    achievements: {
      speed1: { name: 'Reacción a 88mph', desc: 'Responder en <5s' },
      speed2: { name: 'Velocidad del DeLorean', desc: '3 rápidas seguidas (<5s)' },
      speed3: { name: 'Salto temporal', desc: '5 consecutivas en <3s' },
      acc1:   { name: 'Primera chispa de 1.21GW', desc: 'Primera correcta en BTTF' },
      acc2:   { name: 'Estudiante de Doc Brown', desc: '7/10 en una ronda' },
      acc3:   { name: 'El Almanaque Deportivo', desc: 'Ronda perfecta 10/10' },
      acc4:   { name: 'Perfecto como el futuro', desc: '3 rondas perfectas' },
      duel1:  { name: 'Primer duelo', desc: 'Ganar 1 duelo en BTTF' },
      duel2:  { name: 'Campeón del Hill Valley', desc: 'Ganar 5 duelos' },
      duel3:  { name: 'Rival de Biff Tannen', desc: 'Ganar 10 duelos' },
      duel4:  { name: 'Marty vs el Destino', desc: 'Ganar 20 duelos' },
    }
  },

  // ── ANIMADOS ─────────────────────────────────────────────────
  { id: 'disney',    categoryId: 'animados', name: 'Disney',         icon: '🏰', color: '#2080e8', colorSoft: 'rgba(32,128,232,0.12)', colorBorder: 'rgba(32,128,232,0.3)', sub: 'La magia de los clásicos', available: true,
    tiers: [
      { min: 0,   label: 'Visitante del Reino Mágico' },
      { min: 25,  label: 'Aprendiz de cuentos clásicos' },
      { min: 50,  label: 'Príncipe o princesa honorario' },
      { min: 100, label: 'Guardián de la magia Disney' },
      { min: 200, label: 'Leyenda de los clásicos animados' },
    ],
    achievements: {
      speed1: { name: 'Reflejos de hada madrina',       desc: 'Responder en <5s' },
      speed2: { name: 'Velocidad de carruaje encantado', desc: '3 rápidas seguidas (<5s)' },
      speed3: { name: 'Instinto mágico',                desc: '5 consecutivas en <3s' },
      acc1:   { name: 'Primer final feliz',             desc: 'Primera correcta en Disney' },
      acc2:   { name: 'Amigo confiable del reino',      desc: '7/10 en una ronda' },
      acc3:   { name: 'Cuento perfecto',                desc: 'Ronda perfecta 10/10' },
      acc4:   { name: 'Leyenda de los clásicos',        desc: '3 rondas perfectas' },
      duel1:  { name: 'Primer duelo',                   desc: 'Ganar 1 duelo en Disney' },
      duel2:  { name: 'Guardián del castillo',          desc: 'Ganar 5 duelos' },
      duel3:  { name: 'Campeón del Reino Mágico',       desc: 'Ganar 10 duelos' },
      duel4:  { name: 'Héroe vs villano Disney',        desc: 'Ganar 20 duelos' },
    }
  },
  { id: 'rickmorty', categoryId: 'animados', name: 'Rick and Morty', icon: '🛸', color: '#40c870', colorSoft: 'rgba(64,200,112,0.12)', colorBorder: 'rgba(64,200,112,0.3)', sub: 'Wubba lubba dub dub', available: true,
    tiers: [
      { min: 0,   label: 'Morty nervioso' },
      { min: 25,  label: 'Aventurero interdimensional' },
      { min: 50,  label: 'Científico del garage' },
      { min: 100, label: 'Consejero del Consejo Rick' },
      { min: 200, label: 'Rick C-137' },
    ],
    achievements: {
      speed1: { name: 'Burp de conocimiento', desc: 'Responder en <5s' },
      speed2: { name: 'Velocidad del portal gun', desc: '3 rápidas seguidas (<5s)' },
      speed3: { name: 'Mente de Rick Sanchez', desc: '5 consecutivas en <3s' },
      acc1:   { name: 'Primer portal abierto', desc: 'Primera correcta en RM' },
      acc2:   { name: 'Aventura de la semana', desc: '7/10 en una ronda' },
      acc3:   { name: 'Mega semilla perfecta', desc: 'Ronda perfecta 10/10' },
      acc4:   { name: 'El más inteligente del multiverso', desc: '3 rondas perfectas' },
      duel1:  { name: 'Primer duelo', desc: 'Ganar 1 duelo en RM' },
      duel2:  { name: 'Guerrero del Cronenberg', desc: 'Ganar 5 duelos' },
      duel3:  { name: 'Rival del Evil Morty', desc: 'Ganar 10 duelos' },
      duel4:  { name: 'Rick vs el Consejo', desc: 'Ganar 20 duelos' },
    }
  },
  {
    id: 'simpsons', categoryId: 'animados', name: 'The Simpsons', icon: '🍩',
    color: '#e8b84b', colorSoft: 'rgba(232,184,75,0.12)', colorBorder: 'rgba(232,184,75,0.3)',
    sub: "Springfield — D'oh!", available: true,
    tiers: [
      { min: 0,   label: 'Habitante de Springfield' },
      { min: 25,  label: 'Vecino de los Flanders' },
      { min: 50,  label: 'Empleado de la Planta Nuclear' },
      { min: 100, label: 'El Gordo Tony' },
      { min: 200, label: 'Burns Todopoderoso' },
    ],
    achievements: {
      speed1: { name: "D'oh! reflejo",           desc: 'Responder en <5s' },
      speed2: { name: 'Velocidad de Bart',        desc: '3 rápidas seguidas (<5s)' },
      speed3: { name: 'Lisa brillante',           desc: '5 consecutivas en <3s' },
      acc1:   { name: 'Dona del Kwik-E-Mart',     desc: 'Primera correcta en Simpsons' },
      acc2:   { name: 'Fan de la TV con Homer',   desc: '7/10 en una ronda' },
      acc3:   { name: 'Estudiante de Lisa',       desc: 'Ronda perfecta 10/10' },
      acc4:   { name: 'El Abuelo Simpson narra',  desc: '3 rondas perfectas' },
      duel1:  { name: 'Primer duelo',             desc: 'Ganar 1 duelo en Simpsons' },
      duel2:  { name: 'Enemigo de Sideshow Bob',  desc: 'Ganar 5 duelos' },
      duel3:  { name: 'Campeón de Shelbyville',   desc: 'Ganar 10 duelos' },
      duel4:  { name: 'Excelente…',               desc: 'Ganar 20 duelos' },
    }
  },

  // ── SUPERHÉROES ──────────────────────────────────────────────
  { id: 'marvel', categoryId: 'superheroes', name: 'Marvel', icon: '🦸', color: '#ed1d24', colorSoft: 'rgba(237,29,36,0.12)', colorBorder: 'rgba(237,29,36,0.3)', sub: 'El Universo Marvel', available: true,
    tiers: [
      { min: 0,  label: 'Civil de Nueva York' },
      { min: 25,  label: 'Agente SHIELD' },
      { min: 50,  label: 'Héroe de los Vengadores' },
      { min: 100,  label: 'Campeón del Universo' },
      { min: 200,  label: 'Portador de la Gema del Infinito' }
    ],
    achievements: {
      speed1: { name: 'Reflejos de Spider-Man', desc: 'Responder en <5s' },
      speed2: { name: 'Velocidad de Quicksilver', desc: '3 rápidas seguidas (<5s)' },
      speed3: { name: 'Instinto de Black Widow', desc: '5 consecutivas en <3s' },
      acc1: { name: 'Primera misión SHIELD', desc: 'Primera correcta en Marvel' },
      acc2: { name: 'Equipo de los Vengadores', desc: '7/10 en una ronda' },
      acc3: { name: 'Operación perfecta', desc: 'Ronda perfecta 10/10' },
      acc4: { name: 'Director de SHIELD', desc: '3 rondas perfectas' },
      duel1: { name: 'Primer duelo', desc: 'Ganar 1 duelo en Marvel' },
      duel2: { name: 'Héroe callejero', desc: 'Ganar 5 duelos' },
      duel3: { name: 'Campeón de la Torre', desc: 'Ganar 10 duelos' },
      duel4: { name: 'Avengers vs Thanos', desc: 'Ganar 20 duelos' }
    }
  },
  { id: 'dc', categoryId: 'superheroes', name: 'DC Comics', icon: '🦇', color: '#0476f2', colorSoft: 'rgba(4,118,242,0.12)', colorBorder: 'rgba(4,118,242,0.3)', sub: 'Batman, Superman y el multiverso DC', available: true,
    tiers: [
      { min: 0,   label: 'Civil de Metrópolis' },
      { min: 25,  label: 'Alerta de la Liga' },
      { min: 50,  label: 'Héroe de la Liga de la Justicia' },
      { min: 100, label: 'Vigilante de Gotham' },
      { min: 200, label: 'Guardián del Multiverso' },
    ],
    achievements: {
      speed1: { name: 'Velocidad de Flash', desc: 'Responder en <5s' },
      speed2: { name: 'Batarang preciso', desc: '3 rápidas seguidas (<5s)' },
      speed3: { name: 'Instinto del Kryptoniano', desc: '5 consecutivas en <3s' },
      acc1:   { name: 'Primera señal de Batman', desc: 'Primera correcta en DC' },
      acc2:   { name: 'Miembro de la Liga', desc: '7/10 en una ronda' },
      acc3:   { name: 'Sala de la Liga perfecta', desc: 'Ronda perfecta 10/10' },
      acc4:   { name: 'Estratega como Batman', desc: '3 rondas perfectas' },
      duel1:  { name: 'Primer duelo', desc: 'Ganar 1 duelo en DC' },
      duel2:  { name: 'Guardián de Gotham', desc: 'Ganar 5 duelos' },
      duel3:  { name: 'Campeón de la Torre', desc: 'Ganar 10 duelos' },
      duel4:  { name: 'Batman vs Superman', desc: 'Ganar 20 duelos' },
    }
  },
  { id: 'xmen', categoryId: 'superheroes', name: 'X-Men', icon: '☢️', color: '#e8a000', colorSoft: 'rgba(232,160,0,0.12)',  colorBorder: 'rgba(232,160,0,0.3)',  sub: 'Escuela Xavier para mutantes', available: true,
    tiers: [
      { min: 0,   label: 'Estudiante de la Escuela Xavier' },
      { min: 25,  label: 'Mutante en entrenamiento' },
      { min: 50,  label: 'Miembro del equipo X-Men' },
      { min: 100, label: 'Defensor mutante-humano' },
      { min: 200, label: 'Mutante Omega definitivo' },
    ],
    achievements: {
      speed1: { name: 'Reflejos de Wolverine',          desc: 'Responder en <5s' },
      speed2: { name: 'Velocidad de Quicksilver',       desc: '3 rápidas seguidas (<5s)' },
      speed3: { name: 'Telepatía instantánea',          desc: '5 consecutivas en <3s' },
      acc1:   { name: 'Primera lección en la Mansión Xavier', desc: 'Primera correcta en X-Men' },
      acc2:   { name: 'Miembro confiable del equipo',   desc: '7/10 en una ronda' },
      acc3:   { name: 'Misión perfecta de los X-Men',   desc: 'Ronda perfecta 10/10' },
      acc4:   { name: 'Mutante Omega',                  desc: '3 rondas perfectas' },
      duel1:  { name: 'Primer duelo',                   desc: 'Ganar 1 duelo en X-Men' },
      duel2:  { name: 'Defensor de la mansión',         desc: 'Ganar 5 duelos' },
      duel3:  { name: 'Campeón de la Sala de Peligro',  desc: 'Ganar 10 duelos' },
      duel4:  { name: 'X-Men vs Magneto',               desc: 'Ganar 20 duelos' },
    }
  },
  { id: 'invincible', categoryId: 'superheroes', name: 'Invincible', icon: '🟡', color: '#f0c000', colorSoft: 'rgba(240,192,0,0.12)',  colorBorder: 'rgba(240,192,0,0.3)',  sub: 'Mark Grayson y el Viltrumita', available: false, tiers: [], achievements: {} },
  { id: 'batman', categoryId: 'superheroes', name: 'Batman', icon: '🌃', color: '#4a4a58', colorSoft: 'rgba(74,74,88,0.12)', colorBorder: 'rgba(74,74,88,0.3)', sub: 'Gotham City y la noche eterna', available: true,
    tiers: [
      { min: 0,   label: 'Ciudadano de Gotham' },
      { min: 25,  label: 'Vigilante novato' },
      { min: 50,  label: 'Detective de la Mansión Wayne' },
      { min: 100, label: 'Cruzado de la Capa' },
      { min: 200, label: 'El Caballero de la Noche' },
    ],
    achievements: {
      speed1: { name: 'Reflejos de murciélago',         desc: 'Responder en <5s' },
      speed2: { name: 'Batarang en el aire',            desc: '3 rápidas seguidas (<5s)' },
      speed3: { name: 'Instinto detectivesco',          desc: '5 consecutivas en <3s' },
      acc1:   { name: 'Primera pista en la Batcueva',   desc: 'Primera correcta en Batman' },
      acc2:   { name: 'Aliado de Robin',                desc: '7/10 en una ronda' },
      acc3:   { name: 'Caso resuelto a la perfección',  desc: 'Ronda perfecta 10/10' },
      acc4:   { name: 'Genio como Bruce Wayne',         desc: '3 rondas perfectas' },
      duel1:  { name: 'Primer duelo',                   desc: 'Ganar 1 duelo en Batman' },
      duel2:  { name: 'Patrulla de Gotham',             desc: 'Ganar 5 duelos' },
      duel3:  { name: 'Terror de Arkham',               desc: 'Ganar 10 duelos' },
      duel4:  { name: 'Batman vs Joker',                desc: 'Ganar 20 duelos' },
    }
  },
  { id: 'superman', categoryId: 'superheroes', name: 'Superman', icon: '🔷', color: '#1a4fa0', colorSoft: 'rgba(26,79,160,0.12)', colorBorder: 'rgba(26,79,160,0.3)', sub: 'Metrópolis y más allá de las estrellas', available: true,
    tiers: [
      { min: 0,   label: 'Ciudadano de Metrópolis' },
      { min: 25,  label: 'Reportero del Daily Planet' },
      { min: 50,  label: 'Defensor de Metrópolis' },
      { min: 100, label: 'Hijo de Krypton' },
      { min: 200, label: 'El Hombre de Acero' },
    ],
    achievements: {
      speed1: { name: 'Visión de rayos X',              desc: 'Responder en <5s' },
      speed2: { name: 'Más rápido que una bala',        desc: '3 rápidas seguidas (<5s)' },
      speed3: { name: 'Súper velocidad kryptoniana',    desc: '5 consecutivas en <3s' },
      acc1:   { name: 'Primer vuelo sobre Metrópolis',  desc: 'Primera correcta en Superman' },
      acc2:   { name: 'Aliado de la Liga',              desc: '7/10 en una ronda' },
      acc3:   { name: 'Hazaña heroica perfecta',        desc: 'Ronda perfecta 10/10' },
      acc4:   { name: 'Último hijo de Krypton',         desc: '3 rondas perfectas' },
      duel1:  { name: 'Primer duelo',                   desc: 'Ganar 1 duelo en Superman' },
      duel2:  { name: 'Guardián del cielo',             desc: 'Ganar 5 duelos' },
      duel3:  { name: 'Campeón de Metrópolis',          desc: 'Ganar 10 duelos' },
      duel4:  { name: 'Superman vs Lex Luthor',         desc: 'Ganar 20 duelos' },
    }
  },
  { id: 'wonderwoman', categoryId: 'superheroes', name: 'Wonder Woman', icon: '⭐', color: '#c9a227', colorSoft: 'rgba(201,162,39,0.12)', colorBorder: 'rgba(201,162,39,0.3)', sub: 'Themyscira y el mundo de los hombres', available: true,
    tiers: [
      { min: 0,   label: 'Visitante de Themyscira' },
      { min: 25,  label: 'Guerrera Amazona' },
      { min: 50,  label: 'Portadora del Lazo de la Verdad' },
      { min: 100, label: 'Campeona de la Liga de la Justicia' },
      { min: 200, label: 'Princesa de las Amazonas' },
    ],
    achievements: {
      speed1: { name: 'Reflejos amazónicos',            desc: 'Responder en <5s' },
      speed2: { name: 'Brazaletes a prueba de balas',   desc: '3 rápidas seguidas (<5s)' },
      speed3: { name: 'Velocidad de Themyscira',        desc: '5 consecutivas en <3s' },
      acc1:   { name: 'Primer juramento amazónico',     desc: 'Primera correcta en Wonder Woman' },
      acc2:   { name: 'Guerrera entrenada en Themyscira', desc: '7/10 en una ronda' },
      acc3:   { name: 'Verdad perfecta del Lazo',       desc: 'Ronda perfecta 10/10' },
      acc4:   { name: 'Heroína legendaria',             desc: '3 rondas perfectas' },
      duel1:  { name: 'Primer duelo',                   desc: 'Ganar 1 duelo en Wonder Woman' },
      duel2:  { name: 'Defensora del Paraíso',          desc: 'Ganar 5 duelos' },
      duel3:  { name: 'Campeona de la arena',           desc: 'Ganar 10 duelos' },
      duel4:  { name: 'Wonder Woman vs Ares',           desc: 'Ganar 20 duelos' },
    }
  },
  { id: 'spiderman', categoryId: 'superheroes', name: 'Spider-Man', icon: '🕷️', color: '#c41230', colorSoft: 'rgba(196,18,48,0.12)', colorBorder: 'rgba(196,18,48,0.3)', sub: 'Nueva York bajo la responsabilidad de un héroe', available: true,
    tiers: [
      { min: 0,   label: 'Estudiante de Queens' },
      { min: 25,  label: 'Vecino y amigable Hombre Araña' },
      { min: 50,  label: 'Tejedor de telarañas de Manhattan' },
      { min: 100, label: 'Vengador arácnido' },
      { min: 200, label: 'El Hombre Araña definitivo' },
    ],
    achievements: {
      speed1: { name: 'Sentido arácnido activado',      desc: 'Responder en <5s' },
      speed2: { name: 'Reflejos de telaraña',           desc: '3 rápidas seguidas (<5s)' },
      speed3: { name: 'Swing veloz entre rascacielos',  desc: '5 consecutivas en <3s' },
      acc1:   { name: 'Primera foto para el Daily Bugle', desc: 'Primera correcta en Spider-Man' },
      acc2:   { name: 'Aliado de los Vengadores',       desc: '7/10 en una ronda' },
      acc3:   { name: 'Patrulla perfecta de Queens',    desc: 'Ronda perfecta 10/10' },
      acc4:   { name: 'Gran poder, gran responsabilidad', desc: '3 rondas perfectas' },
      duel1:  { name: 'Primer duelo',                   desc: 'Ganar 1 duelo en Spider-Man' },
      duel2:  { name: 'Guardián de Manhattan',          desc: 'Ganar 5 duelos' },
      duel3:  { name: 'Campeón de Nueva York',          desc: 'Ganar 10 duelos' },
      duel4:  { name: 'Spider-Man vs Green Goblin',     desc: 'Ganar 20 duelos' },
    }
  },
  { id: 'deadpool', categoryId: 'superheroes', name: 'Deadpool', icon: '🩹', color: '#8b0c1a', colorSoft: 'rgba(139,12,26,0.12)', colorBorder: 'rgba(139,12,26,0.3)', sub: 'El Mercenario Bocazas, cuarta pared incluida', available: true,
    tiers: [
      { min: 0,   label: 'Mercenario novato' },
      { min: 25,  label: 'Experimento de Weapon X' },
      { min: 50,  label: 'Antihéroe con factor curativo' },
      { min: 100, label: 'Rompedor de la cuarta pared' },
      { min: 200, label: 'El Mercenario Bocazas definitivo' },
    ],
    achievements: {
      speed1: { name: 'Regeneración instantánea',      desc: 'Responder en <5s' },
      speed2: { name: 'Katanas gemelas veloces',        desc: '3 rápidas seguidas (<5s)' },
      speed3: { name: 'Chimichanga turbo',              desc: '5 consecutivas en <3s' },
      acc1:   { name: 'Primer chiste de la cuarta pared', desc: 'Primera correcta en Deadpool' },
      acc2:   { name: 'Mercenario confiable (a veces)', desc: '7/10 en una ronda' },
      acc3:   { name: 'Misión perfecta sin morir (otra vez)', desc: 'Ronda perfecta 10/10' },
      acc4:   { name: 'Leyenda inmortal de Marvel',     desc: '3 rondas perfectas' },
      duel1:  { name: 'Primer duelo',                   desc: 'Ganar 1 duelo en Deadpool' },
      duel2:  { name: 'Pelea de bar en Sister Margaret', desc: 'Ganar 5 duelos' },
      duel3:  { name: 'Campeón del caos',               desc: 'Ganar 10 duelos' },
      duel4:  { name: 'Deadpool vs Cable',              desc: 'Ganar 20 duelos' },
    }
  },
  { id: 'hellboy', categoryId: 'superheroes', name: 'Hellboy', icon: '🔥', color: '#b8443a', colorSoft: 'rgba(184,68,58,0.12)', colorBorder: 'rgba(184,68,58,0.3)', sub: 'El B.P.R.D. y lo paranormal', available: true,
    tiers: [
      { min: 0,   label: 'Recluta del B.P.R.D.' },
      { min: 25,  label: 'Investigador paranormal' },
      { min: 50,  label: 'Cazador de criaturas ocultas' },
      { min: 100, label: 'Campeón del Bien a pesar del destino' },
      { min: 200, label: 'El hijo de la Anung Un Rama' },
    ],
    achievements: {
      speed1: { name: 'Puñetazo de la Mano Derecha del Destino', desc: 'Responder en <5s' },
      speed2: { name: 'Reflejos sobrenaturales',        desc: '3 rápidas seguidas (<5s)' },
      speed3: { name: 'Instinto del B.P.R.D.',          desc: '5 consecutivas en <3s' },
      acc1:   { name: 'Primer caso paranormal resuelto', desc: 'Primera correcta en Hellboy' },
      acc2:   { name: 'Agente confiable del Bureau',    desc: '7/10 en una ronda' },
      acc3:   { name: 'Investigación perfecta',         desc: 'Ronda perfecta 10/10' },
      acc4:   { name: 'Leyenda del ocultismo',          desc: '3 rondas perfectas' },
      duel1:  { name: 'Primer duelo',                   desc: 'Ganar 1 duelo en Hellboy' },
      duel2:  { name: 'Guardián de lo oculto',          desc: 'Ganar 5 duelos' },
      duel3:  { name: 'Campeón del inframundo',         desc: 'Ganar 10 duelos' },
      duel4:  { name: 'Hellboy vs la Apocalipsis',      desc: 'Ganar 20 duelos' },
    }
  },
  { id: 'spawn', categoryId: 'superheroes', name: 'Spawn', icon: '👹', color: '#1a3d1a', colorSoft: 'rgba(26,61,26,0.12)', colorBorder: 'rgba(26,61,26,0.3)', sub: 'El infierno y las calles de Nueva York', available: true,
    tiers: [
      { min: 0,   label: 'Alma perdida del Infierno' },
      { min: 25,  label: 'Hellspawn novato' },
      { min: 50,  label: 'Portador de la capa de ánimas' },
      { min: 100, label: 'Soldado del Ejército de la Oscuridad' },
      { min: 200, label: 'El Hellspawn definitivo' },
    ],
    achievements: {
      speed1: { name: 'Cadenas veloces',                desc: 'Responder en <5s' },
      speed2: { name: 'Capa simbiótica reactiva',       desc: '3 rápidas seguidas (<5s)' },
      speed3: { name: 'Instinto del infierno',          desc: '5 consecutivas en <3s' },
      acc1:   { name: 'Primer pacto con Malebolgia',    desc: 'Primera correcta en Spawn' },
      acc2:   { name: 'Aliado en las calles',           desc: '7/10 en una ronda' },
      acc3:   { name: 'Venganza perfecta',              desc: 'Ronda perfecta 10/10' },
      acc4:   { name: 'Leyenda del Infierno',           desc: '3 rondas perfectas' },
      duel1:  { name: 'Primer duelo',                   desc: 'Ganar 1 duelo en Spawn' },
      duel2:  { name: 'Guardián de los callejones',     desc: 'Ganar 5 duelos' },
      duel3:  { name: 'Campeón del inframundo',         desc: 'Ganar 10 duelos' },
      duel4:  { name: 'Spawn vs Malebolgia',            desc: 'Ganar 20 duelos' },
    }
  },

  // ── ANIME ────────────────────────────────────────────────────
  { id: 'dragonball', categoryId: 'anime', name: 'Dragon Ball',  icon: '🔴', color: '#e87020', colorSoft: 'rgba(232,112,32,0.12)', colorBorder: 'rgba(232,112,32,0.3)', sub: 'El poder del ki',           available: true,
    tiers: [
      { min: 0,   label: 'Terrícola curioso' },
      { min: 25,   label: 'Guerrero Z' },
      { min: 50,   label: 'Super Saiyan' },
      { min: 100,   label: 'Super Saiyan Blue' },
      { min: 200,   label: 'Ultra Instinto' },
    ],
    achievements: {
      speed1: { name: 'Mente de combatiente', desc: 'Responder en <5s' },
      speed2: { name: 'Velocidad de Goku', desc: '3 rápidas seguidas (<5s)' },
      speed3: { name: 'Instinto Superior', desc: '5 consecutivas en <3s' },
      acc1: { name: 'Primera Cápsula Hoi-Poi', desc: 'Primera correcta en DB' },
      acc2: { name: 'Entrenamiento en la Cámara', desc: '7/10 en una ronda' },
      acc3: { name: 'Kamehameha perfecto', desc: 'Ronda perfecta 10/10' },
      acc4: { name: 'Maestro Roshi aprueba', desc: '3 rondas perfectas' },
      duel1: { name: 'Primer duelo', desc: 'Ganar 1 duelo en DB' },
      duel2: { name: 'Rival del Torneo', desc: 'Ganar 5 duelos' },
      duel3: { name: 'Campeón de las Artes', desc: 'Ganar 10 duelos' },
      duel4: { name: 'Goku vs Vegeta', desc: 'Ganar 20 duelos' },
    }
   },
  { id: 'naruto', categoryId: 'anime', name: 'Naruto', icon: '🍃', color: '#e8a020', colorSoft: 'rgba(232,160,32,0.12)', colorBorder: 'rgba(232,160,32,0.3)', sub: 'Konoha y el mundo ninja', available: true,
    tiers: [
      { min: 0,   label: 'Estudiante de la Academia' },
      { min: 25,  label: 'Genin de Konoha' },
      { min: 50,  label: 'Chunin del examen' },
      { min: 100, label: 'Jonin de élite' },
      { min: 200, label: 'Hokage del saber' },
    ],
    achievements: {
      speed1: { name: 'Sello de manos rápido', desc: 'Responder en <5s' },
      speed2: { name: 'Velocidad de Rock Lee', desc: '3 rápidas seguidas (<5s)' },
      speed3: { name: 'Jutsu del Instante', desc: '5 consecutivas en <3s' },
      acc1:   { name: 'Primer rasengan', desc: 'Primera correcta en Naruto' },
      acc2:   { name: 'Equipo 7 coordinado', desc: '7/10 en una ronda' },
      acc3:   { name: 'Modo Sabio perfecto', desc: 'Ronda perfecta 10/10' },
      acc4:   { name: 'Maestro de los Ninjutsu', desc: '3 rondas perfectas' },
      duel1:  { name: 'Primer duelo', desc: 'Ganar 1 duelo en Naruto' },
      duel2:  { name: 'Campeón del Chunin', desc: 'Ganar 5 duelos' },
      duel3:  { name: 'Rival de Sasuke', desc: 'Ganar 10 duelos' },
      duel4:  { name: 'Naruto vs Pain', desc: 'Ganar 20 duelos' },
    }
  },
  { id: 'onepiece', categoryId: 'anime', name: 'One Piece', icon: '🏴‍☠️', color: '#c83020', colorSoft: 'rgba(200,48,32,0.12)', colorBorder: 'rgba(200,48,32,0.3)', sub: 'El Gran Azul y el One Piece', available: true,
    tiers: [
      { min: 0,   label: 'Pirata sin recompensa' },
      { min: 25,  label: 'Tripulante del Sunny' },
      { min: 50,  label: 'Capitán del Gran Azul' },
      { min: 100, label: 'Supernova del New World' },
      { min: 200, label: 'Aspirante al One Piece' },
    ],
    achievements: {
      speed1: { name: 'Velocidad de Gear Second', desc: 'Responder en <5s' },
      speed2: { name: 'Shigan de Lucci', desc: '3 rápidas seguidas (<5s)' },
      speed3: { name: 'Haki de observación', desc: '5 consecutivas en <3s' },
      acc1:   { name: 'Primera fruta del diablo', desc: 'Primera correcta en OP' },
      acc2:   { name: 'Tripulación de Luffy', desc: '7/10 en una ronda' },
      acc3:   { name: 'Pirata perfecto', desc: 'Ronda perfecta 10/10' },
      acc4:   { name: 'Yonko del conocimiento', desc: '3 rondas perfectas' },
      duel1:  { name: 'Primer duelo', desc: 'Ganar 1 duelo en OP' },
      duel2:  { name: 'Duelos en el Grand Line', desc: 'Ganar 5 duelos' },
      duel3:  { name: 'Campeón del Coliseo', desc: 'Ganar 10 duelos' },
      duel4:  { name: 'Luffy vs Kaido', desc: 'Ganar 20 duelos' },
    }
  },
  { id: 'avatar', categoryId: 'anime', name: 'Avatar', icon: '🌊', color: '#20a0c8', colorSoft: 'rgba(32,160,200,0.12)', colorBorder: 'rgba(32,160,200,0.3)', sub: 'Los cuatro elementos', available: true,
    tiers: [
      { min: 0,   label: 'Novato sin doblaje' },
      { min: 25,  label: 'Aprendiz de elemento' },
      { min: 50,  label: 'Doblador intermedio' },
      { min: 100, label: 'Maestro del elemento' },
      { min: 200, label: 'El Avatar despierto' },
    ],
    achievements: {
      speed1: { name: 'Reflejo del Viento', desc: 'Responder en <5s' },
      speed2: { name: 'Velocidad de Azula', desc: '3 rápidas seguidas (<5s)' },
      speed3: { name: 'Estado Avatar instantáneo', desc: '5 consecutivas en <3s' },
      acc1:   { name: 'Primera llama', desc: 'Primera correcta en Avatar' },
      acc2:   { name: 'Estudiante de Iroh', desc: '7/10 en una ronda' },
      acc3:   { name: 'Dominio de los 4 elementos', desc: 'Ronda perfecta 10/10' },
      acc4:   { name: 'El Avatar perfecto', desc: '3 rondas perfectas' },
      duel1:  { name: 'Primer duelo', desc: 'Ganar 1 duelo en Avatar' },
      duel2:  { name: 'Combate en Ba Sing Se', desc: 'Ganar 5 duelos' },
      duel3:  { name: 'Rival de Azula', desc: 'Ganar 10 duelos' },
      duel4:  { name: 'Aang vs Ozai', desc: 'Ganar 20 duelos' },
    }
  },

  // ── WARHAMMER ────────────────────────────────────────────────
  { id: 'warhammer', categoryId: 'videojuegos', showInAll: false, name: 'Warhammer', icon: '💀', color: '#7a4020', colorSoft: 'rgba(122,64,32,0.12)', colorBorder: 'rgba(122,64,32,0.3)', sub: 'En el grimdark futuro lejano', available: true,
    tiers: [
      { min: 0,   label: 'Recluta del Imperio' },
      { min: 25,  label: 'Soldado de la Guardia' },
      { min: 50,  label: 'Capellán de batalla' },
      { min: 100, label: 'Comandante Space Marine' },
      { min: 200, label: 'Maestro del Caos eterno' },
    ],
    achievements: {
      speed1: { name: 'Disparo de bolter',      desc: 'Responder en <5s' },
      speed2: { name: 'Carga de la caballería', desc: '3 rápidas seguidas (<5s)' },
      speed3: { name: 'Instinto del Caos',      desc: '5 consecutivas en <3s' },
      acc1:   { name: 'Primer estandarte tomado', desc: 'Primera correcta en Warhammer' },
      acc2:   { name: 'Escuadra coordinada',    desc: '7/10 en una ronda' },
      acc3:   { name: 'Táctica perfecta',       desc: 'Ronda perfecta 10/10' },
      acc4:   { name: 'Estratega de guerra total', desc: '3 rondas perfectas' },
      duel1:  { name: 'Primer duelo',           desc: 'Ganar 1 duelo en Warhammer' },
      duel2:  { name: 'Héroe de la batalla',    desc: 'Ganar 5 duelos' },
      duel3:  { name: 'Campeón del campo',      desc: 'Ganar 10 duelos' },
      duel4:  { name: 'El último en pie',       desc: 'Ganar 20 duelos' },
    }
  },

  // ── DEPORTES ─────────────────────────────────────────────────
  { id: 'futbol', categoryId: 'deportes', showInAll: false, name: 'Fútbol Mundial', icon: '⚽', color: '#28a050', colorSoft: 'rgba(40,160,80,0.12)', colorBorder: 'rgba(40,160,80,0.3)', sub: 'Mundiales, leyendas y datos', available: true,
    tiers: [
      { min: 0,   label: 'Hincha de barrio' },
      { min: 25,  label: 'Socio del club' },
      { min: 50,  label: 'Comentarista amateur' },
      { min: 100, label: 'Periodista deportivo' },
      { min: 200, label: 'Enciclopedia del fútbol' },
    ],
    achievements: {
      speed1: { name: 'Reacción de portero',    desc: 'Responder en <5s' },
      speed2: { name: 'Velocidad de extremo',   desc: '3 rápidas seguidas (<5s)' },
      speed3: { name: 'Gambeta instantánea',    desc: '5 consecutivas en <3s' },
      acc1:   { name: 'Primer gol',             desc: 'Primera correcta en Fútbol Mundial' },
      acc2:   { name: 'Goleador del torneo',    desc: '7/10 en una ronda' },
      acc3:   { name: 'Ronda perfecta',         desc: 'Ronda perfecta 10/10' },
      acc4:   { name: 'Pelota de oro',          desc: '3 rondas perfectas' },
      duel1:  { name: 'Primer duelo',           desc: 'Ganar 1 duelo en Fútbol' },
      duel2:  { name: 'Capitán de la selección',desc: 'Ganar 5 duelos' },
      duel3:  { name: 'Finalista del Mundial',  desc: 'Ganar 10 duelos' },
      duel4:  { name: 'Campeón del Mundo',      desc: 'Ganar 20 duelos' },
    }
  },

  // ── F1 (deportes) ─────────────────────────────────────────────
  { id: 'formula1', categoryId: 'deportes', name: 'Fórmula 1', icon: '🏎️', color: '#e8002d', colorSoft: 'rgba(232,0,45,0.12)', colorBorder: 'rgba(232,0,45,0.3)', sub: 'Pilotos, escuderías y circuitos', available: true,
    tiers: [
      { min: 0,   label: 'Aficionado del paddock' },
      { min: 25,  label: 'Mecánico de boxes' },
      { min: 50,  label: 'Ingeniero de carrera' },
      { min: 100, label: 'Director técnico' },
      { min: 200, label: 'Campeón del mundo' },
    ],
    achievements: {
      speed1: { name: 'Reacción en boxes',       desc: 'Responder en <5s' },
      speed2: { name: 'Velocidad punta',          desc: '3 rápidas seguidas (<5s)' },
      speed3: { name: 'Vuelta rápida',            desc: '5 consecutivas en <3s' },
      acc1:   { name: 'Primer punto',             desc: 'Primera correcta en F1' },
      acc2:   { name: 'Zona de puntos',           desc: '7/10 en una ronda' },
      acc3:   { name: 'Podio perfecto',           desc: 'Ronda perfecta 10/10' },
      acc4:   { name: 'Victoria dominante',       desc: '3 rondas perfectas' },
      duel1:  { name: 'Primer duelo',             desc: 'Ganar 1 duelo en F1' },
      duel2:  { name: 'Rival de escudería',       desc: 'Ganar 5 duelos' },
      duel3:  { name: 'Batalla en pista',         desc: 'Ganar 10 duelos' },
      duel4:  { name: 'Ayrton Senna del quiz',    desc: 'Ganar 20 duelos' },
    }
  },

  // ── NBA (deportes) ─────────────────────────────────────────────
  { id: 'nba', categoryId: 'deportes', name: 'NBA', icon: '🏀', color: '#c9572a', colorSoft: 'rgba(201,87,42,0.12)', colorBorder: 'rgba(201,87,42,0.3)', sub: 'La mejor liga de básquet', available: true,
    tiers: [
      { min: 0,   label: 'Fan de las gradas' },
      { min: 25,  label: 'Jugador de pick-up' },
      { min: 50,  label: 'Scouter de talentos' },
      { min: 100, label: 'Analista de franquicia' },
      { min: 200, label: 'Hall of Fame' },
    ],
    achievements: {
      speed1: { name: 'Instinto de cancha',       desc: 'Responder en <5s' },
      speed2: { name: 'Fast break mental',        desc: '3 rápidas seguidas (<5s)' },
      speed3: { name: 'Crossover instantáneo',    desc: '5 consecutivas en <3s' },
      acc1:   { name: 'Primer triple',            desc: 'Primera correcta en NBA' },
      acc2:   { name: 'Doble-doble',              desc: '7/10 en una ronda' },
      acc3:   { name: 'Triple-doble',             desc: 'Ronda perfecta 10/10' },
      acc4:   { name: 'MVP de la ronda',          desc: '3 rondas perfectas' },
      duel1:  { name: 'Primer duelo',             desc: 'Ganar 1 duelo en NBA' },
      duel2:  { name: 'Rivalry clásico',          desc: 'Ganar 5 duelos' },
      duel3:  { name: 'Playoffs champion',        desc: 'Ganar 10 duelos' },
      duel4:  { name: 'Jordan vs LeBron',         desc: 'Ganar 20 duelos' },
    }
  },

  // ── JURASSIC PARK (scifi) ──────────────────────────────────────
  { id: 'jurassic', categoryId: 'scifi', name: 'Jurassic Park', icon: '🦕', color: '#5a8a40', colorSoft: 'rgba(90,138,64,0.12)', colorBorder: 'rgba(90,138,64,0.3)', sub: 'La vida siempre encuentra el camino', available: true,
    tiers: [
      { min: 0,   label: 'Visitante del parque' },
      { min: 25,  label: 'Técnico de sistemas' },
      { min: 50,  label: 'Paleontólogo junior' },
      { min: 100, label: 'Doctor Malcolm' },
      { min: 200, label: 'Alan Grant del quiz' },
    ],
    achievements: {
      speed1: { name: 'Reflejos de T-Rex',        desc: 'Responder en <5s' },
      speed2: { name: 'Correr como un raptor',    desc: '3 rápidas seguidas (<5s)' },
      speed3: { name: 'Teoría del caos',          desc: '5 consecutivas en <3s' },
      acc1:   { name: 'Bienvenido al parque',     desc: 'Primera correcta en JP' },
      acc2:   { name: 'Dinosaurio conocedor',     desc: '7/10 en una ronda' },
      acc3:   { name: 'Perfecto como el ADN',     desc: 'Ronda perfecta 10/10' },
      acc4:   { name: 'Hammond aprueba',          desc: '3 rondas perfectas' },
      duel1:  { name: 'Primer duelo',             desc: 'Ganar 1 duelo en JP' },
      duel2:  { name: 'Caza de raptores',         desc: 'Ganar 5 duelos' },
      duel3:  { name: 'Superviviente del parque', desc: 'Ganar 10 duelos' },
      duel4:  { name: 'La vida siempre gana',     desc: 'Ganar 20 duelos' },
    }
  },

  // ── MAD MEN (series) ───────────────────────────────────────────
  { id: 'madmen', categoryId: 'series', name: 'Mad Men', icon: '🥃', color: '#8b6914', colorSoft: 'rgba(139,105,20,0.12)', colorBorder: 'rgba(139,105,20,0.3)', sub: 'Sterling Cooper — Madison Ave.', available: true,
    tiers: [
      { min: 0,   label: 'Secretaria de planta' },
      { min: 25,  label: 'Junior copywriter' },
      { min: 50,  label: 'Account executive' },
      { min: 100, label: 'Socio de la agencia' },
      { min: 200, label: 'Don Draper del quiz' },
    ],
    achievements: {
      speed1: { name: 'Mente de publicista',      desc: 'Responder en <5s' },
      speed2: { name: 'Pitch instantáneo',        desc: '3 rápidas seguidas (<5s)' },
      speed3: { name: 'El Pase Carousel',         desc: '5 consecutivas en <3s' },
      acc1:   { name: 'Primer Old Fashioned',     desc: 'Primera correcta en Mad Men' },
      acc2:   { name: 'Reunión exitosa',          desc: '7/10 en una ronda' },
      acc3:   { name: 'Campaña perfecta',         desc: 'Ronda perfecta 10/10' },
      acc4:   { name: 'Socio fundador',           desc: '3 rondas perfectas' },
      duel1:  { name: 'Primer duelo',             desc: 'Ganar 1 duelo en Mad Men' },
      duel2:  { name: 'Rivalidad en la agencia',  desc: 'Ganar 5 duelos' },
      duel3:  { name: 'Don vs Pete',              desc: 'Ganar 10 duelos' },
      duel4:  { name: 'Leyenda de Madison Ave.',  desc: 'Ganar 20 duelos' },
    }
  },
]

export function getUniverseById(id) {
  return UNIVERSES.find(u => u.id === id)
}

export function getTierLabel(universe, correctTotal) {
  if (!universe?.tiers?.length) return 'Iniciado'
  return [...universe.tiers].reverse().find(t => correctTotal >= t.min)?.label || universe.tiers[0].label
}

export const GAME_MODES = [
  { id: 'clasico',       name: 'Clásico',          icon: '⚔️', desc: 'Turnos alternados — 10 preguntas cada uno', questionsPerPlayer: 10 },
  { id: 'elquemassabe',  name: 'El que más sabe',   icon: '🧠', desc: 'Cada jugador elige su universo especialidad', questionsPerPlayer: 10 },
  { id: 'canonicofalso', name: 'Canónico o Falso',  icon: '🎭', desc: 'Solo preguntas de Verdadero o Falso', questionsPerPlayer: 10 },
  { id: 'duelo',         name: 'Modo Duelo',        icon: '⚡', desc: 'Ambos ven la pregunta — primero en responder gana', questionsPerPlayer: 10 },
]
