const mundial2026Questions = [

  // ── EL TORNEO 2026 ───────────────────────────────────────────
  {t:"m",q:"¿Cuántos países co-organizan el Mundial 2026, siendo la primera vez en la historia que son tres?",o:["2 países","3 países","4 países","Solo 1 país"],a:1,exp:"Estados Unidos, Canadá y México son los tres países co-anfitriones del Mundial 2026, la primera vez en la historia que tres naciones comparten una Copa del Mundo.",extra:"La candidatura conjunta fue presentada en 2017 y seleccionada en junio de 2018 durante el Congreso de la FIFA en Moscú. Competía contra la candidatura de Marruecos."},
  {t:"m",q:"¿Cuántos equipos participarán en el Mundial 2026, un 50% más que en ediciones anteriores de 32 equipos?",o:["40 equipos","44 equipos","48 equipos","56 equipos"],a:2,exp:"El Mundial 2026 tendrá 48 selecciones, el mayor número en la historia del torneo. Significa un salto de 16 equipos respecto al formato de 32 que rigió desde 1998.",extra:"El aumento busca dar más representación a África, Asia y CONCACAF. Implica más partidos pero también más cuidado en la calidad del torneo."},
  {t:"m",q:"¿En qué estadio se jugará la final del Mundial 2026?",o:["Rose Bowl (Los Ángeles)","AT&T Stadium (Dallas)","MetLife Stadium (Nueva York/Nueva Jersey)","Hard Rock Stadium (Miami)"],a:2,exp:"La final del Mundial 2026 se disputará en el MetLife Stadium, ubicado en East Rutherford, Nueva Jersey, en el área metropolitana de Nueva York.",extra:"El MetLife Stadium tiene capacidad para más de 82.500 espectadores. Es el hogar de los NY Giants y NY Jets de la NFL, adaptado para el fútbol."},
  {t:"m",q:"¿Cuántos partidos se disputarán en total en el Mundial 2026?",o:["64 partidos","80 partidos","104 partidos","96 partidos"],a:2,exp:"El Mundial 2026 tendrá 104 partidos, comparado con los 64 de ediciones de 32 equipos. Es un aumento significativo del 62% en número de partidos.",extra:"Los 104 partidos se distribuyen en fase de grupos (96 partidos de grupos), ronda de 16, cuartos, semifinales, partido por el tercer puesto y final."},
  {t:"m",q:"¿Cuántas ciudades sede tendrá el Mundial 2026 entre los tres países anfitriones?",o:["12 ciudades","14 ciudades","16 ciudades","20 ciudades"],a:2,exp:"El Mundial 2026 tendrá 16 ciudades sede: 11 en Estados Unidos, 2 en Canadá (Vancouver y Toronto) y 3 en México (Ciudad de México, Guadalajara y Monterrey).",extra:"Nunca antes un Mundial tuvo tantas ciudades sede. Los viajes entre países harán del 2026 un torneo logísticamente único en la historia del fútbol."},
  {t:"m",q:"¿Cuántas ciudades aporta México como sede del Mundial 2026?",o:["1 ciudad","2 ciudades","3 ciudades","4 ciudades"],a:2,exp:"México aporta tres ciudades: Ciudad de México (Estadio Azteca), Guadalajara (Estadio Akron) y Monterrey (Estadio BBVA).",extra:"México ya organizó los Mundiales de 1970 y 1986. La participación en 2026 lo convertirá en el único país que habrá co-organizado o albergado tres Mundiales masculinos."},
  {t:"m",q:"¿Cuántas ciudades aporta Canadá como sede del Mundial 2026?",o:["1 ciudad","2 ciudades","3 ciudades","4 ciudades"],a:1,exp:"Canadá aporta dos ciudades sede: Vancouver (BC Place) y Toronto (BMO Field), siendo la primera vez que Canadá alberga un Mundial masculino.",extra:"BC Place en Vancouver tiene capacidad para 54.500 espectadores. Para el Mundial se instalará césped natural temporal. Canadá sí organizó el Mundial Femenino en 2015."},
  {t:"f",q:"El partido inaugural del Mundial 2026 se jugará en el Estadio Azteca de la Ciudad de México.",o:["Verdadero","Falso"],a:0,exp:"Verdadero. El partido inaugural del Mundial 2026 está programado para el 11 de junio de 2026 en el Estadio Azteca, como reconocimiento al rol histórico de México.",extra:"Este detalle fue parte de las negociaciones de la candidatura. El Azteca inaugurando el torneo es un guiño al papel clave de México en la historia del fútbol mundial."},
  {t:"m",q:"¿Cuándo comenzará el Mundial 2026 y cuándo se jugará la final?",o:["1 junio - 10 julio","11 junio - 19 julio","15 mayo - 30 junio","20 junio - 25 julio"],a:1,exp:"El Mundial 2026 transcurrirá del 11 de junio al 19 de julio, con 39 días de competición entre los tres países anfitriones.",extra:"La duración de 39 días es similar a ediciones anteriores de 32 equipos. Con 48 equipos y 104 partidos, el calendario es ajustado pero manejable."},
  {t:"m",q:"¿Cuál es el nuevo formato de la fase de grupos del Mundial 2026?",o:["8 grupos de 6 equipos","12 grupos de 4 equipos","6 grupos de 8 equipos","10 grupos de 4 equipos y 2 de 4"],a:1,exp:"El Mundial 2026 tiene 12 grupos de 4 equipos. Los dos primeros de cada grupo y los 8 mejores terceros clasificados avanzan a una ronda de 32 equipos (octavos de final).",extra:"El formato de 'los mejores terceros' es similar al usado en el Mundial de 24 equipos (1982-1994). Genera expectativa hasta el final de la fase de grupos."},
  {t:"f",q:"Los tres países anfitriones (Estados Unidos, Canadá y México) clasifican automáticamente al Mundial 2026 sin necesidad de pasar por eliminatorias.",o:["Verdadero","Falso"],a:0,exp:"Verdadero. Como es tradición, los países anfitriones clasifican directamente. Sus tres plazas son adicionales a los cupos regulares de clasificación.",extra:"Para CONCACAF esto es especialmente ventajoso: los tres anfitriones más los clasificados en eliminatorias suman hasta 6 cupos totales para la región."},

  // ── EL AZTECA: EL ESTADIO HISTÓRICO ──────────────────────────
  {t:"m",q:"¿En cuántas Copas del Mundo habrá albergado partidos el Estadio Azteca si se cuenta el 2026?",o:["2 Mundiales","3 Mundiales","4 Mundiales","5 Mundiales"],a:1,exp:"El Estadio Azteca albergó el Mundial de 1970, el de 1986 y ahora el de 2026. Será el único estadio en la historia en haber recibido partidos de tres Copas del Mundo diferentes.",extra:"En 1970 fue sede de la final (Brasil 4-1 Italia). En 1986 fue sede de la final (Argentina 3-2 Alemania) y del histórico 'gol del siglo' de Maradona."},
  {t:"m",q:"¿Qué partido histórico de Diego Maradona se jugó en el Estadio Azteca en el Mundial 1986?",o:["La final contra Alemania","El gol del siglo y la Mano de Dios contra Inglaterra","El hattrick a Bélgica","El debut de Argentina"],a:1,exp:"El 22 de junio de 1986 en el Azteca, Maradona marcó dos de los goles más famosos de la historia: la 'Mano de Dios' y el 'Gol del Siglo' ante Inglaterra.",extra:"El Azteca fue así testigo de ambos extremos del genio maradoniano: la trampa y la obra de arte, en el mismo partido. Argentina ganó 2-1."},

  // ── HISTORIA GENERAL DEL MUNDIAL ─────────────────────────────
  {t:"m",q:"¿En qué año se disputó el primer Mundial de fútbol y qué país fue sede?",o:["1926 en Italia","1928 en Argentina","1930 en Uruguay","1932 en Brasil"],a:2,exp:"La primera Copa Mundial de la FIFA se jugó en Uruguay en 1930, con 13 selecciones participantes. Uruguay ganó el torneo como local.",extra:"Uruguay fue elegida sede en parte como homenaje a sus dos títulos olímpicos (1924 y 1928). El viaje en barco de las selecciones europeas duraba semanas."},
  {t:"m",q:"¿Cuántas selecciones participaron en el primer Mundial de 1930 en Uruguay?",o:["8 selecciones","13 selecciones","16 selecciones","24 selecciones"],a:1,exp:"Solo 13 selecciones participaron en Uruguay 1930: 9 de América (incluyendo el anfitrión) y solo 4 europeas que aceptaron el largo viaje en barco.",extra:"La mayoría de los equipos europeos se negó a participar por el costo y duración del viaje. Bélgica, Francia, Yugoslavia y Rumanía fueron las cuatro que viajaron."},
  {t:"m",q:"¿Qué país es el único que ha participado en TODOS los Mundiales de la historia desde 1930?",o:["Alemania","Argentina","Italia","Brasil"],a:3,exp:"Brasil es el único país que ha estado presente en los 22 Mundiales disputados hasta 2022, sin haberse perdido ninguna edición.",extra:"Brasil también es el país con más títulos mundiales (5). Su clasificación automática en todas las ediciones refleja la fortaleza histórica del fútbol brasileño."},
  {t:"m",q:"¿Cuántos títulos mundiales tiene Brasil, el país más ganador?",o:["3 títulos","4 títulos","5 títulos","6 títulos"],a:2,exp:"Brasil ganó 5 Copas del Mundo: 1958 (Suecia), 1962 (Chile), 1970 (México), 1994 (USA) y 2002 (Japón/Corea del Sur).",extra:"En 1970, al ganar por tercera vez, Brasil se quedó con la Copa Jules Rimet de forma permanente. El nuevo trofeo se estrenó en 1974."},
  {t:"m",q:"¿Cuántos títulos mundiales tienen Alemania e Italia respectivamente?",o:["3 y 3","4 y 4","4 y 3","3 y 4"],a:1,exp:"Tanto Alemania como Italia tienen 4 títulos mundiales cada una. Alemania ganó en 1954, 1974, 1990 y 2014; Italia en 1934, 1938, 1982 y 2006.",extra:"Ambas naciones son las únicas junto a Brasil y Argentina en haber ganado el Mundial más de dos veces. Francia y Uruguay tienen 2 cada una."},
  {t:"m",q:"¿Cuántos títulos mundiales tiene Argentina?",o:["1 título","2 títulos","3 títulos","4 títulos"],a:2,exp:"Argentina ganó la Copa del Mundo en 1978 (local), 1986 (México) y 2022 (Qatar), siendo el tercer país con más títulos.",extra:"El título de 2022 cerró el ciclo de Lionel Messi, quien finalmente obtuvo el único título que le faltaba en su carrera, superando 36 años de espera."},
  {t:"m",q:"¿Cuál es el máximo goleador en la historia de los Mundiales con 16 tantos?",o:["Ronaldo Nazário","Pelé","Just Fontaine","Miroslav Klose"],a:3,exp:"Miroslav Klose (Alemania) es el máximo goleador de la historia mundialista con 16 goles repartidos en 4 torneos: 2002 (5), 2006 (5), 2010 (4) y 2014 (2).",extra:"Klose superó el récord de Ronaldo Nazário (15 goles) al marcar en la semifinal ante Brasil en 2014. Su récord podría ser amenazado por Messi o Mbappé."},
  {t:"m",q:"¿Cuál es el gol más rápido en la historia de los Mundiales?",o:["Gol de Pelé en 1958 (45s)","Gol de Hakan Şükür en 2002 (~11s)","Gol de Maradona en 1986 (30s)","Gol de Geoff Hurst en 1966 (1 min)"],a:1,exp:"Hakan Şükür (Turquía) marcó el gol más rápido de la historia del Mundial a los 10.89 segundos del comienzo del partido ante Corea del Sur en el tercer puesto de 2002.",extra:"Turquía terminó ganando 3-2 ese partido y se quedó con el tercer puesto. El gol de Şükür es uno de los récords más difíciles de batir del fútbol mundial."},
  {t:"m",q:"¿Cuál es la mayor goleada de la historia de los Mundiales?",o:["Brasil 8-3 Polonia (1938)","Suecia 8-0 Cuba (1938)","Hungría 10-1 El Salvador (1982)","Alemania 8-0 Arabia Saudita (2002)"],a:2,exp:"Hungría 10 - El Salvador 1 en el Mundial de España 1982 es la mayor goleada de la historia. Laszlo Kiss fue el gran protagonista con un hat-trick en solo 7 minutos.",extra:"El Equipo de El Salvador estaba en su único Mundial. A pesar de la goleada, los jugadores salvadoreños son recordados por su coraje al terminar el partido."},
  {t:"m",q:"¿Qué jugador tiene el récord de más partidos disputados en Mundiales con 25 apariciones?",o:["Paolo Maldini","Cafu","Lothar Matthäus","Diego Maradona"],a:2,exp:"Lothar Matthäus (Alemania) jugó 25 partidos en Mundiales a lo largo de 5 ediciones (1982, 1986, 1990, 1994 y 1998), un récord de longevidad.",extra:"Matthäus participó en 5 Mundiales diferentes, ganando en 1990. Su último torneo fue a los 37 años. Es además uno de los mejores centrocampistas de la historia."},
  {t:"m",q:"¿Cuál es el jugador más joven en marcar un gol en la historia de los Mundiales?",o:["Cesc Fàbregas","Michael Owen","Kylian Mbappé","Pelé"],a:3,exp:"Pelé marcó su primer gol mundialista el 19 de junio de 1958 ante Gales, a los 17 años y 239 días, convirtiéndose en el goleador más joven de la historia.",extra:"Ese gol de Pelé fue el único del partido (Brasil 1-0 Gales) y lo catapultó al estrellato mundial. Brasil ganó ese torneo con Pelé como figura revelación."},
  {t:"m",q:"¿Cuántos Mundiales ganó Pelé a lo largo de su carrera?",o:["1 Mundial","2 Mundiales","3 Mundiales","4 Mundiales"],a:2,exp:"Pelé ganó 3 Copas del Mundo con Brasil: 1958 (Suecia, con 17 años), 1962 (Chile, lesionado tras el primer partido) y 1970 (México, en su mejor nivel).",extra:"El de 1970 se considera el de su mejor actuación. El equipo de 1970 con Pelé, Rivelino, Jairzinho y Tostao es considerado uno de los mejores de la historia."},
  {t:"f",q:"Brasil es el único país que ganó el Mundial en su propio territorio como local.",o:["Verdadero","Falso"],a:1,exp:"Falso. Uruguay (1930), Italia (1934), Inglaterra (1966), Alemania (1974), Argentina (1978) y Francia (1998) ganaron el Mundial siendo locales. Brasil NUNCA ganó siendo sede.",extra:"Brasil perdió ante Uruguay 2-1 en 1950 (Maracanazo) siendo local y fue eliminado por Alemania 7-1 en 2014. El título como local se le sigue escapando."},

  // ── RECORDS Y CURIOSIDADES HISTÓRICAS ────────────────────────
  {t:"m",q:"¿Cómo se llama el partido de 1950 donde Uruguay venció 2-1 a Brasil en el Maracaná y se coronó campeón del mundo?",o:["El Uruguayazo","El Maracanazo","El Gol Fantasma","La Tragedia de Río"],a:1,exp:"El 'Maracanazo' fue el partido del 16 de julio de 1950 en el Estadio Maracaná donde Uruguay venció a Brasil y fue campeón, ante más de 170.000 hinchas locales.",extra:"Alcides Ghiggia marcó el gol decisivo a los 79 minutos. Se cuenta que el Maracaná quedó en silencio absoluto. Ghiggia dijo: 'Solo tres personas silenciaron el Maracaná: Frank Sinatra, el Papa y yo'."},
  {t:"m",q:"¿Cómo se llama la aplastante derrota de Brasil 1-7 ante Alemania en las semifinales del Mundial 2014?",o:["El Brasileñazo","El Mineirazo","La Catástrofe de Belo Horizonte","El Siete de la Vergüenza"],a:1,exp:"El 'Mineirazo' fue el 8 de julio de 2014 en el Estadio Mineirão: Alemania goleó 7-1 a Brasil en la semifinal, la mayor derrota en la historia reciente del fútbol brasileño.",extra:"4 de los 7 goles de Alemania cayeron en solo 6 minutos (entre los minutos 23 y 29). Miroslav Klose marcó el gol 16 de su carrera mundialista ese partido."},
  {t:"m",q:"¿Qué Argentina vs Inglaterra protagonizó la 'Mano de Dios' y el 'Gol del Siglo' de Diego Maradona?",o:["Mundial España 1982","Mundial México 1986, cuartos de final","Mundial Italia 1990","Copa América 1987"],a:1,exp:"Fue el 22 de junio de 1986 en cuartos de final del Mundial de México. Maradona primero anotó con la mano y luego dribló a medio equipo inglés en el mismo partido.",extra:"Argentina ganó 2-1. El partido tenía contexto político por la Guerra de las Malvinas (1982). Maradona reconoció la Mano de Dios años después, aunque en el momento lo negó."},
  {t:"m",q:"¿Quién fue el célebre relator que describió el gol del siglo de Maradona con la frase 'Barrilete cósmico, ¿de qué planeta viniste?'?",o:["José María Múñoz","Víctor Hugo Morales","Marcelo Araujo","Alejandro Fantino"],a:1,exp:"Víctor Hugo Morales, relator uruguayo, hizo la icónica narración del gol del siglo de Maradona ante Inglaterra en el Mundial 1986, terminando con '¡Barrilete cósmico!',",extra:"La narración de Víctor Hugo Morales es considerada una de las más emotivas de la historia del deporte. El texto completo es estudiado en escuelas de periodismo deportivo."},
  {t:"m",q:"¿En qué año se usó el VAR (árbitro asistente de video) por primera vez en la Copa del Mundo?",o:["Brasil 2014","Rusia 2016","Rusia 2018","Qatar 2022"],a:2,exp:"El VAR fue implementado por primera vez en un Mundial en Rusia 2018, cambiando la forma de arbitrar y generando debates sobre si mejora o ralentiza el fútbol.",extra:"Francia vs Australia fue el primer partido donde el VAR cambió un resultado en un Mundial. Antoine Griezmann convirtió el penal revisado, Francia ganó 2-1."},
  {t:"m",q:"¿En qué Mundial Qatar 2022 un hecho inédito ocurrió con el equipo anfitrión?",o:["El anfitrión ganó el torneo","El anfitrión llegó a la final","Qatar fue el primer anfitrión eliminado en la fase de grupos","El anfitrión rechazó el trofeo"],a:2,exp:"Qatar 2022 fue el primer caso en la historia donde el equipo anfitrión fue eliminado en la fase de grupos, sin ganar ningún partido.",extra:"Qatar perdió ante Ecuador (0-2), Senegal (1-3) y empató con Países Bajos (1-1) en reclasificación. Fue un debut mundialista histórico pero muy duro para la selección catarí."},
  {t:"m",q:"¿Qué jugador ganó el Balón de Oro al mejor jugador del Mundial de Qatar 2022?",o:["Kylian Mbappé","Luka Modrić","Lionel Messi","Julián Álvarez"],a:2,exp:"Lionel Messi ganó el Balón de Oro de Qatar 2022, su segundo (ya lo había ganado en Argentina 2014). Fue el premio que coronó su desempeño en la final ante Francia.",extra:"Messi marcó 7 goles y dio 3 asistencias en el torneo. La final ante Francia (3-3 en el tiempo extra) se considera una de las mejores de la historia mundialista."},
  {t:"m",q:"¿Quién fue el máximo goleador (Bota de Oro) del Mundial de Qatar 2022 con 8 goles?",o:["Lionel Messi","Olivier Giroud","Kylian Mbappé","Julián Álvarez"],a:2,exp:"Kylian Mbappé terminó como máximo goleador de Qatar 2022 con 8 goles, incluyendo un hat-trick en la final ante Argentina. A pesar de eso, Francia perdió por penales.",extra:"El hat-trick de Mbappé en una final mundialista es solo el segundo de la historia (el primero fue de Geoff Hurst para Inglaterra en 1966 contra Alemania Occidental)."},
  {t:"m",q:"¿Cómo terminó la final del Mundial de Qatar 2022 entre Argentina y Francia?",o:["Argentina ganó 3-1","Francia ganó 4-3","Empate 3-3, Argentina ganó 4-2 en penales","Empate 2-2, Argentina ganó por penales"],a:2,exp:"La final terminó 3-3 en el tiempo extra (2-2 en el tiempo reglamentario). Argentina ganó 4-2 en la tanda de penales para consagrarse campeón del mundo.",extra:"Fue la primera final de la historia en terminar 3-3. Mbappé marcó un hat-trick para Francia pero no alcanzó. Emiliano Martínez fue clave tapando un penal."},
  {t:"m",q:"¿Cuál fue el primer Mundial que el histórico Lionel Messi ganó?",o:["Alemania 2006","Sudáfrica 2010","Brasil 2014","Qatar 2022"],a:3,exp:"Qatar 2022 fue el primer y único Mundial que Messi ganó. Luego de 4 torneos anteriores (2006, 2010, 2014 donde fue subcampeón, y 2018), finalmente levantó la copa.",extra:"En 2014, Messi fue finalista y ganó el Balón de Oro del torneo pese a que Argentina perdió la final 0-1 ante Alemania. En 2022 completó su legado."},

  // ── MUNDIALES LEGENDARIOS ─────────────────────────────────────
  {t:"m",q:"¿Qué partido dramático protagonizó Roberto Baggio en la final del Mundial de USA 1994?",o:["Marcó el gol del título en el último minuto","Falló el penal definitivo que le dio el título a Brasil","Fue expulsado en la prórroga","Lesionó al portero rival"],a:1,exp:"Roberto Baggio falló el último penal de la tanda ante Brasil en la final de USA 1994. La imagen del astro italiano de cabeza baja se convirtió en símbolo de la derrota.",extra:"Brasil ganó 3-2 en los penales tras un 0-0 de 120 minutos. Fue la primera final sin goles en el tiempo reglamentario de la historia de los Mundiales."},
  {t:"f",q:"La final del Mundial de USA 1994 entre Brasil e Italia terminó sin goles en los 90 minutos y la prórroga, siendo la primera final con penales.",o:["Verdadero","Falso"],a:0,exp:"Verdadero. El 0-0 de la final de 1994 fue la primera vez que una final mundialista llegaba a los penales. Brasil ganó 3-2 en la tanda.",extra:"Baggio, Massaro, Baresi y otros italianos fallaron penales. Fue uno de los partidos más tensos de la historia del fútbol. Brasil obtuvo así su cuarto título."},
  {t:"m",q:"¿En qué Mundial de 1998 Zinedine Zidane fue la gran figura con dos goles de cabeza en la final?",o:["USA 1994","Francia 1998","Corea-Japón 2002","Alemania 2006"],a:1,exp:"En la final de Francia 1998 ante Brasil, Zidane marcó dos goles de cabeza en la primera parte. Francia ganó 3-0 y se consagró campeón del mundo por primera vez.",extra:"El rendimiento de Ronaldo Nazário en esa final fue sospechoso (convulsionó horas antes). Brasil presentó a Ronaldo pero él tuvo un mal partido. Zidane fue la figura del torneo."},
  {t:"m",q:"¿En qué año ganó Francia su segunda Copa del Mundo y ante quién?",o:["2002 vs Brasil","2010 vs España","2014 vs Alemania","2018 vs Croacia"],a:3,exp:"Francia ganó su segundo título mundial en Rusia 2018, venciendo a Croacia 4-2 en la final. Kylian Mbappé marcó el gol que lo hizo el segundo adolescente en marcar en una final.",extra:"El primero en marcar en una final siendo adolescente fue Pelé en 1958. Mbappé tenía 19 años en Rusia 2018."},
  {t:"m",q:"¿Qué selección africana llegó por primera vez a las semifinales de un Mundial en Qatar 2022?",o:["Ghana","Nigeria","Senegal","Marruecos"],a:3,exp:"Marruecos se convirtió en el primer país africano en llegar a las semifinales de un Mundial, eliminando a España, Portugal y casi a Francia.",extra:"Los marroquíes eliminaron a España en octavos y a Portugal en cuartos. En semifinales cayeron ante Francia 0-2 pero el logro fue histórico para el fútbol africano."},
  {t:"m",q:"¿Qué primer equipo africano llegó a los cuartos de final de un Mundial, en Italia 1990?",o:["Nigeria","Costa de Marfil","Egipto","Camerún"],a:3,exp:"Camerún en Italia 1990 fue el primer equipo africano en alcanzar los cuartos de final de un Mundial, bajo la conducción del legendario Roger Milla.",extra:"Roger Milla tenía 38 años y salía al campo bailando junto al banderín del córner tras cada gol. Sus celebraciones se convirtieron en símbolo del Mundial de 1990."},
  {t:"m",q:"¿Cuál fue la primera selección asiática en llegar a las semifinales de un Mundial (2002)?",o:["Japón","Arabia Saudita","Iran","Corea del Sur"],a:3,exp:"Corea del Sur llegó a las semifinales del Mundial 2002 (co-organizado con Japón), eliminando a España e Italia en el camino, con gran nivel futbolístico y apoyo local.",extra:"La hazaña de Corea generó controversia por algunas decisiones arbitrales cuestionadas. Aun así, fue el mayor logro en la historia del fútbol de la región asiática."},

  // ── RÉCORDS Y DATOS DE JUGADORES ─────────────────────────────
  {t:"m",q:"¿Cuántos goles marcó Ronaldo Nazário (El Fenômeno) en el Mundial de Corea-Japón 2002?",o:["6 goles","7 goles","8 goles","9 goles"],a:2,exp:"Ronaldo Nazário marcó 8 goles en el Mundial 2002, siendo el máximo goleador del torneo. Brasil ganó el título venciendo a Alemania 2-0 en la final.",extra:"Ronaldo había tenido una misteriosa convulsión antes de la final de 1998 y fue subcampeón. En 2002 se redimió siendo la figura del torneo. Sus dos goles ante Alemania fueron épicos."},
  {t:"m",q:"¿Cuántos Mundiales jugó Diego Maradona como futbolista?",o:["2 Mundiales","3 Mundiales","4 Mundiales","5 Mundiales"],a:2,exp:"Maradona jugó 4 Mundiales como jugador: Argentina 1978 (fue al plantel pero no jugó), España 1982, México 1986 (campeón y mejor jugador) e Italia 1990.",extra:"En 1978 fue convocado pero Menotti no lo incluyó en la lista final. Fue una de las grandes controversias del fútbol argentino. Argentina ganó igual pero sin Maradona."},
  {t:"m",q:"¿Cuál fue el último Mundial de Maradona como jugador, donde Argentina llegó a la final?",o:["España 1982","México 1986","Italia 1990","USA 1994"],a:2,exp:"Italia 1990 fue el último Mundial de Maradona como jugador. Argentina llegó a la final pero cayó ante Alemania Occidental 0-1 con un penal polémico al final.",extra:"Maradona fue el capitán y figura de esa Argentina defensiva. En la final lloró en el podio. Fue su última aparición como protagonista en un Mundial."},
  {t:"m",q:"¿Cuántos Mundiales jugó Lionel Messi en total antes de ganar el título en Qatar 2022?",o:["3 Mundiales","4 Mundiales","5 Mundiales","6 Mundiales"],a:1,exp:"Messi jugó 5 Mundiales: Alemania 2006 (18 años), Sudáfrica 2010, Brasil 2014 (subcampeón), Rusia 2018 y Qatar 2022 (campeón).",extra:"En 2014 fue subcampeón y ganó el Balón de Oro del torneo (controversial elección por muchos). El 2022 fue su quinta y probablemente última Copa del Mundo."},

  // ── EL TROFEO Y LA COPA JULES RIMET ─────────────────────────
  {t:"m",q:"¿Cómo se llamaba el trofeo original de la Copa del Mundo que Brasil se quedó definitivamente tras ganarla por tercera vez?",o:["Copa Rimet","Copa Jules Rimet","El Trofeo de Oro","Copa FIFA"],a:1,exp:"La Copa Jules Rimet, llamada así por el presidente de la FIFA que impulsó el torneo, fue ganada definitivamente por Brasil al ganar su tercera Copa en 1970.",extra:"La Copa Jules Rimet era de plata dorada y representaba a Nike alada, la diosa griega de la victoria. Brasil recibió una réplica; el original fue robado en Brasil en 1983 y nunca recuperado."},
  {t:"f",q:"La Copa Jules Rimet original fue robada en Brasil en 1983 y nunca recuperada, probablemente siendo fundida.",o:["Verdadero","Falso"],a:0,exp:"Verdadero. La Copa Jules Rimet fue robada en 1983 de la sede de la Confederación Brasileña de Fútbol. Nunca se recuperó y se cree que fue fundida para vender el oro.",extra:"Paradójicamente, el trofeo ya había sido robado anteriormente en Inglaterra en 1966 (cuatro meses antes del Mundial) y fue encontrado por un perro llamado Pickles."},
  {t:"m",q:"¿De qué material está hecho el actual trofeo de la Copa Mundial de la FIFA, introducido en 1974?",o:["Plata y bronce","Oro macizo de 18 quilates con base de malaquita","Acero inoxidable dorado","Platino y cristal"],a:1,exp:"El trofeo actual, diseñado por el escultor italiano Silvio Gazzaniga, es de oro macizo de 18 quilates y pesa 6,1 kg. La base es de malaquita (piedra verde semipreciosa).",extra:"El diseño representa a dos figuras humanas sosteniendo el globo terráqueo. Solo los capitanes y jefes de delegación de los equipos que ganaron pueden tocarlo."},
  {t:"m",q:"¿En qué año se introdujo el actual trofeo de la Copa Mundial, usado por primera vez en Alemania 1974?",o:["1970","1974","1978","1982"],a:1,exp:"El nuevo trofeo de la FIFA debutó en el Mundial de Alemania Occidental 1974, donde la selección local lo levantó por primera vez. Johann Cruyff llegó a la final con Países Bajos pero no lo ganó.",extra:"El trofeo fue diseñado por el escultor Silvio Gazzaniga y seleccionado entre 53 propuestas de 7 países. Permanece sin cambios desde entonces."},

  // ── FORMATO HISTÓRICO Y EVOLUCIÓN ────────────────────────────
  {t:"m",q:"¿En qué año el Mundial pasó de 16 a 24 equipos por primera vez?",o:["1970","1978","1982","1986"],a:2,exp:"El Mundial de España 1982 fue el primero con 24 equipos, aumentando desde los 16 que participaron en todos los torneos desde 1954 hasta 1978.",extra:"Con 24 equipos se añadieron nuevos cupos para África, Asia y CONCACAF, ampliando la representación global del torneo."},
  {t:"m",q:"¿En qué año el Mundial pasó de 24 a 32 equipos?",o:["1990","1994","1998","2002"],a:2,exp:"El Mundial de Francia 1998 fue el primero con 32 equipos, formato que rigió hasta el Mundial de Qatar 2022, siendo el último de 32 selecciones.",extra:"Con 32 equipos, África pasó de 3 a 5 cupos y Asia de 2 a 4. El nuevo formato incluía 8 grupos de 4 equipos con los 2 primeros clasificados."},
  {t:"m",q:"¿Cuándo se usaron por primera vez los penales como desempate en un partido de Mundial?",o:["México 1970","Argentina 1978","España 1982","México 1986"],a:2,exp:"Los penales se usaron por primera vez en un Mundial en España 1982: Alemania Occidental venció a Francia 5-4 en penales en la semifinal, tras empatar 3-3 en la prórroga.",extra:"Esa semifinal fue un partido épico con remontadas y goles espectaculares. Los penales eran un recurso nuevo y dramático; Schumacher y su falta a Battiston marcaron el partido."},
  {t:"m",q:"¿En qué edición del Mundial se introdujeron los tarjetas amarillas y rojas como sistema de sanciones?",o:["Chile 1962","Inglaterra 1966","México 1970","Alemania 1974"],a:2,exp:"Las tarjetas amarillas y rojas se usaron por primera vez en el Mundial de México 1970, idea del árbitro inglés Ken Aston inspirada en los semáforos de tráfico.",extra:"Ken Aston tuvo la idea manejando su auto en Londres al ver un semáforo: amarillo = atención/amonestación, rojo = parar/expulsión. El sistema se adoptó inmediatamente."},
  {t:"f",q:"La regla del gol de oro (golden goal) fue usada en algunos Mundiales donde el primer gol en prórroga determinaba el ganador.",o:["Verdadero","Falso"],a:0,exp:"Verdadero. El 'gol de oro' (o sudden death) se usó en los Mundiales de 1998 y 2002 antes de ser eliminado. El primer gol en prórroga terminaba el partido.",extra:"Francia ganó la semifinal de 1998 ante Paraguay con un gol de oro de Blanc. En 2006 y posteriores se volvió al formato tradicional de dos tiempos de prórroga completos."},

  // ── PAÍSES BAJOS: LOS ETERNOS SUBCAMPEONES ───────────────────
  {t:"m",q:"¿Cuántas veces fue finalista Países Bajos (Holanda) sin ganar nunca el Mundial?",o:["2 veces","3 veces","4 veces","5 veces"],a:1,exp:"Países Bajos perdió 3 finales: 1974 (vs Alemania Occidental), 1978 (vs Argentina) y 2010 (vs España). Es el país con más finales sin ganar.",extra:"El equipo de 1974 con Cruyff y el 'Total Football' es considerado uno de los mejores en nunca ganar un Mundial. Perdieron la final 2-1 ante Alemania pese a dominar."},
  {t:"m",q:"¿Cómo se llamaba el revolucionario sistema táctico con el que Países Bajos deslumbró en los 70?",o:["Catenaccio","Tiki-taka","Total Football (Fútbol Total)","Gegenpressing"],a:2,exp:"El 'Total Football' (Totaalvoetbal) fue el sistema donde todos los jugadores podían ocupar cualquier posición, creando confusión en el rival. Johan Cruyff era su máximo exponente.",extra:"El Total Football fue desarrollado en el Ajax de los 70 y llevado a la selección holandesa. Revolucionó el fútbol y sus principios siguen vigentes en equipos modernos como el Barcelona."},

  // ── CURIOSIDADES ÚNICAS ───────────────────────────────────────
  {t:"m",q:"¿Cuántos espectadores se calcula que presenciaron el partido Uruguay vs Brasil en el Maracaná en 1950?",o:["80.000 personas","120.000 personas","Entre 170.000 y 200.000 personas","300.000 personas"],a:2,exp:"Se calcula que entre 170.000 y 200.000 personas estuvieron en el Maracaná para el partido definitorio de 1950. Es el partido con más espectadores presentes en la historia del fútbol.",extra:"El Estadio Maracaná tenía capacidad ilimitada en ese entonces (se paraba). No había registros exactos. La derrota local ante Uruguay dejó un silencio absoluto en el estadio."},
  {t:"m",q:"¿Qué portero italiano tiene el récord de más minutos invicto en Mundiales con 517 minutos?",o:["Gianluigi Buffon","Dino Zoff","Walter Zenga","Sebastiano Rossi"],a:2,exp:"Walter Zenga mantuvo su arco en cero durante 517 minutos en el Mundial de Italia 1990, un récord que aún permanece como el mayor período sin encajar en Mundiales.",extra:"Zenga encadenó 5 partidos completos sin recibir gol. El récord se terminó en el partido ante Argentina, cuando Claudio Caniggia marcó de cabeza en semifinales."},
  {t:"m",q:"¿Quién fue el primer jugador en ser expulsado en una final de la Copa del Mundo?",o:["Zinedine Zidane (2006)","Marco Mateus (2010)","Carlos Monzón (1990)","Pedro Monzón (1990)"],a:3,exp:"Pedro Monzón (Argentina) fue expulsado en la final de Italia 1990 ante Alemania, siendo el primer jugador en recibir una tarjeta roja en una final mundialista.",extra:"En esa misma final, su compatriota Gustavo Dezotti también fue expulsado. Argentina terminó con 9 jugadores y perdió 0-1 con un penal polémico al final."},
  {t:"m",q:"¿Qué famosa cabezazo de Zinedine Zidane ocurrió en la final del Mundial 2006?",o:["Marcó el gol del título","Le dio un cabezazo a Materazzi en el pecho y fue expulsado","Falló el penal definitivo","Perdió el balón que llevó al gol de Italia"],a:1,exp:"En la prórroga de la final de Alemania 2006, Zidane le dio un cabezazo a Marco Materazzi en el pecho y fue expulsado. Francia perdió los penales ante Italia 3-5.",extra:"Fue el último partido de Zidane como profesional. Materazzi supuestamente insultó a la madre o hermana de Zidane. El incidente sigue siendo uno de los más debatidos de la historia."},
  {t:"m",q:"¿Qué extraña historia rodeó a Ronaldo Nazário antes de la final de 1998 ante Francia?",o:["Fue amenazado de muerte","Sufrió una convulsión misteriosa horas antes y lo pusieron en la lista a último momento","Tuvo una lesión que lo dejó cojo","Se peleó con el DT"],a:1,exp:"Horas antes de la final, Ronaldo sufrió una convulsión misteriosa. Fue borrado de la lista inicial y luego reincorporado. Jugó pero tuvo su peor actuación; Brasil perdió 0-3.",extra:"La causa de la convulsión nunca se aclaró públicamente. Generó teorías sobre presión del patrocinador Nike, problemas médicos o nerviosos. Fue uno de los mayores misterios del fútbol."},

  // ── MUNDIALES: ANFITRIONES Y SEDES ───────────────────────────
  {t:"m",q:"¿En qué año organizó Estados Unidos su último Mundial antes del 2026?",o:["1990","1994","2002","2010"],a:1,exp:"Estados Unidos organizó el Mundial de 1994, que fue un éxito de asistencia y marketing pese a que el fútbol no era el deporte principal del país.",extra:"USA 1994 estableció el récord de promedio de asistencia por partido que duró décadas. El torneo fue clave para el crecimiento posterior de la MLS y el fútbol en Norteamérica."},
  {t:"m",q:"¿Qué países co-organizaron el Mundial de 2002, siendo la primera vez que dos naciones compartían la sede?",o:["China y Japón","Japón y Corea del Sur","Corea del Sur y Taiwán","China y Corea del Sur"],a:1,exp:"Japón y Corea del Sur fueron los primeros co-anfitriones en la historia del Mundial en 2002. El torneo tuvo 20 estadios entre los dos países.",extra:"La co-organización fue controversial al principio: ambos países querían ser los únicos anfitriones. Terminó siendo exitoso y abrió la puerta para la co-organización de 2026."},
  {t:"m",q:"¿Cuántos Mundiales organizó México antes del 2026?",o:["1 Mundial","2 Mundiales","3 Mundiales","4 Mundiales"],a:1,exp:"México organizó dos Mundiales: 1970 (donde Brasil ganó su 3er título con Pelé) y 1986 (donde Argentina con Maradona ganó su 2do título). Ahora será parte del 2026.",extra:"En 1986, México asumió la organización de urgencia reemplazando a Colombia, que renunció por problemas económicos. Tuvo solo 3 años para organizar el torneo."},
  {t:"f",q:"El Mundial 2026 será la primera vez que Canadá organiza una Copa del Mundo masculina.",o:["Verdadero","Falso"],a:0,exp:"Verdadero. Canadá nunca organizó un Mundial masculino. Sin embargo, sí organizó el Mundial Femenino en 2015 y la Copa Oro de la CONCACAF en múltiples ocasiones.",extra:"Con el 2026, Canadá también aprovechó para fortalecer su programa de fútbol. La clasificación de Canadá para el Mundial de Qatar 2022 fue el primer paso de ese crecimiento."},
  {t:"m",q:"¿Cuántas ciudades estadounidenses serán sede del Mundial 2026?",o:["8 ciudades","9 ciudades","11 ciudades","13 ciudades"],a:2,exp:"Estados Unidos aporta 11 ciudades sede al Mundial 2026: Nueva York/Nueva Jersey, Los Ángeles (dos estadios), Dallas, Miami, San Francisco, Seattle, Kansas City, Boston y Filadelfia.",extra:"El MetLife Stadium (NY/NJ) albergará la final. El Rose Bowl (LA) fue también sede del Mundial 1994. SoFi Stadium es uno de los recintos más modernos del mundo."},

  // ── DATOS DE CLASIFICACIÓN 2026 ───────────────────────────────
  {t:"m",q:"¿Cuántos cupos le corresponden a la UEFA (Europa) en el Mundial 2026?",o:["13 cupos","14 cupos","16 cupos","18 cupos"],a:2,exp:"Europa tiene 16 cupos directos en el Mundial 2026 (más plazas de repechaje), el mayor número de cualquier confederación, reflejando el nivel del fútbol europeo.",extra:"El aumento de cupos fue proporcional al total de 48 equipos. Europa pasó de 13 plazas (en el formato de 32) a 16, una ganancia de 3 cupos directos."},
  {t:"m",q:"¿Cuántos cupos le corresponden a la CONMEBOL (Sudamérica) en el Mundial 2026?",o:["4 cupos","5 cupos","6 cupos + repechaje","8 cupos"],a:2,exp:"Sudamérica tiene 6 cupos directos más uno adicional en el repechaje intercontinental para el Mundial 2026. Antes tenía 4,5 plazas.",extra:"El aumento de CONMEBOL fue muy celebrado en la región. Con 10 selecciones peleando por 6 plazas, las eliminatorias sudamericanas siguen siendo muy competitivas."},
  {t:"m",q:"¿Cuántos cupos tiene la CAF (África) en el Mundial 2026?",o:["6 cupos","8 cupos","9 cupos + repechaje","10 cupos"],a:2,exp:"África tiene 9 cupos directos más uno en el repechaje para el Mundial 2026. En el formato de 32 equipos tenía solo 5 plazas. El aumento fue muy significativo.",extra:"El crecimiento del fútbol africano justifica el aumento. Con resultados como Marruecos en Qatar 2022 (semifinalista), África demuestra cada vez más su nivel competitivo."},

  // ── CURIOSIDADES Y DATOS VARIADOS ────────────────────────────
  {t:"m",q:"¿Cuántos entrenadores argentinos ganaron la Copa del Mundo con Argentina?",o:["1 entrenador","2 entrenadores","3 entrenadores","4 entrenadores"],a:1,exp:"Dos entrenadores argentinos ganaron el Mundial: César Luis Menotti en 1978 (Argentina local) y Carlos Bilardo en 1986 (México). Lionel Scaloni sumó el tercero en 2022.",extra:"Menotti era defensor del fútbol ofensivo y bello; Bilardo del pragmático y efectivo. Sus estilos opuestos generaron un debate que dividió el fútbol argentino por décadas."},
  {t:"m",q:"¿Cómo se llama el trofeo al mejor portero de cada Copa del Mundo?",o:["Escudo de Oro","Guante de Oro","Casco de Platino","Barrera de Oro"],a:1,exp:"El Guante de Oro (Golden Glove) es el trofeo al mejor arquero del torneo. En Qatar 2022 lo ganó Emiliano Martínez (Argentina), figura clave en las semifinales y final.",extra:"El Guante de Oro se llama 'Yashin Award' en honor al legendario portero soviético Lev Yashin, considerado el mejor guardameta de la historia."},
  {t:"m",q:"¿Qué selección europea llegó a la final del Mundial 2022 pese a no clasificar directamente para el mundial anterior (2018)?",o:["Bélgica","Países Bajos","Croacia","Francia"],a:2,exp:"Croacia fue finalista en Qatar 2022 (perdió la final vs Argentina en 2018) y en 2018 también fue finalista. Croacia no tiene tradición de grandes jugadores pero sí una cultura de juego colectivo.",extra:"Luka Modrić es el cerebro de la Croacia contemporánea. En 2018 ganó el Balón de Oro del torneo a pesar de que Croacia perdió la final. En 2022 Croacia llegó al tercer puesto."},
  {t:"m",q:"¿Cuál es el partido de fútbol con más espectadores presentes en la historia?",o:["Brasil vs Argentina 1990","Brasil vs Uruguay 1950 (Maracaná)","Inglaterra vs Alemania 1966","Argentina vs Alemania 1978"],a:1,exp:"El partido Uruguay vs Brasil del 16 de julio de 1950 en el Maracaná se estima que fue presenciado por entre 170.000 y 200.000 personas, el mayor número en la historia del fútbol.",extra:"El estadio no tenía aforo oficial en esa época. Los datos varían según la fuente, pero incluso la cifra más conservadora lo convierte en el partido con más espectadores de la historia."},
  {t:"m",q:"¿Cuántos Mundiales ganó Uruguay, convirtiéndolo en uno de los países más exitosos de la historia temprana del torneo?",o:["1 Mundial","2 Mundiales","3 Mundiales","4 Mundiales"],a:1,exp:"Uruguay ganó 2 Copas del Mundo: 1930 (como local y primer campeón mundial) y 1950 (el histórico 'Maracanazo' en Brasil). Sus 2 títulos son notables para un país pequeño.",extra:"Uruguay también ganó los Juegos Olímpicos de 1924 y 1928. Para su tamaño (3,5 millones de habitantes), su palmarés internacional es único en la historia del deporte."},
  {t:"f",q:"El primer Mundial de 1930 se disputó completamente en un solo estadio en Uruguay.",o:["Verdadero","Falso"],a:1,exp:"Falso. El Mundial de 1930 usó 3 estadios en Montevideo: el Estadio Centenario (construido para el evento), el Estadio Gran Parque Central y el Estadio Pocitos.",extra:"El Estadio Centenario fue inaugurado durante el torneo y fue la sede de la final Uruguay vs Argentina (4-2). El torneo se jugó íntegramente en Montevideo, solo en esa ciudad."},
  {t:"m",q:"¿Qué debut mundialista hizo Kylian Mbappé en Rusia 2018 que solo Pelé había logrado antes?",o:["Ganó la Bota de Oro","Marcó en la final del Mundial siendo menor de 20 años","Metió 4 goles en un solo partido","Fue el jugador más joven en jugar un Mundial"],a:1,exp:"Mbappé se convirtió en 2018 en el segundo jugador menor de 20 años en marcar en una final mundialista, después de Pelé en 1958. Francia ganó esa final 4-2 a Croacia.",extra:"Mbappé tenía 19 años en la final de 2018. Pelé tenía 17 cuando marcó ante Suecia en 1958. Ambos consiguieron el título en la misma oportunidad."},

  // ── MUNDIALES Y CURIOSIDADES FINALES ─────────────────────────
  {t:"m",q:"¿Quién fue el goleador del primer Mundial de 1930, con el récord de 8 goles en un solo torneo?",o:["Guillermo Stábile (Argentina)","Pedro Petrone (Uruguay)","Bert Patenaude (USA)","Héctor Castro (Uruguay)"],a:0,exp:"Guillermo Stábile (Argentina) marcó 8 goles en el Mundial de 1930, siendo el máximo goleador del primer torneo. El récord en una sola edición fue superado después.",extra:"Stábile debutó en el Mundial siendo el reemplazante de un titular. Con 8 goles llevó a Argentina a la final, donde perdieron ante Uruguay 2-4. Es el mayor debut mundialista de la historia."},
  {t:"m",q:"¿Quién marcó el primer hat-trick en la historia de los Mundiales en el torneo de 1930?",o:["Guillermo Stábile","Bert Patenaude (USA)","Pedro Cea (Uruguay)","Wilfried Van Moer"],a:1,exp:"Bert Patenaude (Estados Unidos) anotó el primer hat-trick de la historia mundialista el 17 de julio de 1930 ante Paraguay. USA ganó ese partido 3-0.",extra:"El hat-trick de Patenaude fue reconocido oficialmente por la FIFA recién en 2006 tras revisar los archivos históricos. Antes se atribuía erróneamente a otro jugador."},
  {t:"m",q:"¿Qué selección ha disputado más finales mundialistas perdidas?",o:["Francia","Brasil","Alemania","Argentina"],a:2,exp:"Alemania es el país con más finales perdidas: cayó en 1966 (vs Inglaterra), 1982 (vs Italia), 1986 (vs Argentina) y 2002 (vs Brasil). Tiene 4 finales perdidas.",extra:"Sumando las ganadas (1954, 1974, 1990, 2014), Alemania ha jugado 8 finales en total, más que cualquier otro país. Es la selección más consistente en la historia del torneo."},
  {t:"f",q:"Just Fontaine (Francia) marcó 13 goles en el Mundial de 1958, el récord de goles en un solo torneo que aún se mantiene.",o:["Verdadero","Falso"],a:0,exp:"Verdadero. Just Fontaine marcó 13 goles en el Mundial de Suecia 1958 en solo 6 partidos. Es el récord de goles en una sola edición mundialista que no ha sido igualado.",extra:"Fontaine marcó 4 goles en un solo partido (vs Alemania Occidental por el tercer puesto). Francia terminó 3ra. La carrera de Fontaine terminó prematuramente por lesiones."},
  {t:"m",q:"¿Cuál es el mayor número de goles marcados por una selección en un solo partido de fases finales?",o:["8 goles","10 goles","12 goles","9 goles"],a:1,exp:"Hungría marcó 10 goles ante El Salvador en España 1982 (10-1). Antes, Austria marcó 7 ante Suiza en 1954, pero la goleada húngara es la mayor final de la historia.",extra:"Laszlo Kiss marcó un hat-trick en solo 7 minutos como suplente en ese partido, convirtiéndose en el jugador que marcó más rápido un hat-trick desde el banco."},
  {t:"m",q:"¿Qué jugador fue el último en marcar un hat-trick en una final mundialista, hazaña que realizó en 1966?",o:["Pelé","Just Fontaine","Geoff Hurst","Eusébio"],a:2,exp:"Geoff Hurst marcó el único hat-trick de una final mundialista el 30 de julio de 1966, cuando Inglaterra venció a Alemania Occidental 4-2 en el Estadio Wembley.",extra:"Su tercer gol es el más controvertido: el balón pegó en el travesaño y rebotó dentro (o fuera) de la línea. El árbitro lo dio como gol tras consultar con el juez de línea."},
  {t:"m",q:"¿Cuántos cupos para el Mundial 2026 tiene la AFC (Confederación Asiática)?",o:["6 cupos","8 cupos + repechaje","10 cupos","5 cupos"],a:1,exp:"Asia tiene 8 cupos directos más uno adicional en el repechaje intercontinental para el Mundial 2026. En el formato de 32 equipos tenía solo 4,5 plazas.",extra:"El aumento de cupos para Asia refleja el crecimiento del fútbol en la región. Japón, Corea del Sur, Arabia Saudita y otros países compiten regularmente a buen nivel."},
  {t:"m",q:"¿Qué récord estableció el delantero francés Kylian Mbappé al convertirse en el máximo goleador de Qatar 2022?",o:["Primer jugador en marcar 8 goles desde Ronaldo 2002","El goleador más joven de una final","El primer europeo en ganar la Bota de Oro desde 1998","Primer jugador en marcar en 4 fases distintas del torneo"],a:0,exp:"Mbappé marcó 8 goles en Qatar 2022, igualando el récord de Ronaldo Nazário en 2002 para el máximo goleador de un torneo de 32 equipos.",extra:"El hat-trick de Mbappé en la final fue excepcional pero no alcanzó para Francia. Sus 3 goles en los últimos 15 minutos igualaron el partido a 3-3 antes de los penales."},
  {t:"m",q:"¿Cuántas veces ha ganado Argentina el Mundial y cuáles son los años?",o:["2 veces: 1978 y 1986","3 veces: 1978, 1986 y 2022","2 veces: 1986 y 2022","4 veces"],a:1,exp:"Argentina ganó 3 Mundiales: 1978 (local, con César Menotti), 1986 (México, con Maradona) y 2022 (Qatar, con Lionel Messi).",extra:"En 1978 el título fue polémico por el régimen militar en el poder. En 1986 fue el de Maradona. En 2022 fue el de Messi, quizás el más emocionante de los tres."},
  {t:"m",q:"¿Qué selección ganó el Mundial como local más recientemente?",o:["Brasil 2014","Argentina 1978","Francia 1998","Alemania 2006"],a:2,exp:"Francia ganó el Mundial de 1998 jugando como local, venciendo a Brasil 3-0 en la final. Fue el último título obtenido por un país anfitrión.",extra:"Desde Francia 1998, ningún anfitrión ha ganado el torneo. Brasil 2014 fue eliminado en semifinales (7-1 vs Alemania) y Qatar 2022 no pasó de grupos."},
  {t:"m",q:"¿Cuántos goles se marcaron en total en el Mundial de Qatar 2022?",o:["142 goles","172 goles","172 goles","156 goles"],a:1,exp:"En Qatar 2022 se marcaron 172 goles en 64 partidos, con un promedio de 2,69 goles por partido, siendo uno de los torneos con más goles por partido de la historia reciente.",extra:"El promedio de goles por partido fue el más alto desde el Mundial de Francia 1998. La calidad de los atacantes y el ritmo del torneo contribuyeron al festival de goles."},
  {t:"m",q:"¿Qué portero se consagró como héroe en la final del Mundial 2022 tapando dos penales ante Francia?",o:["David De Gea","Alisson Becker","Emiliano Martínez","Hugo Lloris"],a:2,exp:"Emiliano Martínez (Argentina) fue clave en la final de Qatar 2022: atajó el penal de Kingsley Coman y la definición de Randal Kolo Muani para que Argentina ganara por penales.",extra:"'El Dibu' Martínez también fue figura en semifinales ante Croacia. Su provocativa celebración del Guante de Oro generó controversia pero reflejó su intensidad competitiva."},
  {t:"m",q:"¿Qué selección latinoamericana eliminó a Polonia y llegó a cuartos de final en el Mundial de Qatar 2022?",o:["Ecuador","México","Perú","Australia"],a:1,exp:"Australia eliminó a Polonia... en realidad fue Australia quien fue a octavos. México no pasó de grupos. En cuartos de final de LATAM en 2022 estuvieron Brasil y Argentina.",extra:"Brasil llegó a cuartos donde perdió ante Croacia en penales. Argentina superó Países Bajos en cuartos. México quedó eliminado en la fase de grupos pese a ganar 2-1 a Polonia."},
  {t:"f",q:"México ha sido eliminado en la fase de octavos de final (ronda de 16) en sus últimas 7 participaciones consecutivas en el Mundial.",o:["Verdadero","Falso"],a:0,exp:"Verdadero. Desde 1994 hasta 2018, México llegó siempre a octavos y siempre cayó. En Qatar 2022 ni siquiera llegó a esa fase, rompiendo la racha pero de la peor manera.",extra:"La 'maldición del quinto partido' (no pasar de octavos) se convirtió en un fenómeno cultural en México. Romperla sigue siendo el gran objetivo de la selección azteca."},
  {t:"m",q:"¿Cuál es el nombre del estadio principal de la ciudad de Dallas que será sede del Mundial 2026?",o:["Cowboys Stadium","Mercedes-Benz Stadium","AT&T Stadium","Globe Life Field"],a:2,exp:"El AT&T Stadium (antes conocido como Cowboys Stadium) en Arlington, Texas, es el estadio sede del Mundial 2026 en el área de Dallas, con capacidad para 100.000 espectadores.",extra:"Es el estadio techado más grande del mundo y uno de los más modernos de los EE.UU. Tiene una pantalla gigante central que es la más grande en un estadio deportivo."},
  {t:"m",q:"¿En qué estadio de Los Ángeles se jugó la final del Mundial de 1994 en Estados Unidos?",o:["SoFi Stadium","Rose Bowl","Memorial Coliseum","Dignity Health Sports Park"],a:1,exp:"La final del Mundial 1994 se jugó en el Rose Bowl de Pasadena (Los Ángeles), con más de 94.000 espectadores presenciando el Brasil vs Italia.",extra:"El Rose Bowl también será sede del Mundial 2026. Es uno de los estadios más históricos de EE.UU. con más de 100 años de historia y fue sede también de los JJOO 1984."},
  {t:"m",q:"¿Cuántas veces fue campeón del mundo Didier Deschamps: como jugador y como entrenador de Francia?",o:["Solo 1 vez como jugador","1 vez como jugador (1998) y 1 vez como entrenador (2018)","2 veces como jugador","2 veces como entrenador"],a:1,exp:"Didier Deschamps ganó el Mundial de 1998 como capitán de Francia y el de 2018 como entrenador de la misma selección. Es uno de los pocos en lograrlo en ambos roles.",extra:"El único otro jugador/entrenador bicampeón fue Franz Beckenbauer (jugador 1974, entrenador 1990 con Alemania). Deschamps igualó esa hazaña en 2018."},
  {t:"m",q:"¿Qué selección venció a la ampliamente favorita España en la final del Mundial de Sudáfrica 2010?",o:["Brasil","Países Bajos","Alemania","Uruguay"],a:1,exp:"Países Bajos (Holanda) fue el rival de España en la final del Mundial 2010. España ganó 1-0 con gol de Andrés Iniesta en el minuto 116 de la prórroga.",extra:"Fue el primer Mundial de España. La selección había dominado el fútbol mundial con el 'tiki-taka' de Guardiola/Del Bosque. Iniesta marcó el gol del título y fue figura del torneo."},
  {t:"m",q:"¿Qué jugador argentino marcó el gol a los 17 años en el Mundial de 2022 convirtiéndose en uno de los más jóvenes en marcar en una final?",o:["Lautaro Martínez","Ángel Di María","Julián Álvarez","Paulo Dybala"],a:2,exp:"Julián Álvarez no marcó en la final, fue Ángel Di María. Pero Julián Álvarez fue el segundo goleador del torneo con 4 goles. Di María marcó en la final a los 34 años.",extra:"Di María abrió el marcador en la final ante Francia con un gol de penal en el primer tiempo. Fue uno de sus mejores partidos con Argentina en un torneo mundialista."},
  {t:"m",q:"¿Cuántos mundiales dirigió Marcelo Bielsa, el 'Loco' conocido por su influencia en el fútbol moderno?",o:["1 Mundial","2 Mundiales","3 Mundiales","Nunca dirigió un Mundial"],a:0,exp:"Marcelo Bielsa dirigió un único Mundial: Francia 1998 con Argentina, donde llegaron a cuartos de final siendo eliminados por Países Bajos en penales (1-1 después de 90 min).",extra:"Bielsa llevó a Argentina con un excelente juego pero la eliminación ante Holanda fue polémica. Su huella como técnico ha marcado a generaciones de entrenadores como Guardiola y Klopp."},
  {t:"f",q:"El Mundial 2026 será la primera Copa del Mundo en la historia con 48 equipos participantes.",o:["Verdadero","Falso"],a:0,exp:"Verdadero. El Mundial 2026 inaugurará el formato de 48 selecciones, un aumento del 50% respecto a los 32 equipos que participaron desde 1998 hasta 2022.",extra:"La FIFA aprobó el nuevo formato en 2017. Hubo debates sobre si el aumento de equipos diluía la calidad, pero también argumentos sobre mayor representación global del fútbol."},
  {t:"m",q:"¿Quién será el único estadio en la historia del fútbol en albergar partidos de tres Copas del Mundo diferentes (1970, 1986 y 2026)?",o:["Camp Nou (Barcelona)","Wembley Stadium (Londres)","Estadio Azteca (Ciudad de México)","Maracaná (Río de Janeiro)"],a:2,exp:"El Estadio Azteca será el único estadio del mundo en albergar partidos de tres ediciones distintas de la Copa del Mundo: 1970, 1986 y 2026.",extra:"En el Azteca de 1970 se jugó la final (Brasil 4-1 Italia). En 1986 se jugó otra final (Argentina 3-2 Alemania) y el gol del siglo de Maradona. En 2026 será sede nuevamente."},
];
export default mundial2026Questions;
