const sonicQuestions = [
  // ── ERA CLÁSICA ──────────────────────────────────────────────
  {t:"m",q:"¿En qué año se lanzó Sonic the Hedgehog por primera vez para Sega Mega Drive?",o:["1989","1991","1993","1995"],a:1,exp:"Sonic the Hedgehog debutó el 23 de junio de 1991 en Japón para la Mega Drive.",extra:"La fecha del 23 de junio se convirtió en el 'Día de Sonic' y se celebra cada año como aniversario oficial del personaje."},
  {t:"m",q:"¿Cuál es el nombre de la primera zona de Sonic the Hedgehog (1991)?",o:["Spring Yard Zone","Marble Zone","Green Hill Zone","Scrap Brain Zone"],a:2,exp:"Green Hill Zone es la icónica primera zona del juego original, famosa por sus loopings y colinas verdes.",extra:"Su música compuesta por Masato Nakamura se convirtió en uno de los temas más reconocibles de los videojuegos."},
  {t:"m",q:"¿Cuál es el nombre completo del Dr. Eggman?",o:["Dr. Albert Robotnik","Dr. Ivo Robotnik","Dr. Gerald Robotnik","Dr. Julian Kintobor"],a:1,exp:"El nombre oficial es Dr. Ivo Robotnik. En Occidente se usó 'Robotnik' como nombre principal hasta Sonic Adventure; 'Eggman' es su apodo.",extra:"En los juegos japoneses siempre fue llamado Eggman/Egguman, mientras que en los occidentales se popularizó el apellido Robotnik."},
  {t:"m",q:"¿Cuántas Esmeraldas del Caos existen en la saga principal de Sonic?",o:["5","6","7","8"],a:2,exp:"Las 7 Esmeraldas del Caos son las piedras preciosas más poderosas del universo Sonic. Recolectarlas permite la transformación en Super Sonic.",extra:"Cada Esmeralda representa un color: amarillo, azul, rojo, verde, gris, cian y morado/blanco según el juego."},
  {t:"m",q:"¿En qué juego apareció por primera vez Knuckles the Echidna?",o:["Sonic CD (1993)","Sonic the Hedgehog 2 (1992)","Sonic the Hedgehog 3 (1994)","Knuckles' Chaotix (1995)"],a:2,exp:"Knuckles hizo su debut en Sonic the Hedgehog 3 (1994) como el guardián de la Master Emerald que inicialmente se opone a Sonic.",extra:"Knuckles fue engañado por Eggman para que creyera que Sonic era el villano, un malentendido que generó uno de los arcos más queridos de la saga."},
  {t:"m",q:"¿Qué reliquia ancestral custodia Knuckles the Echidna en Angel Island?",o:["Las 7 Esmeraldas del Caos","La Power Ring","La Master Emerald","El Chaos Crystal"],a:2,exp:"La Master Emerald es una gema gigante que neutraliza el poder de las Esmeraldas del Caos. Knuckles es el último guardián de su linaje.",extra:"La Master Emerald reposa en la Altar de la Gema en lo alto de Angel Island, que flota en el cielo gracias a su poder."},
  {t:"m",q:"¿Cuál es el nombre completo oficial de Tails?",o:["Thomas 'Tails' Prower","Miles 'Tails' Prower","Max 'Tails' Prower","Felix 'Tails' Prower"],a:1,exp:"Su nombre completo es Miles 'Tails' Prower, un juego de palabras con 'miles per hour' (millas por hora), haciendo referencia a su velocidad.",extra:"El apodo 'Tails' proviene de sus dos colas, que usa como hélice para volar. Es el mejor amigo y compañero inseparable de Sonic."},
  {t:"m",q:"¿Qué habilidad especial tiene Tails que Sonic no posee?",o:["Trepar paredes","Volar usando sus dos colas","Hacerse invisible","Lanzar proyectiles"],a:1,exp:"Tails puede volar durante un tiempo limitado haciendo girar sus dos colas como una hélice, lo que le permite alcanzar plataformas elevadas.",extra:"Esta habilidad debutó como mecánica jugable en Sonic the Hedgehog 2 (1992), donde Tails apareció por primera vez como personaje secundario."},
  {t:"m",q:"¿En qué juego de Mega Drive se puede jugar como Super Sonic por primera vez de forma completa?",o:["Sonic the Hedgehog (1991)","Sonic the Hedgehog 2 (1992)","Sonic CD (1993)","Sonic 3 & Knuckles"],a:1,exp:"Aunque hay referencias en Sonic 1, Super Sonic es plenamente jugable desde Sonic the Hedgehog 2, tras recolectar las 7 Esmeraldas del Caos.",extra:"Super Sonic es invencible, muy rápido y consume 1 anillo por segundo; si se queda sin anillos, regresa a la forma normal."},
  {t:"m",q:"¿Cómo se llama el arma icónica de Amy Rose?",o:["Chaos Hammer","Star Mallet","Piko Piko Hammer","Rose Crusher"],a:2,exp:"El Piko Piko Hammer es el arma característica de Amy Rose. Es desproporcionadamente grande y poderoso para su tamaño.",extra:"Amy lo usa por primera vez como arma en Sonic Adventure (1998), aunque el personaje debutó en Sonic CD (1993) como la 'novia' de Sonic."},
  {t:"m",q:"¿En qué juego de Sonic apareció Amy Rose por primera vez?",o:["Sonic the Hedgehog 2","Sonic the Hedgehog 3","Sonic CD (1993)","Sonic R"],a:2,exp:"Amy Rose debutó en Sonic CD (1993), donde era conocida como 'Princess Sally' en los bocetos previos, aunque fue renombrada Amy.",extra:"En Sonic CD, Amy es secuestrada por Metal Sonic por órdenes de Eggman, siendo el primer personaje femenino recurrente de la saga."},
  {t:"f",q:"Sonic the Hedgehog sabe nadar bien y puede moverse ágilmente bajo el agua sin restricciones.",o:["Verdadero","Falso"],a:1,exp:"Falso. Sonic no sabe nadar; bajo el agua hay un contador que si llega a cero lo mata. Junto al fuego, el agua es su principal debilidad.",extra:"Esta limitación es canónica en la saga: incluso en algunos comics y series animadas se menciona que Sonic tiene miedo o rechazo al agua."},
  {t:"f",q:"Knuckles the Echidna puede planear en el aire extendiendo sus brazos para descender lentamente.",o:["Verdadero","Falso"],a:0,exp:"Verdadero. Knuckles puede planear horizontalmente en el aire al extender sus puños, permitiéndole cubrir grandes distancias.",extra:"Además de planear, Knuckles puede escalar paredes usando sus espinas de nudillos, una habilidad única entre los personajes principales de Sonic."},
  {t:"m",q:"¿Cuál fue la segunda zona de Sonic the Hedgehog (1991), de temática de ruinas antiguas?",o:["Labyrinth Zone","Spring Yard Zone","Star Light Zone","Marble Zone"],a:3,exp:"Marble Zone es la segunda zona del primer Sonic, con estética de ruinas de mármol y lava, presentando un ritmo mucho más lento que Green Hill.",extra:"Marble Zone sorprendió a muchos jugadores que esperaban la misma velocidad de Green Hill, siendo una de las zonas más memorables por su contraste."},

  // ── ERA DREAMCAST / ADVENTURE ────────────────────────────────
  {t:"m",q:"¿En qué consola se lanzó originalmente Sonic Adventure (1998)?",o:["Sega Saturn","Sega Dreamcast","PlayStation","Nintendo 64"],a:1,exp:"Sonic Adventure fue el juego estrella de lanzamiento de la Sega Dreamcast en Japón en 1998, siendo el primer Sonic 3D con historia completa.",extra:"Fue revolucionario en su época por su exploración libre, sistema de historia con múltiples personajes jugables y crianza de Chao."},
  {t:"m",q:"¿Cuál es el antagonista final de Sonic Adventure (1998)?",o:["Chaos Perfecto","Neo Metal Sonic","Biolizard","Dark Gaia"],a:0,exp:"Perfect Chaos es la forma final del ser acuático Chaos, que inunda Station Square. Sonic usa las Esmeraldas para transformarse en Super Sonic y derrotarlo.",extra:"Chaos es un ser antiguo que estuvo encerrado en la Master Emerald por Tikal durante miles de años antes de ser liberado por Eggman."},
  {t:"m",q:"¿En qué juego apareció por primera vez Shadow the Hedgehog?",o:["Sonic Adventure (1998)","Sonic Heroes (2003)","Sonic Adventure 2 (2001)","Sonic Battle (2003)"],a:2,exp:"Shadow the Hedgehog debutó en Sonic Adventure 2 (2001) como el personaje misterioso que comparte aspecto con Sonic pero actúa como rival.",extra:"Shadow fue creado por el Prof. Gerald Robotnik como la 'Forma de Vida Suprema', usando ADN de Black Doom, el líder de los Black Arms."},
  {t:"m",q:"¿Cómo se llama la estación espacial donde transcurre gran parte de Sonic Adventure 2?",o:["Eggman Space Base","Ark Colony","Space Colony ARK","Death Egg"],a:2,exp:"La Space Colony ARK es una estación espacial donde Gerald Robotnik realizó sus investigaciones; también es el hogar de infancia de Maria.",extra:"El ARK fue sellado por G.U.N. años antes del juego. Eggman activa el Eclipse Cannon, un arma dentro del ARK, como parte de su plan."},
  {t:"m",q:"¿Quién es el científico que creó a Shadow the Hedgehog?",o:["Dr. Ivo Robotnik","Professor Robotnik","Gerald Robotnik","Black Doom"],a:2,exp:"El Profesor Gerald Robotnik creó a Shadow como la Forma de Vida Suprema en la Space Colony ARK, utilizando ADN de Black Doom.",extra:"Gerald fue encarcelado y posteriormente ejecutado por G.U.N. tras el sellado del ARK, dejando mensajes cifrados que Shadow descubrirá años después."},
  {t:"m",q:"¿Qué relación familiar existe entre el Profesor Gerald Robotnik y el Dr. Eggman?",o:["Padre e hijo","Hermanos","Abuelo y nieto","Tío y sobrino"],a:2,exp:"Gerald Robotnik es el abuelo del Dr. Ivo Robotnik (Eggman). Esta revelación en SA2 añade profundidad emocional a la historia del ARK.",extra:"Eggman descubre que su abuelo construyó el Eclipse Cannon y programó al ARK para caer sobre la Tierra como venganza contra G.U.N."},
  {t:"m",q:"¿De quién es el ADN que Gerald Robotnik usó para crear a Shadow como Forma de Vida Suprema?",o:["Chaos","Black Doom","Mephiles","Perfect Chaos"],a:1,exp:"Gerald usó ADN de Black Doom, el líder alienígena de los Black Arms, para dar a Shadow sus habilidades únicas. Esto se revela en Shadow the Hedgehog (2005).",extra:"Por eso Shadow puede usar Chaos Control de forma natural, ya que los Black Arms tienen ese poder. También explica por qué Black Doom lo reconoce."},
  {t:"m",q:"¿Cómo se llama la habilidad de Shadow que le permite distorsionar el espacio y el tiempo?",o:["Dark Speed","Shadow Blast","Chaos Control","Dark Warp"],a:2,exp:"Chaos Control es la habilidad que permite manipular el espacio-tiempo usando las Esmeraldas del Caos. Shadow la usa con especial maestría.",extra:"Sonic también puede usar Chaos Control en ciertos momentos, pero Shadow es el usuario más hábil de esta técnica en toda la saga."},
  {t:"m",q:"¿En qué juego hizo su debut Rouge the Bat?",o:["Sonic Adventure (1998)","Sonic Heroes (2003)","Sonic Adventure 2 (2001)","Shadow the Hedgehog (2005)"],a:2,exp:"Rouge the Bat debutó en Sonic Adventure 2 (2001), donde actúa como espía de G.U.N. infiltrada en los planes de Eggman.",extra:"Rouge es una ladrona de joyas que trabaja ocasionalmente para G.U.N. Su relación con Shadow y Omega forma el Team Dark."},
  {t:"f",q:"Rouge the Bat trabaja en secreto como agente espía para la organización G.U.N.",o:["Verdadero","Falso"],a:0,exp:"Verdadero. Aunque actúa como cazadora de joyas independiente, Rouge es una agente encubierta de G.U.N. que investiga a Eggman y el ARK.",extra:"Su doble rol de villana/aliada la convierte en uno de los personajes moralmente más ambiguos de la saga junto a Shadow."},
  {t:"m",q:"¿Cuántos equipos de personajes existen en Sonic Heroes (2003)?",o:["3","4","5","6"],a:1,exp:"Sonic Heroes tiene 4 equipos: Team Sonic (Sonic, Tails, Knuckles), Team Dark (Shadow, Rouge, Omega), Team Rose (Amy, Cream, Big) y Team Chaotix.",extra:"Cada equipo tiene tres clases de personaje: velocidad, vuelo y poder, y todos abordan la misma historia desde perspectivas diferentes."},
  {t:"m",q:"¿Quiénes conforman el Team Dark en Sonic Heroes?",o:["Shadow, Rouge y Gamma","Shadow, Rouge y Omega","Silver, Blaze y Rouge","Shadow, Metal Sonic y Rouge"],a:1,exp:"Team Dark está formado por Shadow the Hedgehog, Rouge the Bat y E-123 Omega, el robot de Eggman que quiere venganza contra su creador.",extra:"E-123 Omega fue sellado junto a Shadow al inicio de Heroes. Su furia contra Eggman lo lleva a aliarse con Shadow y Rouge."},

  // ── PERSONAJES MODERNOS ──────────────────────────────────────
  {t:"m",q:"¿De qué época proviene Silver the Hedgehog?",o:["Del pasado, 200 años antes","Del futuro, 200 años después","De una dimensión paralela","De la Luna"],a:1,exp:"Silver viene del futuro, aproximadamente 200 años después de los eventos presentes, donde el mundo está destruido por el flamante Iblis.",extra:"Silver viaja al pasado para eliminar el 'Mephiles' que causó la catástrofe, lo que lo pone en conflicto directo con Sonic."},
  {t:"m",q:"¿Cuál es el poder especial de Silver the Hedgehog?",o:["Pircinesis (fuego)","Crioquinesis (hielo)","Telequinesis (psíquico)","Electrocinesis (electricidad)"],a:2,exp:"Silver posee poderosas habilidades psíquicas (telequinesis) que le permiten levitar objetos y rivales con su mente.",extra:"En Sonic the Hedgehog (2006), Silver puede suspender a Sonic en el aire usando su telequinesis, siendo uno de los rivales más peligrosos del juego."},
  {t:"m",q:"¿En qué juego apareció por primera vez Blaze the Cat?",o:["Sonic Riders (2006)","Sonic Rush (2005)","Sonic the Hedgehog (2006)","Sonic Unleashed (2008)"],a:1,exp:"Blaze debutó en Sonic Rush (2005) para Nintendo DS, donde colabora con Sonic desde su dimensión paralela.",extra:"En Sonic Rush, Blaze recolecta las Sol Emeralds de su mundo mientras Sonic reúne las Chaos Emeralds, y juntos enfrentan a Eggman y Eggman Nega."},
  {t:"m",q:"¿Cuál es el poder de Blaze the Cat?",o:["Control del hielo","Pirocinesis (control del fuego)","Velocidad supersónica","Invisibilidad"],a:1,exp:"Blaze tiene pirocinesis, la capacidad de generar y controlar el fuego. Es una princesa de la Sol Dimension con este don innato.",extra:"Su forma superpoderosa, Burning Blaze, se activa con las 7 Sol Emeralds y es el equivalente a Super Sonic en su dimensión."},
  {t:"m",q:"¿Cómo se llama la transformación nocturna de Sonic en Sonic Unleashed (2008)?",o:["Dark Sonic","Shadow Form","Werehog","Chaos Sonic"],a:2,exp:"En Sonic Unleashed, Dark Gaia fragmenta el alma de Sonic de noche convirtiéndolo en el Werehog, con cuerpo elástico y fuerza bruta.",extra:"El Werehog juega completamente diferente al Sonic normal: es un juego de acción cuerpo a cuerpo lento, no de velocidad."},
  {t:"m",q:"¿Cómo se llaman los seres extraterrestres que Sonic conoce en Sonic Colors (2010)?",o:["Chao","Wisps","Mobians","Flicky"],a:1,exp:"Los Wisps son alienígenas que Eggman ha capturado para usar su energía como combustible. Sonic los libera y ellos le otorgan poderes temporales.",extra:"Cada color de Wisp da un poder diferente: el Cyan Wisp convierte a Sonic en un láser, el Red Wisp en una roca, el Yellow en un taladro, etc."},
  {t:"m",q:"¿Cuáles son los dos Sonic jugables en Sonic Generations (2011)?",o:["Super Sonic y Hyper Sonic","Sonic y Shadow","Sonic Clásico y Sonic Moderno","Sonic y Metal Sonic"],a:2,exp:"Sonic Generations presenta dos versiones de Sonic: el Clásico de los años 90 (silencioso, con Spin Dash) y el Moderno (con voz y Homing Attack).",extra:"El juego celebra los 20 años de Sonic revisitando zonas icónicas de toda la historia con ambos personajes."},
  {t:"f",q:"Sonic Mania (2017) fue desarrollado en parte por fans de Sonic que se profesionalizaron y fueron contratados por SEGA.",o:["Verdadero","Falso"],a:0,exp:"Verdadero. Christian Whitehead, PagodaWest Games y Headcannon (todos conocidos por sus proyectos fan) lideraron el desarrollo de Sonic Mania.",extra:"Sonic Mania fue muy bien recibido por la crítica, considerado el mejor juego de Sonic en años, y revitalizó el interés en el estilo clásico."},
  {t:"m",q:"¿Qué tipo de mundo introdujo Sonic Frontiers (2022) por primera vez en la saga principal?",o:["Un mundo procedural infinito","Niveles lineales con múltiples caminos","Un mundo abierto de exploración libre (open-zone)","Una ciudad sandbox editable"],a:2,exp:"Sonic Frontiers introdujo el concepto 'open-zone' en la saga: mundos abiertos gigantes que Sonic puede explorar libremente antes de abordar los niveles.",extra:"Fue el primer Sonic 3D en alejarse radicalmente del diseño de etapas lineales, acercándose más a juegos como Breath of the Wild."},
  {t:"m",q:"¿Quién diseñó visualmente a Sonic the Hedgehog originalmente en SEGA?",o:["Yuji Naka","Masato Nakamura","Naoto Ohshima","Hirokazu Yasuhara"],a:2,exp:"Naoto Ohshima diseñó el aspecto visual de Sonic. Yuji Naka programó el motor del juego y Hirokazu Yasuhara diseñó los niveles.",extra:"La banda sonora del primer juego fue compuesta por Masato Nakamura, bajista del grupo musical Dreams Come True."},

  // ── PERSONAJES SECUNDARIOS ───────────────────────────────────
  {t:"m",q:"¿En qué juego apareció por primera vez Metal Sonic?",o:["Sonic the Hedgehog 2","Sonic CD (1993)","Sonic 3 & Knuckles","Sonic Adventure"],a:1,exp:"Metal Sonic debutó en Sonic CD (1993) como la gran creación de Eggman: una versión mecánica de Sonic que le sirve de rival principal.",extra:"Su icónica carrera en Stardust Speedway contra Sonic es una de las secuencias más memorables de la saga clásica."},
  {t:"f",q:"Metal Sonic tiene la capacidad de escanear y copiar datos de otros personajes para replicar sus habilidades.",o:["Verdadero","Falso"],a:0,exp:"Verdadero. Especialmente en Sonic Heroes, Neo Metal Sonic copia datos de Sonic, Shadow y Chaos para transformarse en Metal Overlord.",extra:"Esta habilidad lo convierte en el antagonista oculto de Sonic Heroes, haciéndose pasar por Eggman para manipular a todos los equipos."},
  {t:"m",q:"¿Cómo se llama la chao mascota de Cream the Rabbit?",o:["Froggy","Cheese","Gemerl","Chocola"],a:1,exp:"Cheese es el pequeño chao azul que acompaña siempre a Cream. A diferencia de otros chao, Cheese participa activamente en combate.",extra:"Cream y Cheese debutan en Sonic Advance 2 (2002) y luego aparecen en Sonic Heroes, Sonic Battle, Sonic Rush y otras entregas."},
  {t:"m",q:"¿Qué busca Big the Cat durante toda su historia en Sonic Adventure (1998)?",o:["La Master Emerald","La Power Ring","Su rana llamada Froggy","Las Esmeraldas del Caos"],a:2,exp:"Big the Cat pasa toda su campaña en SA1 buscando a Froggy, su rana mascota que huyó después de tragarse una cola de Chaos.",extra:"La campaña de Big en SA1 es recordada por ser radicalmente diferente al ritmo del resto del juego, centrada en la pesca."},
  {t:"m",q:"¿Cuál es el nombre del robot de Eggman que forma parte del Team Dark junto a Shadow y Rouge?",o:["E-102 Gamma","E-123 Omega","E-10000 G","Metal Sonic"],a:1,exp:"E-123 Omega es el último y más poderoso de los robots E-Series de Eggman, que lo encerró en la misma instalación que a Shadow.",extra:"Omega busca venganza contra Eggman por haberlo sellado. Su implacable fuerza de fuego es clave en las batallas del Team Dark."},
  {t:"m",q:"¿Cuál es el nombre del líder de los Babylon Rogues en Sonic Riders (2006)?",o:["Wave the Swallow","Storm the Albatross","Jet the Hawk","Silver the Hedgehog"],a:2,exp:"Jet the Hawk es el líder de los Babylon Rogues y el rival más directo de Sonic en Sonic Riders, donde compiten en carreras de aeroplanchas.",extra:"Jet se llama a sí mismo el 'Fastest Thing in the World', título que lo pone en conflicto constante con Sonic."},
  {t:"m",q:"¿Quiénes son los tres miembros del Team Chaotix?",o:["Espio, Charmy y Vector","Knuckles, Espio y Vector","Cream, Espio y Vector","Big, Charmy y Vector"],a:0,exp:"El Team Chaotix está formado por Espio the Chameleon, Charmy Bee y Vector the Crocodile, quienes dirigen la agencia detective Chaotix.",extra:"Los Chaotix aparecieron por primera vez en Knuckles' Chaotix (1995) para Sega 32X, siendo uno de los primeros spinoffs importantes de Sonic."},
  {t:"m",q:"¿En qué juego hicieron su debut los personajes del Team Chaotix?",o:["Sonic CD (1993)","Knuckles' Chaotix (1995)","Sonic Heroes (2003)","Sonic Advance 3"],a:1,exp:"Knuckles' Chaotix (1995) para Sega 32X introdujo a Espio, Charmy, Vector, Mighty y Heavy/Bomb. Vector se conoció por primera vez aquí.",extra:"Knuckles' Chaotix tuvo un mechanic único: dos personajes siempre conectados por un elástico de energía, lo que afectaba el movimiento."},

  // ── LORE Y ORGANIZACIONES ────────────────────────────────────
  {t:"m",q:"¿Qué significa la sigla G.U.N. en el universo de Sonic?",o:["Global Union of Nations","Guardian Units of Nations","General United Network","Galactic Universal Nexus"],a:1,exp:"G.U.N. son las Guardian Units of Nations, una organización militar gubernamental que opera en secreto, a veces como antagonista.",extra:"G.U.N. capturó a Gerald Robotnik y mató a Maria. Años después, persigue a Shadow creyéndolo peligroso."},
  {t:"m",q:"¿Quién es Maria Robotnik y qué relación tiene con Shadow?",o:["La hija de Eggman y enemiga de Shadow","La hermana de Gerald y programadora del ARK","La nieta de Gerald Robotnik y mejor amiga de Shadow","Una robot creada para acompañar a Shadow"],a:2,exp:"Maria era la nieta del Prof. Gerald Robotnik y vivía en el ARK due a su enfermedad (NIDS). Era la mejor amiga de Shadow hasta que G.U.N. la mató.",extra:"El deseo de Maria antes de morir era que Shadow protegiera a las personas de la Tierra; esto motiva el arco redentor de Shadow en SA2."},
  {t:"f",q:"Al final de Sonic Adventure 2, Shadow aparentemente muere después de usar el Chaos Control con Super Sonic para salvar la Tierra.",o:["Verdadero","Falso"],a:0,exp:"Verdadero. Shadow usa sus últimas fuerzas junto a Super Sonic para detener el ARK y cae al espacio, dando a entender que muere. Regresa en Sonic Heroes.",extra:"Su 'muerte' al final de SA2 fue un momento emotivo poderoso, aunque posteriormente Eggman reveló que lo había salvado y tenía copias en cápsulas."},
  {t:"m",q:"¿Cómo se llama la forma superpoderosa de Knuckles obtenida con las Super Emeralds en Sonic 3 & Knuckles?",o:["Mega Knuckles","Super Knuckles","Hyper Knuckles","Dark Knuckles"],a:2,exp:"Con las Super Emeralds (versión mejorada de las Chaos Emeralds en Sonic 3 & Knuckles), Knuckles se transforma en Hyper Knuckles.",extra:"Hyper Sonic, Hyper Tails e Hyper Knuckles son más poderosos que sus formas Super. Estas transformaciones solo existen en Sonic 3 & Knuckles."},
  {t:"m",q:"¿Cómo se llaman las versiones mejoradas de las Esmeraldas del Caos disponibles en Sonic 3 & Knuckles?",o:["Chaos Crystals","Hyper Emeralds","Super Emeralds","Master Shards"],a:2,exp:"Las Super Emeralds se obtienen llevando las 7 Chaos Emeralds a las Special Stages gigantes del Mushroom Hill en Sonic 3 & Knuckles.",extra:"Cada Esmeralda del Caos puede potenciarse en una Super Emerald pasándola por un Monitor de Super Emerald en los niveles secretos."},
  {t:"m",q:"¿Cómo se llama el ser de dos partes (Iblis y Mephiles) que es el dios destructor en Sonic the Hedgehog (2006)?",o:["Perfect Dark","Darkspine","Solaris","Iblis Prime"],a:2,exp:"Solaris es la deidad caótica dividida en Iblis (el flamante destructor sin mente) y Mephiles (la sombra consciente). Eggman lo separa accidentalmente.",extra:"Sonic 06 tiene un final donde Sonic y Elise apagan la llama de Solaris borrando toda la línea temporal del juego de la existencia."},

  // ── MECÁNICAS DE JUEGO ───────────────────────────────────────
  {t:"m",q:"¿Cuál fue la primera aparición del Homing Attack, la técnica de Sonic para atacar en el aire hacia enemigos?",o:["Sonic 3 & Knuckles","Sonic CD","Sonic Adventure (1998)","Sonic Spinball"],a:2,exp:"El Homing Attack en su forma moderna debutó en Sonic Adventure (1998) para Dreamcast, siendo clave en la nueva dimensión 3D del juego.",extra:"Esta técnica se volvió tan fundamental que aparece en prácticamente todos los juegos 3D de Sonic y es considerada su movimiento más reconocible en 3D."},
  {t:"m",q:"¿Qué necesita Sonic para transformarse en Super Sonic?",o:["Recolectar 50 anillos solamente","Las 7 Esmeraldas del Caos y al menos 50 anillos","Solo las 7 Esmeraldas del Caos","Un Power Ring especial y las Esmeraldas"],a:1,exp:"Para transformarse en Super Sonic se necesitan las 7 Esmeraldas del Caos y al menos 50 anillos. La transformación consume 1 anillo por segundo.",extra:"Esta mecánica se mantuvo consistente en la mayoría de juegos; Super Sonic es invencible, muy veloz y puede derrotar enemigos con solo tocarlo."},
  {t:"f",q:"En los juegos clásicos de Sonic, si recibes un golpe con al menos un anillo, no pierdes una vida sino que los anillos se dispersan.",o:["Verdadero","Falso"],a:0,exp:"Verdadero. Los anillos funcionan como escudo: al recibir daño, se dispersan y tienes un instante para recuperarlos. Sin anillos, el siguiente golpe es mortal.",extra:"Este sistema de 'escudo de anillos' es uno de los elementos más innovadores del diseño de Sonic, diferenciándolo del sistema de vidas de Mario."},
  {t:"m",q:"¿Cómo se llama la técnica de Sonic que le permite arrancar desde parado acumulando velocidad giratoria?",o:["Spin Jump","Spin Attack","Spin Dash","Rolling Start"],a:2,exp:"El Spin Dash permite a Sonic girar en el lugar para acumular velocidad y lanzarse a alta velocidad. Debutó en Sonic the Hedgehog 2.",extra:"El Spin Dash fue tan popular que no ha faltado en prácticamente ningún juego de Sonic desde su introducción en 1992."},

  // ── BANDA SONORA Y MEDIOS ────────────────────────────────────
  {t:"m",q:"¿Cómo se llama la banda de rock que realizó canciones icónicas para Sonic Adventure 2 como 'Live and Learn'?",o:["Dream Factory","Crush 40","Sonic Rush Band","Jun Force"],a:1,exp:"Crush 40 es la banda formada por Jun Senoue (guitarrista) y Johnny Gioeli (vocalista). Sus temas son emblemáticos de la era Adventure de Sonic.",extra:"'Live and Learn' suena durante el clímax de SA2 cuando Shadow y Sonic se transforman para salvar la Tierra, siendo uno de los momentos más épicos del juego."},
  {t:"m",q:"¿Cómo se llama la canción principal de Sonic Adventure 2?",o:["Open Your Heart","His World","Live and Learn","Escape from the City"],a:2,exp:"'Live and Learn' de Crush 40 es la canción principal de SA2 y suena en el combate final contra el Biolizard/Finalhazard.",extra:"La canción 'Escape from the City' de SA2, aunque no es la principal, es posiblemente la más icónica asociada al juego por la escena de la tabla en la autopista."},
  {t:"m",q:"¿Cómo se llama la canción principal de Sonic Adventure 1?",o:["Live and Learn","Open Your Heart","Believe in Myself","Unknown from M.E."],a:1,exp:"'Open Your Heart' de Crush 40 es la canción principal de Sonic Adventure (1998), cantada en el combate contra Perfect Chaos.",extra:"'Unknown from M.E.' es el rap de Knuckles en SA1. 'Believe in Myself' es el tema de Tails. Cada personaje tiene su propia canción."},
  {t:"m",q:"¿Cómo se llama el anime japonés de Sonic emitido entre 2003 y 2006?",o:["Sonic Underground","Sonic X","Sonic SatAM","Sonic Boom"],a:1,exp:"Sonic X es el anime japonés producido por TMS Entertainment que siguió las aventuras de Sonic y sus amigos junto al joven Chris Thorndyke.",extra:"Sonic X fue doblado a muchos idiomas y presentó adaptaciones del arco de Sonic Adventure, Sonic Adventure 2 y Sonic Battle."},
  {t:"m",q:"¿Quién dio voz a Sonic the Hedgehog en la película live-action de 2020?",o:["Roger Craig Smith","Jason Griffith","Ben Schwartz","Ryan Reynolds"],a:2,exp:"Ben Schwartz (conocido por Parks and Recreation y Jean-Ralphio) da voz al personaje de Sonic en las películas live-action.",extra:"La película fue notoria por cambiar el diseño de Sonic tras el rechazo masivo del tráiler original, rediseñando al personaje antes del estreno."},
  {t:"m",q:"¿Quién interpretó al Dr. Robotnik en la película Sonic the Hedgehog (2020)?",o:["Steve Carell","Jim Carrey","Will Ferrell","Bill Murray"],a:1,exp:"Jim Carrey dio vida al Dr. Robotnik con su característico humor exagerado, siendo uno de los aspectos más elogiados de la película.",extra:"La actuación de Carrey fue tan bien recibida que regresó en Sonic the Hedgehog 2 (2022), mostrando al personaje convertirse en el Eggman clásico."},
  {t:"m",q:"¿En qué año se estrenó la primera película live-action de Sonic the Hedgehog?",o:["2018","2019","2020","2021"],a:2,exp:"Sonic the Hedgehog se estrenó en febrero de 2020 y fue un éxito de taquilla, convirtiéndose en una de las mejores adaptaciones de videojuego al cine.",extra:"Originalmente planeada para noviembre de 2019, fue retrasada para permitir el rediseño completo del personaje tras las críticas al tráiler."},

  // ── CREADORES Y CONTEXTO ─────────────────────────────────────
  {t:"m",q:"¿Qué consola rival de Nintendo motivó la creación de Sonic como mascota para SEGA?",o:["NES (Nintendo Entertainment System)","Super Nintendo / SNES","Game Boy","Virtual Boy"],a:1,exp:"SEGA creó a Sonic para competir directamente con la Super Nintendo de Nintendo y su mascota Mario, que dominaba el mercado.",extra:"En 1991, la SNES superaba en ventas a la Mega Drive. Sonic fue el 'game changer' que cambió la percepción del hardware de SEGA."},
  {t:"f",q:"En Norteamérica, Sonic the Hedgehog se vendía incluido con la Sega Mega Drive como juego pack-in, sustituyendo a otros títulos.",o:["Verdadero","Falso"],a:0,exp:"Verdadero. Desde 1991, SEGA comenzó a incluir Sonic con la Genesis (Mega Drive) en Norteamérica para superar las ventas frente a Nintendo.",extra:"Esta estrategia fue tan exitosa que las ventas de la Mega Drive se dispararon. Sonic fue durante un tiempo el videojuego más vendido del mundo."},
  {t:"m",q:"¿Quién fue el principal programador y líder de Sonic Team durante los primeros juegos de Sonic?",o:["Naoto Ohshima","Hirokazu Yasuhara","Yuji Naka","Masato Nakamura"],a:2,exp:"Yuji Naka fue el programador principal del primer Sonic y líder de Sonic Team durante años. Es considerado el 'padre' de Sonic junto a Ohshima y Yasuhara.",extra:"En 2006, Yuji Naka dejó SEGA para fundar su propio estudio, Prope. Su partida marcó el fin de una era para Sonic Team."},
  {t:"f",q:"Sonic fue el primer personaje de SEGA en aparecer en la serie Super Smash Bros. de Nintendo.",o:["Verdadero","Falso"],a:0,exp:"Verdadero. Sonic fue el primer representante de SEGA en Smash Bros., debutando en Super Smash Bros. Brawl (2008) para Nintendo Wii.",extra:"Su inclusión fue muy solicitada por los fans durante años. Fue anunciado de forma dramática poco antes del lanzamiento de Brawl."},

  // ── JUEGOS ESPECÍFICOS ───────────────────────────────────────
  {t:"m",q:"¿Cómo se llama la zona de casino icónica del primer Sonic 2?",o:["Casinopolis","Spring Yard Zone","Casino Night Zone","Carnival Night Zone"],a:2,exp:"Casino Night Zone en Sonic the Hedgehog 2 es famosa por sus flipper, tragamonedas y bumpers. Es una de las zonas más recordadas de los juegos clásicos.",extra:"Sonic 3 tiene Carnival Night Zone con temática similar pero más enfocada en plataformas y la infame barril que muchos jugadores no sabían cómo superar."},
  {t:"m",q:"¿En qué juego apareció por primera vez la Chemical Plant Zone, luego revisitada en Generations y Mania?",o:["Sonic the Hedgehog (1991)","Sonic the Hedgehog 2 (1992)","Sonic CD (1993)","Sonic 3"],a:1,exp:"Chemical Plant Zone debutó en Sonic 2 (1992) como la icónica zona industrial morada con el líquido Mega Mack en el que Sonic se ahoga.",extra:"Esta zona regresó en Sonic Generations (2011) y Sonic Mania (2017), convirtiéndose en una de las más revisitadas de toda la franquicia."},
  {t:"m",q:"¿En qué zona de Sonic 3 & Knuckles cae Sonic desde el cielo al inicio del juego?",o:["Mushroom Hill Zone","Flying Battery Zone","Angel Island Zone","Hydrocity Zone"],a:2,exp:"Angel Island Zone es la primera zona de Sonic 3. Sonic aterriza en la isla flotante de Knuckles, quien destruye las Esmeraldas del Caos.",extra:"El opening de Sonic 3 es legendario: muestra a Sonic y Tails en el Tornado volando hacia la isla, con la épica música que acompaña la caída."},
  {t:"m",q:"¿En qué juego de Sonic para Nintendo DS aparece Blaze the Cat junto a Sonic por primera vez en la saga principal?",o:["Sonic Advance 2","Sonic Chronicles","Sonic Rush (2005)","Sonic Rush Adventure"],a:2,exp:"Sonic Rush (2005) para Nintendo DS presentó a Blaze the Cat y al villano Eggman Nega, siendo el primer juego exclusivo para DS de Sonic.",extra:"Sonic Rush usó las dos pantallas de la DS de forma creativa: Sonic corría por las dos simultáneamente y podía acumular boost para ir más rápido."},
  {t:"f",q:"Sonic the Hedgehog (2006) fue muy bien recibido por la crítica y los fans tras su lanzamiento.",o:["Verdadero","Falso"],a:1,exp:"Falso. Sonic 06 fue fuertemente criticado por sus bugs técnicos, tiempos de carga excesivos, historia confusa y controles defectuosos.",extra:"'Sonic 06' se convirtió en sinónimo de decepción en la comunidad; el proyecto fue apresurado para coincidir con el 15 aniversario del personaje."},
  {t:"m",q:"¿En qué año se lanzó Sonic Mania, el juego de regreso al estilo clásico?",o:["2015","2016","2017","2018"],a:2,exp:"Sonic Mania se lanzó en agosto de 2017 para PS4, Xbox One, Nintendo Switch y PC, recibiendo críticas muy positivas.",extra:"Sonic Mania Plus (2018) añadió a Mighty the Armadillo y Ray the Flying Squirrel como personajes jugables adicionales."},
  {t:"m",q:"¿Cuál de estas zonas de Sonic Mania (2017) es completamente original y no aparece en ningún juego clásico anterior?",o:["Green Hill Zone","Chemical Plant Zone","Studiopolis Zone","Hydrocity Zone"],a:2,exp:"Studiopolis Zone es una de las zonas nuevas de Sonic Mania, con temática de estudio de televisión. Fue creada completamente para el juego.",extra:"Sonic Mania tiene 12 zonas en total: algunas son remakes de clásicos (revisitadas con nuevas rutas y jefes) y otras son completamente originales."},
  {t:"m",q:"¿Cómo se llama la inteligencia artificial que actúa como aliada de Sonic en Sonic Frontiers (2022)?",o:["Aurora","ARIA","Sage","Nova"],a:2,exp:"Sage es una IA creada por Eggman que actúa como guardiana de las islas Starfall y eventualmente como aliada cuando comprende la amenaza de The End.",extra:"Sage tiene un rol importante en la narrativa de Frontiers, con un arco emocional similar al de Shadow en SA2, sobre la lealtad y la identidad."},

  // ── LORE ADICIONAL ───────────────────────────────────────────
  {t:"m",q:"¿Cuál es el coeficiente intelectual que se atribuye canónicamente al Dr. Eggman?",o:["200","250","300","400"],a:2,exp:"El Dr. Eggman tiene un IQ canónico de 300, lo que lo hace uno de los villanos más inteligentes de los videojuegos pese a sus fracasos constantes.",extra:"Su genialidad contrasta con su incapacidad de derrotar definitivamente a Sonic, lo que ha generado memes sobre su 'competencia selectiva'."},
  {t:"m",q:"¿Qué color son los ojos de Sonic en su diseño moderno (desde Sonic Adventure en adelante)?",o:["Negros","Azules","Verdes","Amarillos"],a:2,exp:"En su diseño moderno desde Sonic Adventure (1998), Sonic tiene ojos verdes brillantes. En el diseño clásico de los 90, sus ojos eran completamente negros.",extra:"El cambio a ojos verdes fue parte del rediseño para el paso a 3D. El color verde se mantiene como seña de identidad de Sonic moderno hasta hoy."},
  {t:"f",q:"En el diseño clásico original de Sonic (años 90), sus ojos eran completamente negros sin iris de color.",o:["Verdadero","Falso"],a:0,exp:"Verdadero. El Sonic clásico tiene ojos negros como los de cualquier personaje de dibujos animados de la época. Los ojos verdes son una característica del diseño moderno.",extra:"Esta diferencia entre el Sonic clásico y el moderno es uno de los contrastes visuales más notables en Sonic Generations."},
  {t:"m",q:"¿Cuál es el poder psíquico especial de Espio the Chameleon en los Chaotix?",o:["Controlar el fuego","Volar como Tails","Volverse invisible","Usar armas de largo alcance"],a:2,exp:"Espio puede volverse invisible usando sus habilidades de camaleón, lo que lo hace ideal para misiones de espionaje e infiltración.",extra:"También puede lanzar shurikens y trepar por paredes. Su personalidad ninja es uno de los rasgos más queridos por los fans de los Chaotix."},
  {t:"m",q:"¿Qué nombre recibe el jardín donde se crían y cuidan las criaturas virtuales en Sonic Adventure?",o:["Animal Kingdom","Chao Garden","Chaos Garden","Flicky Park"],a:1,exp:"El Chao Garden es el área donde los jugadores pueden criar, entrenar y evolucionar a sus Chao, las criaturas de huevo que habitan el universo de Sonic.",extra:"Los Chao pueden evolucionar hacia formas Hero o Dark según con qué personaje pasen más tiempo. El sistema de crianza fue muy popular en SA1 y SA2."},
  {t:"m",q:"¿Cómo se llama el robot de la serie E-Series en Sonic Adventure 1 que tiene un arco redentor, liberando animales atrapados en otros robots?",o:["E-100 Alpha","E-102 Gamma","E-123 Omega","E-104 Epsilon"],a:1,exp:"E-102 Gamma tiene un arco emotivo en SA1: creado por Eggman para cazar, decide en cambio liberar los animales atrapados dentro de sus hermanos robots.",extra:"El personaje de Gamma resonó enormemente con los jugadores por su historia de libre albedrío y sacrificio. Es considerado uno de los mejores arcos de SA1."},
  {t:"m",q:"¿Cómo se llaman las gemas equivalentes a las Esmeraldas del Caos en la dimensión de Blaze the Cat?",o:["Chaos Gems","Sol Emeralds","Fire Crystals","Sun Stones"],a:1,exp:"Las Sol Emeralds son las 7 gemas que Blaze recolecta en Sonic Rush para transformarse en Burning Blaze, el equivalente a Super Sonic.",extra:"Las Sol Emeralds existen en la Sol Dimension, paralela a la de Sonic. La magia de ambas dimensiones está interconectada en los eventos de Sonic Rush."},
  {t:"f",q:"La velocidad de Sonic supera canónicamente la velocidad del sonido (Mach 1, ~1234 km/h).",o:["Verdadero","Falso"],a:0,exp:"Verdadero. Canónicamente Sonic supera la velocidad del sonido, de ahí su nombre 'Sonic' (relacionado con el sonido). En algunos medios se dice que alcanza la velocidad de la luz.",extra:"La velocidad exacta varía según el medio: en los cómics puede acelerar aún más. Lo que está claro es que es el ser más rápido de su universo."},
  {t:"f",q:"Cream the Rabbit puede flotar usando sus largas orejas como si fueran hélices.",o:["Verdadero","Falso"],a:0,exp:"Verdadero. Cream puede volar temporalmente agitando sus grandes orejas, similar a cómo Tails usa sus colas para volar.",extra:"Esta mecánica la hace especialmente útil en juegos como Sonic Advance 2 y Sonic Heroes, donde puede mantener a Amy en el aire en el Team Rose."},

  // ── PREGUNTAS FINALES ────────────────────────────────────────
  {t:"m",q:"¿Cuál es la primera franquicia deportiva oficial donde Sonic y Mario aparecen juntos en un videojuego?",o:["Olimpiadas de Fútbol","Mario & Sonic en los Juegos Olímpicos de Pekín 2008","FIFA con personajes especiales","Sonic & Mario Tennis"],a:1,exp:"Mario & Sonic en los Juegos Olímpicos (2007) para Wii fue la primera vez que ambos personajes compartieron un videojuego oficial.",extra:"El juego fue un evento cultural enorme porque durante décadas Mario y Sonic fueron rivales. Su colaboración fue impensable para los fans de los años 90."},
  {t:"f",q:"Shadow the Hedgehog (2005) fue el primer juego de Sonic donde el personaje podía usar armas de fuego y conducir vehículos.",o:["Verdadero","Falso"],a:0,exp:"Verdadero. Shadow the Hedgehog (2005) fue el primer juego de la saga donde se podía usar pistolas, fusiles, granadas y conducir todo tipo de vehículos.",extra:"El juego intentó dirigirse a un público más maduro con temáticas oscuras y elecciones morales, recibiendo críticas mixtas por este enfoque."},
  {t:"m",q:"¿En qué consola portátil de SEGA se lanzaron varios juegos de Sonic en los años 90, paralelos a la Mega Drive?",o:["Game Gear","Nomad","Master System","Saturn Handheld"],a:0,exp:"La Game Gear de SEGA tuvo varios juegos de Sonic adaptados específicamente para la portátil, con niveles y diseño diferente a los de Mega Drive.",extra:"Sonic portátil para Game Gear incluía Sonic 1, 2, Sonic Chaos, Sonic Triple Trouble y más, todos con niveles diseñados para el formato portátil."},
  {t:"m",q:"¿Cómo se llama la canción principal de Sonic the Hedgehog (2006)?",o:["Live and Learn","Open Your Heart","His World","Endless Possibility"],a:2,exp:"'His World' interpretada por Zebrahead acompaña la historia de Sonic en el juego de 2006, sirviendo como su tema principal.",extra:"'Endless Possibility' es el tema de Sonic Unleashed; 'Reach for the Stars' es de Colors; 'Live and Learn' es de SA2. Cada era tiene su anthem."},
  {t:"m",q:"¿Cuántas zonas tiene Sonic the Hedgehog (1991) en total?",o:["4 zonas","5 zonas","6 zonas","8 zonas"],a:2,exp:"El primer Sonic tiene 6 zonas: Green Hill, Marble, Spring Yard, Labyrinth, Star Light y Scrap Brain. Cada una tiene 3 actos.",extra:"El diseño de 6 zonas con 3 actos cada una se convirtió en la fórmula estándar que Sonic 2 y 3 expandirían y modificarían."},
  {t:"m",q:"¿Qué tecnología especial permitía conectar el cartucho de Sonic & Knuckles con Sonic 2 y Sonic 3 en la Mega Drive?",o:["Sonic Fusion","Pass Through","Lock-On Technology","Combo Cartridge"],a:2,exp:"La Lock-On Technology del cartucho de Sonic & Knuckles permite insertar otros cartuchos en su conector superior para expandir el juego.",extra:"Sonic 3 + Sonic & Knuckles crea la experiencia completa que se pretendía originalmente; con Sonic 2 desbloquea Knuckles in Sonic 2."},
  {t:"m",q:"¿Cuál es la zona de tipo laberinto acuático del primer Sonic (1991) donde el agua puede ahogarlo?",o:["Oil Ocean Zone","Aquatic Ruin Zone","Hydrocity Zone","Labyrinth Zone"],a:3,exp:"Labyrinth Zone en Sonic 1 es la cuarta zona del juego y la primera en introducir el peligro del agua, con burbujas de aire que Sonic necesita para sobrevivir.",extra:"La zona es muy odiada y amada a partes iguales; muchos jugadores la recuerdan como la primera vez que Sonic los hizo perder por ahogamiento."},
  {t:"m",q:"¿En qué año hizo Sonic su debut en Super Smash Bros., convirtiéndose en el primer personaje de SEGA en la saga?",o:["2005","2006","2008","2010"],a:2,exp:"Sonic debutó en Super Smash Bros. Brawl en 2008 para Wii, siendo el primer y durante mucho tiempo único personaje de SEGA en la saga de Nintendo.",extra:"Su inclusión fue una de las más solicitadas por los fans desde Melee. Se anunció de forma dramática en el último Direct antes del lanzamiento de Brawl."},
  {t:"m",q:"¿Cómo se llama la serie animada occidental de los sábados por la mañana (SatAM) de Sonic de los años 90 donde los personajes viven en Knothole y luchan contra Robotnik?",o:["Sonic Underground","Adventures of Sonic the Hedgehog","Sonic the Hedgehog (SatAM)","Sonic Boom"],a:2,exp:"'Sonic the Hedgehog' (conocida como SatAM por emitirse los sábados por la mañana) fue la serie animada seria y dramática de Sonic de 1993-1994.",extra:"A diferencia de la otra serie 'Adventures of Sonic the Hedgehog' (más cómica), SatAM tenía un tono oscuro y fue muy bien recibida por los fans adultos."},
  {t:"f",q:"Sonic Underground (1999) es la serie animada donde Sonic tiene dos hermanos reales llamados Sonia y Manic que tocan instrumentos musicales.",o:["Verdadero","Falso"],a:0,exp:"Verdadero. En Sonic Underground, Sonic tiene dos hermanos perdidos: Sonia (que toca el teclado) y Manic (que toca la batería). Juntos forman una banda.",extra:"La serie tiene un estilo muy diferente a la SatAM, con muchos números musicales y una mitología propia sobre la madre de Sonic, la reina Aleena."},
  {t:"m",q:"¿Cómo se llama la forma final de Neo Metal Sonic en Sonic Heroes (2003)?",o:["Perfect Metal Sonic","Metal Madness / Metal Overlord","Robo Sonic","Mechanized Hedgehog"],a:1,exp:"En Sonic Heroes, Neo Metal Sonic se transforma primero en Metal Madness y luego en Metal Overlord, el jefe final del juego tras copiar los datos de todos.",extra:"Para derrotar a Metal Overlord solo puede usarse la versión Super de los tres equipos principales: Super Sonic, Super Shadow y Super Silver... en realidad Super Sonic, Super Tails y Super Knuckles."},
  {t:"m",q:"¿Qué tipo de juego de rol fue Sonic Chronicles: The Dark Brotherhood (2008)?",o:["JRPG de acción en tiempo real","RPG por turnos isométrico","Beat 'em up con elementos RPG","Estrategia por turnos"],a:1,exp:"Sonic Chronicles fue un RPG táctico por turnos desarrollado por BioWare para Nintendo DS, siendo el único RPG formal de Sonic en la saga principal.",extra:"Aunque fue recibido de forma tibia, fue notable por ser desarrollado por BioWare, el estudio conocido por Mass Effect y Dragon Age."},
  {t:"m",q:"¿Cuántas zonas acumulan en total Sonic 3 y Sonic & Knuckles cuando se conectan mediante Lock-On?",o:["10 zonas","14 zonas","18 zonas","12 zonas"],a:1,exp:"Sonic 3 & Knuckles combinado tiene 14 zonas: las 6 de Sonic 3 más las 8 de Sonic & Knuckles, formando la aventura completa que Sega originalmente planeaba.",extra:"La división en dos cartuchos fue consecuencia de las limitaciones de tiempo y presupuesto. La experiencia completa fue la visión original del equipo."},
  {t:"m",q:"¿Qué personaje de Sonic tiene el poder del hielo y actúa como guardia de Blaze the Cat en Sonic Rush Adventure?",o:["Freeze","Marine the Raccoon","Blizzard","Captain Whisker"],a:1,exp:"Marine the Raccoon es el personaje que Sonic y Tails conocen en la Sol Dimension en Sonic Rush Adventure (2007), siendo la guía local energética y parlanchina.",extra:"Marine no tiene poderes de hielo; el malentendido viene de su color. Captain Whisker es el antagonista pirata de Sonic Rush Adventure."},
  {t:"f",q:"Mighty the Armadillo y Ray the Flying Squirrel aparecieron originalmente en Knuckles' Chaotix (1995) antes de ser rescatados en Sonic Mania Plus.",o:["Verdadero","Falso"],a:0,exp:"Verdadero. Mighty y Ray son personajes de los 90: Mighty apareció en SegaSonic the Hedgehog Arcade y Chaotix; Ray en SegaSonic Arcade. Regresaron en Mania Plus.",extra:"Su regreso en Sonic Mania Plus fue muy celebrado por los fans, ya que ambos llevaban décadas sin aparecer en ningún juego oficial de Sonic."},
  {t:"m",q:"¿Cómo se llama el nivel de música nocturna en la Stardust Speedway de Sonic CD donde Sonic corre contra Metal Sonic?",o:["Robotnik's Base","Quartz Quadrant","Stardust Speedway Bad Future","La carrera de Metal Sonic"],a:3,exp:"La carrera de Metal Sonic en Stardust Speedway (Bad Future) es uno de los momentos más icónicos de Sonic CD: hay que ganar a Metal Sonic o Eggman mata a Amy.",extra:"Stardust Speedway tiene cuatro versiones temporales en Sonic CD: pasado, presente, buen futuro y mal futuro, cada una con diferente música y diseño."},
  {t:"m",q:"¿Qué objeto especial esconde cada zona de nivel en Sonic CD que permite liberar el buen futuro si se usa correctamente?",o:["Chaos Emeralds","Robot Generators y Hologramas de Metal Sonic","Time Stones","Power Rings"],a:1,exp:"En Sonic CD, destruir los Robot Generators y los Holograms de Metal Sonic en el pasado de cada zona es lo que crea el Buen Futuro al recolectarlos todos.",extra:"Alternativamente, conseguir las 7 Time Stones en las Special Stages también asegura el Buen Futuro para todas las zonas. Son los dos métodos válidos."},
  {t:"f",q:"Burning Blaze, la forma superpoderosa de Blaze the Cat, se activa recolectando las 7 Sol Emeralds de su dimensión.",o:["Verdadero","Falso"],a:0,exp:"Verdadero. Burning Blaze es la contraparte de Super Sonic en la Sol Dimension: Blaze necesita las 7 Sol Emeralds para transformarse.",extra:"En Sonic Rush, tanto Super Sonic como Burning Blaze son necesarios para el combate final cooperativo contra el jefe definitivo del juego."},

  // ── SONIC ADVANCE SERIES (GBA) ──────────────────────────────
  {t:"m",q:"¿Cuál fue el primer juego de Sonic lanzado para una consola de Nintendo (GBA)?",o:["Sonic Battle","Sonic Advance 2","Sonic Advance","Sonic Rush"],a:2,exp:"Sonic Advance (2001) para Game Boy Advance fue la primera vez que Sonic llegó a una consola portátil de Nintendo, marcando una histórica alianza entre SEGA y Nintendo.",extra:"Antes de Sonic Advance, SEGA y Nintendo eran rivales directos. La aparición de Sonic en hardware de Nintendo fue un hito para la industria."},
  {t:"m",q:"¿Qué personaje jugable nuevo fue introducido por primera vez en Sonic Advance 2 (GBA, 2002)?",o:["Marine the Raccoon","Blaze the Cat","Cream the Rabbit","Silver the Hedgehog"],a:2,exp:"Cream the Rabbit debutó en Sonic Advance 2 como personaje jugable, siendo la primera vez que aparecía en la saga. Vuela agitando sus grandes orejas.",extra:"Cream se convirtió en personaje recurrente: también apareció en Sonic Heroes, Sonic Battle, Sonic Rush y otros juegos posteriores."},
  {t:"m",q:"¿Qué sistema de juego especial tenía Sonic Advance 3 (GBA, 2004)?",o:["Turnos en batalla","Páreas de personajes con habilidades combinadas","Mundo abierto sin zonas","Modo historia con voces"],a:1,exp:"Sonic Advance 3 introdujo un sistema de parejas: el jugador elige dos personajes y su combinación determina las habilidades disponibles durante el nivel.",extra:"Hay 15 combinaciones posibles entre los 5 personajes (Sonic, Tails, Knuckles, Amy, Cream), cada una con una habilidad especial única."},
  {t:"m",q:"¿Cómo se llama el robot de combate de alta tecnología que el jugador puede entrenar en Sonic Battle (GBA, 2003)?",o:["Omega Mk-II","Mecha Sonic","Emerl the Gizoid","Battle Droid"],a:2,exp:"Emerl the Gizoid es el robot protagonista de Sonic Battle: puede copiar y aprender las técnicas de lucha de todos los personajes con los que entrena.",extra:"Emerl absorbe datos de las Chaos Emeralds y de sus rivales en combate. Su historia trágica lo convirtió en uno de los personajes más queridos de la GBA."},

  // ── SONIC AND THE SECRET RINGS / BLACK KNIGHT ────────────────
  {t:"m",q:"¿En qué mundo mítico está ambientado Sonic and the Secret Rings (2007)?",o:["La mitología griega","El Lejano Oeste","Las Mil y Una Noches (Arabian Nights)","La leyenda artúrica"],a:2,exp:"Sonic and the Secret Rings lleva al personaje al mundo de Las Mil y Una Noches, donde debe derrotar al Genio Maligno Erazor Djinn para salvar las historias.",extra:"El juego usa el control por movimiento del Wii Remote: se inclina para girar y se sacude para usar habilidades, siendo el primer Sonic para Wii."},
  {t:"m",q:"¿Cómo se llama la genio que acompaña y guía a Sonic a lo largo de Sonic and the Secret Rings?",o:["Shahra the Ring Genie","Leilani the Wish Genie","Aladdin's Djinn","Calypso"],a:0,exp:"Shahra es una genio del anillo atada a Erazor Djinn que se une a Sonic para detener a su antiguo amo, sacrificándose al final del juego.",extra:"La relación de Sonic y Shahra tiene un componente emotivo: su sacrificio al final para salvar a Sonic es uno de los momentos más recordados del juego."},
  {t:"m",q:"¿Cómo se llama la transformación de poder oscuro que obtiene Sonic al usar los World Rings en Secret Rings?",o:["Hyper Sonic","Flame Sonic","Darkspine Sonic","Void Sonic"],a:2,exp:"Darkspine Sonic es la forma de poder de Sonic en Secret Rings: absorbe tres World Rings negativos y gana una apariencia oscura con mayor velocidad y fuerza.",extra:"A diferencia de Super Sonic, Darkspine no usa Chaos Emeralds. Es la única forma de poder de Sonic fuera del universo de las Esmeraldas del Caos."},
  {t:"m",q:"¿En qué leyenda está ambientado Sonic and the Black Knight (2009)?",o:["Las mil y una noches","La mitología nórdica","El rey Arturo y los Caballeros de la Mesa Redonda","La Iliada"],a:2,exp:"Black Knight lleva a Sonic al mundo artúrico, donde debe enfrentarse al Rey Arturo corrompido y a los caballeros de la Mesa Redonda transformados en villanos.",extra:"Shadow aparece como Sir Lancelot, Knuckles como Sir Gawain y Blaze como Sir Percival, todos enfrentándose a Sonic en distintos puntos del juego."},
  {t:"m",q:"¿Cómo se llama la espada parlante que Sonic recibe al comienzo de Sonic and the Black Knight?",o:["Excalibur","Durandal","Caliburn","Fragarach"],a:2,exp:"Caliburn es una espada con espíritu propio que inicialmente menosprecia a Sonic por no ser un verdadero caballero, pero acaba reconociendo su valor.",extra:"Al final del juego, Caliburn se revela como la verdadera Excalibur. Sonic derrota al Rey Arturo oscuro y se convierte en el Caballero legendario."},
  {t:"m",q:"¿Qué personaje de Sonic aparece disfrazado del caballero Sir Percival en Black Knight?",o:["Amy Rose","Rouge the Bat","Blaze the Cat","Silver the Hedgehog"],a:2,exp:"Blaze the Cat aparece como Sir Percival, uno de los Caballeros de la Mesa Redonda que el jugador debe derrotar durante la aventura.",extra:"Su diseño como caballera de armadura combina la elegancia de Blaze con una estética medieval. Es uno de los jefes más dinámicos del juego."},

  // ── SONIC LOST WORLD ─────────────────────────────────────────
  {t:"m",q:"¿En qué consolas fue lanzado Sonic Lost World (2013) de forma exclusiva inicialmente?",o:["PS4 y Xbox One","PC y Nintendo Switch","Wii U y Nintendo 3DS","Solo Wii U"],a:2,exp:"Sonic Lost World fue un juego exclusivo de Nintendo al lanzamiento: Wii U para consola de sobremesa y 3DS para portátil, con versiones bastante diferentes.",extra:"Más adelante llegó a PC (Steam), pero la exclusividad con Nintendo duró varios años. El acuerdo reflejó la relación renovada entre SEGA y Nintendo."},
  {t:"m",q:"¿Cómo se llama la raza alienígena de los Deadly Six, los villanos de Sonic Lost World?",o:["Los Voidians","Los Zeti","Los Darkons","Los Nebulons"],a:1,exp:"Los Zeti son los seis seres que conforman los Deadly Six, originarios de Losteria (Lost Hex). Eggman los controlaba con una concha musical antes de que Sonic los liberara.",extra:"Al perder el control sobre ellos, los Zeti se vuelven contra Eggman y Sonic por igual, complicando la trama del juego."},
  {t:"m",q:"¿Quién lidera a los Deadly Six como el más poderoso y estratégico entre los Zeti?",o:["Zazz","Zor","Master Zik","Zavok"],a:3,exp:"Zavok es el líder de los Deadly Six: un Zeti rojo de gran tamaño que combina fuerza bruta con inteligencia táctica y se convierte en el villano principal del juego.",extra:"Zavok ha vuelto a aparecer en juegos posteriores como Sonic Forces y Team Sonic Racing, convirtiéndose en uno de los antagonistas secundarios recurrentes."},
  {t:"m",q:"¿Cómo se llama la única Zeti femenina de los Deadly Six en Sonic Lost World?",o:["Zelda","Zeena","Zara","Ziva"],a:1,exp:"Zeena es la Zeti femenina del grupo, de color verde, vanidosa y calculadora. A diferencia de los otros, no muestra interés en la pelea salvo que sea necesario.",extra:"Su diseño contrasta con los otros Deadly Six por ser más estilizado. En el cómic IDW de Sonic también apareció de forma breve."},

  // ── SONIC FORCES ─────────────────────────────────────────────
  {t:"m",q:"¿Cómo se llama el antagonista enmascarado nuevo que aparece en Sonic Forces (2017)?",o:["Mephiles","Null","Infinite","Eclipse"],a:2,exp:"Infinite es un mercenario felino que fue derrotado por Shadow y, al obtener el Phantom Ruby, adquirió poderes ilusorios devastadores que usó para servir a Eggman.",extra:"Su backstory de humillación y deseo de poder resonó con muchos fans. La canción 'Infinite' que acompaña su presentación es una de las más populares de Forces."},
  {t:"m",q:"¿Qué gema da sus poderes a Infinite en Sonic Forces, permitiéndole crear realidades ilusorias?",o:["Master Emerald","Phantom Ruby","Void Crystal","Null Space Gem"],a:1,exp:"El Phantom Ruby es una gema de origen desconocido con el poder de alterar la percepción de la realidad, haciendo que copias ilusorias parezcan completamente reales.",extra:"El Phantom Ruby también aparece en Sonic Mania como parte de la historia de los Hard Boiled Heavies, conectando ambos juegos de 2017."},
  {t:"m",q:"¿Cómo se llama el nuevo tipo de personaje completamente personalizable que el jugador puede crear en Sonic Forces?",o:["Rookie","The Avatar","Custom Hedgehog","Hero Recruit"],a:1,exp:"El Avatar (llamado 'Rookie' en el juego) es el personaje creado por el jugador: se elige la especie, el color y las armas Wire-type para combatir al ejército de Eggman.",extra:"Fue la primera vez que Sonic Team permitió a los fans jugar como su propio personaje OC en un juego principal de Sonic, lo que generó mucho entusiasmo online."},
  {t:"f",q:"En Sonic Forces (2017), Classic Sonic regresa como personaje jugable además del Sonic moderno y el Avatar.",o:["Verdadero","Falso"],a:0,exp:"Verdadero. Forces tiene tres estilos de juego: Sonic moderno (3D), Classic Sonic (2D side-scrolling) y el Avatar del jugador (cables y gadgets).",extra:"La presencia de Classic Sonic causó controversia: muchos fans sentían que diluyó la narrativa. Su rol en Forces fue menos celebrado que en Generations."},

  // ── SONIC BOOM ───────────────────────────────────────────────
  {t:"m",q:"¿Qué accesorio lleva Sonic como seña de identidad exclusiva del universo Sonic Boom (2014)?",o:["Gafas de sol","Guantes de combate","Una bufanda azul","Zapatillas con turbinas"],a:2,exp:"En Sonic Boom, Sonic lleva una bufanda/vendaje azul alrededor del torso, diferenciándolo visualmente del diseño clásico/moderno.",extra:"Knuckles también tiene un rediseño radical: es mucho más grande y musculoso. Amy tiene cabello más largo y usa ropa de aventurera en lugar de su vestido."},
  {t:"m",q:"¿Qué cambio físico drástico tiene Knuckles en el universo Sonic Boom comparado con su diseño habitual?",o:["Tiene cuatro puños","Es mucho más alto y musculoso","Sus pelos rojos son más largos","Usa armadura de metal"],a:1,exp:"En Sonic Boom, Knuckles es notablemente más grande y musculoso que en cualquier otro diseño, con un cuerpo casi el doble del tamaño habitual.",extra:"El rediseño generó muchos memes y reacciones mixtas. Dentro del universo Boom, Knuckles también es el personaje más torpe e ingenuo del grupo."},
  {t:"m",q:"¿Cómo se llama la isla ficticia donde transcurre la mayor parte de la acción en la serie animada Sonic Boom?",o:["South Island","Bygone Island","Angle Island","Flicky Island"],a:1,exp:"Bygone Island es el hogar de Sonic y sus amigos en Sonic Boom: una isla tropical con ruinas antiguas y la aldea donde viven junto a otros habitantes.",extra:"La villa es constantemente atacada por el Dr. Eggman, cuya base está también en la isla. La serie se distingue por su humor y parodia de los clichés de la franquicia."},
  {t:"m",q:"¿Cuál fue el juego de Sonic Boom más criticado negativamente al lanzarse en 2014?",o:["Sonic Boom: Shattered Crystal (3DS)","Sonic Boom: Fire & Ice (3DS)","Sonic Boom: Rise of Lyric (Wii U)","Sonic Boom: Team Racing"],a:2,exp:"Sonic Boom: Rise of Lyric (Wii U) fue muy criticado por sus graves bugs, caídas de framerate, controles defectuosos y diseño de niveles pobre.",extra:"El juego es frecuentemente citado como uno de los peores juegos de Sonic junto a Sonic 06. Los bugs de colisión y los glitches virales se volvieron memes."},

  // ── SONIC SUPERSTARS ─────────────────────────────────────────
  {t:"m",q:"¿En qué año se lanzó Sonic Superstars, el juego de estilo clásico con hasta 4 jugadores simultáneos?",o:["2021","2022","2023","2024"],a:2,exp:"Sonic Superstars se lanzó en octubre de 2023 para todas las plataformas principales. Es el primer juego clásico 2D oficial que soporta 4 jugadores en pantalla simultánea.",extra:"El juego fue desarrollado en colaboración con Arzest, el estudio de Naoto Ohshima (co-creador del diseño original de Sonic)."},
  {t:"m",q:"¿Cómo se llama la nueva personaje que aparece en Sonic Superstars (2023) y empieza como antagonista antes de unirse a Sonic?",o:["Surge the Tenrec","Honey the Cat","Trip the Sungazer","Shade the Echidna"],a:2,exp:"Trip the Sungazer es un nuevo personaje de Sonic Superstars: inicialmente sirve al Dr. Eggman, pero eventualmente cambia de bando y se vuelve jugable.",extra:"Trip es un gecko de cuello de abanico, el primero de su especie en la franquicia. Su arco de redención recuerda al de Gamma en SA1 o al de Blaze en Rush."},

  // ── IDW COMICS / ARCHIE COMICS ───────────────────────────────
  {t:"m",q:"¿En qué año comenzó la serie de cómics de Sonic publicada por IDW Publishing?",o:["2015","2016","2017","2018"],a:3,exp:"Los cómics de IDW Sonic comenzaron en abril de 2018, continuando la historia después de los eventos de Sonic Forces con personajes canónicos y nuevos.",extra:"La serie fue bien recibida por los fans por su escritura, arte y creación de personajes originales que respetan el espíritu de los juegos."},
  {t:"m",q:"¿Cómo se llama la erizo eléctrica creada en secreto por Eggman que actúa como antagonista en los cómics IDW de Sonic?",o:["Honey the Cat","Surge the Tenrec","Mina Mongoose","Fiona Fox"],a:1,exp:"Surge the Tenrec (un equidna de dedos tenrec) fue diseñada por Eggman como alternativa a Sonic: veloz y con poderes eléctricos, con una historia trágica de origen.",extra:"Surge y su compañero Kit the Fennec son los personajes originales más populares de los IDW Comics, con fuerte demanda de los fans para aparecer en juegos."},
  {t:"m",q:"¿Cómo se llamaba el virus que Eggman usó en los cómics IDW de Sonic para crear un ejército de 'Zombots'?",o:["El Nano Plague","El Metal Virus","El Cyber Infection","El Dark Plague"],a:1,exp:"El Metal Virus fue un arco narrativo importante en los IDW Comics: Eggman creó un nanite-virus que convertía a los infectados en Zombots (zombies robóticos).",extra:"Sonic mismo fue infectado y tuvo que seguir moviéndose para retardar la propagación. El arco duró varios meses y involucró a casi todos los personajes."},
  {t:"m",q:"¿Cómo se llama la princesa ardilla que era el interés amoroso de Sonic y líder de los Freedom Fighters en los cómics de Archie Comics?",o:["Mina Mongoose","Fiona Fox","Sally Acorn","Bunnie Rabbot"],a:2,exp:"Sally Acorn (Princesa Sally Alicia Acorn) era el personaje femenino principal de Archie Sonic, líder de los Freedom Fighters y compañera inseparable de Sonic.",extra:"Sally nunca apareció en los juegos principales, siendo un personaje exclusivo de medios alternativos (SatAM, Archie). Tiene seguidores muy devotos hasta hoy."},
  {t:"m",q:"¿Cómo se llama el mundo donde viven los personajes en el universo de los cómics de Archie Sonic?",o:["Sonictopia","Mobius","Sonic World","Planet Freedom"],a:1,exp:"En los cómics de Archie, el mundo se llama Mobius, un planeta futurista donde animales antropomórficos y humanos coexisten.",extra:"Mobius tenía una historia rica y compleja en los cómics, con continentes, países, historia política y personajes que nunca aparecieron en los juegos."},

  // ── VOCES Y MÚSICA ───────────────────────────────────────────
  {t:"m",q:"¿Qué músico japonés, integrante del grupo Dreams Come True, compuso la banda sonora de Sonic 1 y Sonic 2?",o:["Jun Senoue","Yuji Naka","Masato Nakamura","Naofumi Hataya"],a:2,exp:"Masato Nakamura del grupo japonés Dreams Come True compuso la música de Sonic 1 (1991) y Sonic 2 (1992), dándoles su icónico sonido pop-rock.",extra:"Dreams Come True es una banda pop japonesa muy conocida. La conexión con SEGA fue única; desde Sonic 3 en adelante el compositor principal pasó a ser Jun Senoue."},
  {t:"m",q:"¿Quién ha sido el actor de doblaje inglés de Sonic desde Sonic Colors (2010) hasta la actualidad?",o:["Jason Griffith","Ryan Drummond","Roger Craig Smith","Martin Burke"],a:2,exp:"Roger Craig Smith tomó el rol de Sonic a partir de 2010 con Sonic Colors y sigue siendo la voz inglesa del personaje hasta el presente.",extra:"Roger Craig Smith es también conocido por doblar a Chris Redfield (Resident Evil), Ezio Auditore (Assassin's Creed) y muchos otros personajes icónicos."},
  {t:"m",q:"¿Quién fue el actor de doblaje inglés de Sonic durante el período 2005-2010 (desde Shadow the Hedgehog hasta Sonic & Sega All-Stars Racing)?",o:["Ryan Drummond","Jason Griffith","Martin Burke","Pete Capella"],a:1,exp:"Jason Griffith fue la voz inglesa de Sonic durante 5 años, también doblando a Shadow. Fue reemplazado por Roger Craig Smith en 2010.",extra:"Su versión de Sonic fue la de la era oscura (06, Secret Rings, Unleashed) y algunos fans lo recuerdan con afecto por las series 4Kids como Sonic X."},
  {t:"m",q:"¿Quién fue el primer actor de doblaje inglés de Sonic en los juegos 3D, comenzando en Sonic Adventure (1998)?",o:["Jason Griffith","Roger Craig Smith","Ryan Drummond","David Humphrey"],a:2,exp:"Ryan Drummond fue la primera voz inglesa de Sonic en los juegos 3D, desde SA1 (1998) hasta Sonic Heroes (2003), dando la voz enérgica y carismática del personaje.",extra:"Ryan Drummond también doblaba a otros personajes como Tails en SA2. Su voz fue muy querida por los fans de la era Dreamcast."},
  {t:"m",q:"¿Quién es el actor de doblaje japonés de Sonic the Hedgehog desde Sonic Adventure (1998) hasta hoy, sin cambios en décadas?",o:["Takehito Koyasu","Junichi Kanemaru","Daisuke Ono","Mamoru Miyano"],a:1,exp:"Junichi Kanemaru ha sido la voz japonesa de Sonic sin interrupción desde SA1 en 1998, convirtiéndose en uno de los dobladores más icónicos del personaje.",extra:"A diferencia de la versión inglesa con varios cambios, Japón ha tenido una sola voz para Sonic durante más de 25 años, lo que da más consistencia al personaje."},
  {t:"m",q:"¿Qué canción interpreta la banda Cash Cash y es el tema principal de Sonic Colors (2010)?",o:["Endless Possibility","Fist Bump","Reach for the Stars","Colors of the Wind"],a:2,exp:"'Reach for the Stars' de Cash Cash es el tema principal de Sonic Colors, con una letra positiva y enérgica sobre superar limitaciones.",extra:"La banda sonora de Colors fue muy celebrada, especialmente el tema de la zona Asteroid Coaster y la música electrónica de los niveles de Wisps."},
  {t:"m",q:"¿Qué canción de Jaret Reddick (Bowling for Soup) sirve como tema principal de Sonic Unleashed (2008)?",o:["Reach for the Stars","Endless Possibility","Fist Bump","Un-gravitify"],a:1,exp:"'Endless Possibility' de Jaret Reddick es el anthem de Sonic Unleashed, con una letra sobre no rendirse ante las adversidades.",extra:"La canción en japonés tiene letra diferente. En Unleashed se usa en la apertura y final del juego, representando el espíritu del personaje."},
  {t:"m",q:"¿Cómo se llama el compositor principal responsable de la banda sonora de Sonic Mania (2017)?",o:["Jun Senoue","Masato Nakamura","Tee Lopes","Tomoya Ohtani"],a:2,exp:"Tee Lopes compuso la banda sonora de Sonic Mania, combinando el estilo retro de los clásicos con arreglos modernos y temas originales.",extra:"Tee Lopes saltó de ser fan (hacía remixes de Sonic en YouTube) a compositor oficial, siendo descubierto por el equipo de Mania gracias a su talento."},

  // ── SONIC RIDERS ─────────────────────────────────────────────
  {t:"m",q:"¿Cuántas entregas tiene la serie Sonic Riders en total?",o:["2 juegos","3 juegos","4 juegos","Solo 1 juego"],a:1,exp:"La serie Sonic Riders tiene 3 juegos: Sonic Riders (2006), Sonic Riders: Zero Gravity (2008) y Sonic Free Riders (2010).",extra:"Los tres juegos giran en torno a las carreras con Extreme Gear, tablas de levitación futuristas, y al Equipo Babylon (Jet, Wave y Storm)."},
  {t:"m",q:"¿Qué periférico de control especial requería Sonic Free Riders (2010) para ser jugado?",o:["PlayStation Move","Wii Remote Plus","Kinect para Xbox 360","DualSense con háptica"],a:2,exp:"Sonic Free Riders fue diseñado exclusivamente para Kinect, el periférico sin controlador de Xbox 360 que detecta el movimiento del cuerpo.",extra:"El juego requería que el jugador se inclinara, balanceara y gesticulara para controlar el Extreme Gear. Las críticas fueron mixtas por los controles imprecisos."},
  {t:"m",q:"¿Cómo se llaman los dispositivos de tabla voladora que usan los personajes en la serie Sonic Riders?",o:["Hover Boards","Sky Skates","Extreme Gear","Chaos Boards"],a:2,exp:"Los Extreme Gear son los vehículos de levitación que usan los corredores en Sonic Riders: tablas, motos y esquís anti-gravedad de alta velocidad.",extra:"Hay tres tipos de Extreme Gear: Boards (tablas), Skates (patines) y Bikes (motos). Jet the Hawk usa una tabla personalizada llamada 'Type-J'."},
  {t:"m",q:"¿Quiénes son los otros dos integrantes de Team Babylon, el equipo de Jet the Hawk en Sonic Riders?",o:["Silver y Blaze","Rouge y Omega","Wave the Swallow y Storm the Albatross","Espio y Charmy"],a:2,exp:"Team Babylon está formado por Jet the Hawk (líder), Wave the Swallow (mecánica experta en Gear) y Storm the Albatross (músculo y fuerza).",extra:"Wave es considerada más inteligente que Tails en mecánica de Extreme Gear, mientras que Storm tiene una rivalidad con Knuckles muy marcada."},

  // ── TEAM SONIC RACING ────────────────────────────────────────
  {t:"m",q:"¿Qué mechanic diferencia a Team Sonic Racing (2019) de un juego de karts convencional?",o:["Permite chocar sin daño","Los equipos de 3 colaboran con slipstream y power-ups compartidos","Usa realidad aumentada","Tiene físicas de simulación"],a:1,exp:"En Team Sonic Racing, los tres miembros del equipo deben cooperar: compartir potenciadores, hacer slipstream para darse velocidad y llegar juntos.",extra:"Ganar requiere que el equipo termine bien en conjunto, no solo que un miembro llegue primero. Es una mecánica inusual y cooperativa para el género."},

  // ── LORE: CHAOS, TIKAL, EGGMAN ───────────────────────────────
  {t:"m",q:"¿Qué es Chaos, el ser que Eggman libera absorbiendo Esmeraldas del Caos en Sonic Adventure 1?",o:["Un robot antiguo de Gerald","Un alien del espacio","El dios protector de los Chao formado de agua","Un equidna mutado"],a:2,exp:"Chaos es un ser acuático inmortal que evolucionó de un Chao antiguo. En el pasado protegió a los Chao de los humanos y fue sellado en la Master Emerald por Tikal.",extra:"Chaos tiene 7 formas según cuántas Esmeraldas absorba (Chaos 0, 1, 2, 4, 6, Perfect Chaos). En su forma perfecta puede destruir ciudades enteras."},
  {t:"m",q:"¿Quién es Tikal the Echidna y cuál es su relación con Knuckles?",o:["La madre de Knuckles","Un fantasma del pasado del clan Knuckles y posible ancestro","La reina de Angel Island","Una científica que creó la Master Emerald"],a:1,exp:"Tikal es el espíritu de una echidna del pasado cuyo clan guardaba la Master Emerald. Su alma quedó atrapada dentro de la piedra junto a Chaos.",extra:"Tikal era pacifista y se opuso a su padre Pachacamac cuando este atacó el altar de los Chao para robar las Esmeraldas, lo que desencadenó la ira de Chaos."},
  {t:"m",q:"¿Cuál es el coeficiente intelectual (IQ) canónico del Dr. Eggman según la franquicia?",o:["200","250","300","400"],a:2,exp:"El Dr. Eggman tiene un IQ canónico de 300, lo que lo hace uno de los villanos más inteligentes de los videojuegos, pese a sus constantes fracasos ante Sonic.",extra:"Su genialidad contrasta cómicamente con su incapacidad de derrotar definitivamente a Sonic. Es capaz de construir flotas enteras pero pierde ante un erizo."},
  {t:"m",q:"¿Cómo se llama el arma orbital de la Space Colony ARK que Eggman usa para amenazar al mundo en Sonic Adventure 2?",o:["Chaos Cannon","ARK Beam","Death Egg Laser","Eclipse Cannon"],a:3,exp:"El Eclipse Cannon es un arma capaz de destruir la luna. Gerald Robotnik lo construyó en la ARK hace 50 años; Eggman lo reactiva usando las Esmeraldas del Caos.",extra:"En el clímax de SA2, el Eclipse Cannon es reprogramado por el Professor Gerald para destruir la Tierra como venganza contra los que lo encarcelaron."},
  {t:"m",q:"¿Cómo se llama el jefe final verdadero de Sonic Adventure 1, la forma perfecta del ser acuático tras absorber las 7 Esmeraldas?",o:["Chaos Supreme","Aqua Titan","Perfect Chaos","Hydra God"],a:2,exp:"Perfect Chaos es la forma final del antagonista de SA1: un monstruo acuático gigantesco que inunda Station Square y destruye edificios enteros.",extra:"Super Sonic lo derrota en el clímax del juego absorbiendo la energía positiva de las Esmeraldas. La batalla es acrobática y puramente de velocidad."},
  {t:"m",q:"¿Cómo se llama la fusión del Biolizard con la Space Colony ARK que se convierte en el jefe final de Sonic Adventure 2?",o:["ARK Prime","Finalhazard","Chaos Prime","Metal Biolizard"],a:1,exp:"Finalhazard es la fusión del Biolizard con toda la estructura de la ARK: un monstruo orgánico-mecánico que intenta hacer chocar la estación contra la Tierra.",extra:"Es derrotado por Super Sonic y Super Shadow en el espacio exterior. La escena de Shadow usando Chaos Control para teletransportar la ARK es icónica."},

  // ── SONIC ADVENTURE 2: DETALLES ──────────────────────────────
  {t:"m",q:"¿Cómo se llama el primer nivel de Sonic en Sonic Adventure 2, donde huye de los militares en una tabla de snowboard?",o:["Metal Harbor","Radical Highway","Pumpkin Hill","City Escape"],a:3,exp:"City Escape es el primer nivel de Sonic en SA2 y uno de los más icónicos de la saga: Sonic esquiva un camión militar sobre una tabla improvisada.",extra:"La escena de Sonic deslizándose sobre el camión se convirtió en meme y referencia cultural. La canción 'E.G.G.M.A.N.' también fue lanzada en este nivel."},
  {t:"m",q:"¿Qué tres estilos de gameplay ofrece Sonic Adventure 2 para sus seis personajes jugables?",o:["Plataformas/vuelo/natación","Velocidad/mechas de disparo/rastreo de objetos","RPG/acción/sigilo","Carreras/lucha/exploración"],a:1,exp:"SA2 tiene tres gameplays: velocidad (Sonic/Shadow), mechas de disparo (Tails/Eggman) y rastreo de objetos con radar (Knuckles/Rouge).",extra:"La variedad fue bien recibida pero los modos de rastreo fueron los más criticados. Buscar fragmentos en niveles enormes podía volverse tedioso."},
  {t:"m",q:"¿Cómo se llama el mech robot que Tails pilota en su modo de juego en Sonic Adventure 2?",o:["Gamma Mk-II","Tornado EX","Cyclone","Mech Tornado"],a:2,exp:"El Cyclone es el mech bípedo de Tails, equipado con lanzamientos y misiles. En SA2, Tails pilota el Cyclone en todos sus niveles en lugar de combatir a pie.",extra:"El Cyclone puede transformarse en un tanque para ciertos jefes. Eggman usa un mech similar llamado Eggwalker. Ambos tienen el mismo gameplay de disparo."},

  // ── SONIC 06 Y SILVER ─────────────────────────────────────────
  {t:"m",q:"¿Cómo se llama el ser oscuro y malicioso nacido de una mitad del dios Solaris en Sonic the Hedgehog (2006)?",o:["Iblis","Mephiles the Dark","Dark Gaia","Void"],a:1,exp:"Mephiles the Dark es la consciencia y voluntad de Solaris: un ser de pura oscuridad que manipula a Silver desde el futuro para desencadenar su propia liberación.",extra:"Mephiles es uno de los antagonistas más queridos de la saga por su inteligencia, paciencia y aspecto visual único. No tiene boca y expresa todo con sus ojos."},
  {t:"m",q:"¿Por qué Silver the Hedgehog viajó desde el futuro para buscar al 'Iblis Trigger' en Sonic the Hedgehog (2006)?",o:["Para robar las Esmeraldas del Caos","Para salvar a Amy Rose","Para eliminar al responsable de liberar a Iblis y destruir su futuro apocalíptico","Para derrotar a Eggman"],a:2,exp:"Silver viene de un futuro en llamas dominado por Iblis. Mephiles lo manipuló haciéndole creer que Sonic era el 'Iblis Trigger' que desencadenaría el apocalipsis.",extra:"Silver persigue a Sonic durante todo el juego hasta que descubre la verdad. Su arco lo llevó de antagonista a héroe al entender que Mephiles lo engañó."},
  {t:"m",q:"¿Qué fue Solaris, el antagonista definitivo de Sonic the Hedgehog (2006)?",o:["Un robot de Eggman del futuro","El dios del tiempo del reino de Soleanna, dividido en Mephiles e Iblis","Un alien de otra dimensión","Shadow evolucionado al máximo"],a:1,exp:"Solaris era la deidad del tiempo venerada por el reino de Soleanna. Un experimento del Duke of Soleanna lo dividió en Mephiles (mente) e Iblis (poder destructor).",extra:"Para borrarlo de la existencia, Sonic, Shadow y Silver lo derrotan juntos como Supers, y luego Sonic y Elise apagan la llama de Solaris en el pasado."},

  // ── ZONES CLÁSICAS ────────────────────────────────────────────
  {t:"m",q:"¿Cómo se llama la zona de refinería de petróleo en Sonic the Hedgehog 2 con plataformas sobre líquido viscoso amarillo?",o:["Chemical Lagoon","Aqua Ruin","Oil Ocean Zone","Petroleum Panic"],a:2,exp:"Oil Ocean Zone en Sonic 2 es la novena zona, ambientada en una refinería de petróleo con plataformas flotantes sobre el líquido y enemigos robóticos inspirados en maquinaria industrial.",extra:"Su paleta de colores naranja-marrón y el ambiente industrial la hacen una de las zonas más visualmente distintas de Sonic 2."},
  {t:"m",q:"¿Cuál es la única zona de Sonic the Hedgehog 2 que tiene tres actos en lugar de los dos habituales?",o:["Chemical Plant Zone","Death Egg Zone","Casino Night Zone","Metropolis Zone"],a:3,exp:"Metropolis Zone en Sonic 2 tiene 3 actos, siendo la zona más larga del juego. Es la penúltima zona antes de Sky Chase y Wing Fortress.",extra:"Muchos fans recuerdan Metropolis Zone como una de las más desafiantes de Sonic 2, con enemigos que se agarran a Sonic y laberintos de tuberías confusos."},
  {t:"m",q:"¿Cómo se llama la zona final antes de la Death Egg en Sonic the Hedgehog 1 (1991)?",o:["Star Light Zone","Marble Zone","Scrap Brain Zone","Crystal Egg Zone"],a:2,exp:"Scrap Brain Zone es la sexta y penúltima zona de Sonic 1: una fábrica industrial llena de trampas eléctricas, ventiladores y maquinaria peligrosa.",extra:"El acto 3 de Scrap Brain es en realidad una versión diferente de Labyrinth Zone inundada, siendo una trampa de Eggman antes del enfrentamiento final."},
  {t:"m",q:"¿Cómo se llama la zona de Sonic 3 con temática de carnaval que tiene el infame barril rompecabezas que muchos jugadores no sabían mover?",o:["Casino Night Zone","Circus Park","Carnival Night Zone","Funfair Factory"],a:2,exp:"Carnival Night Zone en Sonic 3 tiene un barril en su Acto 2 que solo avanza si el jugador presiona arriba o abajo mientras está dentro (muchos no lo sabían).",extra:"El barril se convirtió en uno de los mayores memes de Sonic: muchos jugadores quedaron bloqueados días sin saber cómo avanzar, antes de internet."},
  {t:"m",q:"¿Cómo se llama la zona acuática de Sonic 3 donde el jugador puede aprovechar las corrientes de turbinas para ganar velocidad?",o:["Aquatic Ruin","Tidal Tempest","Hydrocity Zone","Water Palace Zone"],a:2,exp:"Hydrocity Zone (Acto 2) en Sonic 3 es memorada por sus espirales de agua y turbinas. Es una de las zonas acuáticas más dinámicas de toda la saga.",extra:"A diferencia de Labyrinth Zone en Sonic 1, Hydrocity se siente veloz incluso bajo el agua. Su música es considerada una de las mejores de Sonic 3."},

  // ── SONIC ADVENTURE 1 DETALLES ────────────────────────────────
  {t:"m",q:"¿Cómo se llama la ciudad costera hub world de Sonic Adventure 1, inspirada en una metrópolis americana?",o:["Angel Island","Pumpkin Hill","Station Square","Mystic Ruins"],a:2,exp:"Station Square es la ciudad hub principal de SA1: una metrópolis al estilo americano con un hotel, una tienda, una estación de tren y acceso a los niveles.",extra:"En el clímax del juego, Perfect Chaos inunda Station Square casi por completo. Su destrucción y reconstrucción marcan el arco narrativo principal del juego."},
  {t:"m",q:"¿Cuántos personajes son jugables con su propia historia individual en Sonic Adventure 1?",o:["4 personajes","5 personajes","6 personajes","8 personajes"],a:2,exp:"SA1 tiene 6 historias independientes: Sonic, Tails, Knuckles, Amy, Big the Cat y E-102 Gamma, cada una desde una perspectiva diferente del mismo evento.",extra:"Las historias se cruzan e intersectan. Ver todos los puntos de vista fue el primer experimento narrativo ambicioso de Sonic Team en un juego 3D."},
  {t:"m",q:"¿Cuál es el primer nivel de Sonic en Sonic Adventure 1?",o:["Speed Highway","Windy Valley","Emerald Coast","Twinkle Park"],a:2,exp:"Emerald Coast es el primer nivel de Sonic en SA1: una zona costera con playas, ruinas y un orca gigante que persigue a Sonic en una sección de agua.",extra:"Emerald Coast estableció el estilo de los niveles de velocidad de SA1. La persecución del orca es una de las primeras imágenes icónicas del juego."},

  // ── SONIC UNLEASHED ──────────────────────────────────────────
  {t:"m",q:"¿Cómo se llama la forma monstruosa y poderosa que Sonic adopta durante la noche en Sonic Unleashed (2008)?",o:["Darkspine Sonic","Shadow Sonic","Werehog","Night Sonic"],a:2,exp:"El Werehog es la forma nocturna de Sonic en Unleashed: similar a un hombre lobo, con brazos extensibles y combate cuerpo a cuerpo en lugar de velocidad.",extra:"El gameplay del Werehog fue el más divisivo de Unleashed: muchos fans lo veían como un desvío del estilo Sonic. Otros lo encontraron entretenido y narrativo."},
  {t:"m",q:"¿En cuántas regiones/continentes del mundo transcurren los niveles de Sonic Unleashed?",o:["4 regiones","6 regiones","8 regiones","10 regiones"],a:2,exp:"Sonic Unleashed tiene 8 regiones del mundo con inspiración geográfica real: Apotos (Grecia), Mazuri (África), Spagonia (Europa), Chun-nan (China) y más.",extra:"Cada región tiene un templo de la Tierra que Sonic debe restaurar como Werehog de noche y explorar con velocidad de día. El diseño artístico fue muy elogiado."},

  // ── SONIC GENERATIONS ────────────────────────────────────────
  {t:"m",q:"¿Cómo se llama el espacio vacío y decolorado que sirve de hub world en Sonic Generations (2011)?",o:["Blank Space","Null Dimension","White Space","Time Void"],a:2,exp:"White Space es el hub world de Generations: un espacio en blanco donde los recuerdos de Sonic están atrapados como murales decolorados por el Time Eater.",extra:"A medida que Sonic rescata a sus amigos y desbloquea niveles, el White Space se va llenando de color. Es una metáfora visual de recuperar el pasado."},
  {t:"m",q:"¿Quién es el villano de Sonic Generations que devora el tiempo y borra los recuerdos?",o:["Mephiles","The End","Time Eater","Infinite"],a:2,exp:"El Time Eater es una entidad poderosa que manipulan el Eggman presente y el Classic Eggman juntos para dominar el espacio-tiempo.",extra:"El Time Eater convierte los momentos del pasado de Sonic en niveles blancos y apagados. Su derrota requiere la cooperación de Sonic clásico y moderno."},

  // ── SONIC THE HEDGEHOG 4 / JUEGOS DESCARGABLES ───────────────
  {t:"m",q:"¿En qué año se lanzó Sonic the Hedgehog 4: Episode I como juego digital descargable?",o:["2008","2009","2010","2012"],a:2,exp:"Sonic 4: Episode I se lanzó en 2010 para PS3, Xbox 360 y Wii como descarga digital, posicionándose como sucesor espiritual de los clásicos de Mega Drive.",extra:"El Episode II (2012) añadió a Tails como compañero y a Metal Sonic como antagonista, pero tampoco logró convencer completamente a los fans de los clásicos."},
  {t:"m",q:"¿Cuál fue la crítica más común de los fans hacia la física de Sonic the Hedgehog 4?",o:["Era demasiado rápido","La física era 'flotante' y no se sentía como los juegos de Mega Drive","Los niveles eran demasiado cortos","No tenía música original"],a:1,exp:"La física 'pesada' o 'flotante' de Sonic 4 fue la queja principal: el personaje no tenía el mismo peso e inercia que en los juegos clásicos de Mega Drive.",extra:"Esta física fue comparada desfavorablemente con los originales muchas veces. Sonic Mania (2017) fue finalmente el regreso clásico que los fans esperaban."},

  // ── SONIC COLORS ULTIMATE / PELÍCULAS ────────────────────────
  {t:"m",q:"¿En qué año se lanzó Sonic Colors: Ultimate, la versión remasterizada de Sonic Colors?",o:["2019","2020","2021","2022"],a:2,exp:"Sonic Colors: Ultimate se lanzó en septiembre de 2021 para Nintendo Switch, PS4, Xbox One y PC, con gráficos mejorados y nuevas características.",extra:"La versión Ultimate tuvo problemas técnicos al lanzamiento en algunas plataformas, con bugs que los fans señalaron en comparación con el original de Wii."},
  {t:"m",q:"¿Quién actúa como personaje humano protagonista Tom Wachowski en las películas de acción real de Sonic?",o:["Dwayne Johnson","John Cena","Chris Pratt","James Marsden"],a:3,exp:"James Marsden interpreta a Tom Wachowski, el sheriff del pueblo de Green Hills que se convierte en el protector y amigo de Sonic en las películas.",extra:"James Marsden es conocido por su rol en X-Men (Cyclops) y Westworld. Su química con el Sonic animado fue uno de los puntos más elogiados de la película."},
  {t:"m",q:"¿Quién interpreta a Maddie, la esposa veterinaria de Tom en las películas de Sonic?",o:["Zendaya","Tika Sumpter","Sanaa Lathan","Awkwafina"],a:1,exp:"Tika Sumpter interpreta a Maddie Wachowski, la veterinaria que también termina ayudando a Sonic. Su conocimiento médico resulta útil para el personaje.",extra:"En la película de 2022, Maddie tiene un papel más activo en la trama. Su hermana Rachel (Natasha Rothwell) es uno de los personajes cómicos más populares."},
  {t:"m",q:"¿En qué pequeño pueblo de Montana vive Sonic escondido al inicio de la película Sonic the Hedgehog (2020)?",o:["Bozeman","Green Valley","Green Hills","Blue Ridge"],a:2,exp:"Green Hills es el pueblo ficticio de Montana donde Sonic vivió en secreto durante años, observando a los habitantes desde la distancia.",extra:"Green Hills es la versión del universo fílmico de 'Green Hill Zone'. El Easter egg es deliberado y fue celebrado por los fans del juego original."},
  {t:"m",q:"¿Quién da voz a Tails en las películas de acción real de Sonic (2022 y 2024)?",o:["Tara Strong","Andrea Libman","Colleen Villard","Veronica Taylor"],a:2,exp:"Colleen Villard (también conocida como Colleen O'Shaughnessey) da voz a Tails, siendo la misma actriz que lo dobla en los juegos desde Sonic Boom (2014).",extra:"Colleen Villard reemplazó a Kate Higgins como voz de Tails en los juegos y continuó en las películas, dando consistencia al personaje en todos los medios."},
  {t:"m",q:"¿Quién da voz a Knuckles en las películas de Sonic (2022 y 2024)?",o:["Idris Elba","Chiwetel Ejiofor","Daniel Kaluuya","Michael B. Jordan"],a:0,exp:"Idris Elba da voz a Knuckles en las películas, con un registro grave y solemne que encaja con el personaje serio y guerrero que representa.",extra:"Knuckles también tuvo su propia serie de TV en Paramount+, seguida de la película de Sonic 2, donde Idris Elba repitió el papel con su característico tono épico."},

  // ── SONIC ARCADE / PLATAFORMAS ESPECIALES ────────────────────
  {t:"m",q:"¿Cómo se llama el juego arcade de Sonic de 1993 que usaba un joystick de tipo trackball y permitía jugar con Sonic, Mighty y Ray?",o:["Sonic Spinball Arcade","SegaSonic the Hedgehog","Sonic the Fighters","Sonic Championship"],a:1,exp:"SegaSonic the Hedgehog (1993) fue un arcade exclusivo que usaba trackball para mover a los personajes y fue el debut de Mighty the Armadillo.",extra:"SegaSonic nunca tuvo un lanzamiento doméstico oficial y solo apareció en Japón. Es uno de los juegos de Sonic más raros y difíciles de conseguir."},
  {t:"m",q:"¿En qué periférico de expansión de la Mega Drive se lanzó Knuckles' Chaotix (1995)?",o:["Mega CD","SEGA 32X","Game Gear","Nomad"],a:1,exp:"Knuckles' Chaotix fue lanzado para el SEGA 32X, el accesorio de 32 bits que se conectaba a la Mega Drive. Es uno de los pocos juegos exclusivos del 32X.",extra:"El juego presenta a Knuckles y a los Chaotix (Espio, Charmy, Vector, Mighty) unidos por una liga elástica que es la mecánica central del juego."},
  {t:"m",q:"¿Qué mecánica de movimiento especial caracteriza a Knuckles' Chaotix, donde dos personajes están siempre conectados?",o:["Una cuerda magnética","Una liga elástica que los mantiene juntos","Un portal dimensional compartido","Un hilo de Caos"],a:1,exp:"En Chaotix, Knuckles y su compañero están conectados por una liga/resorte: si se separan demasiado, se jalan mutuamente. La tensión crea plataformas especiales.",extra:"La mecánica fue innovadora pero también frustrante para algunos jugadores. El AI del compañero podía dificultar el avance si no se controlaba bien."},
  {t:"m",q:"¿Cómo se llama el juego de carreras de Sonic para SEGA Saturn y PC lanzado en 1996?",o:["Sonic GP","Sonic Drift 2","Sonic R","Sonic Speed Racers"],a:2,exp:"Sonic R (1996) es un juego de carreras en perspectiva 3D para Saturn/PC donde los personajes corren a pie. Tiene 5 pistas y canciones pop que se volvieron icónicas.",extra:"Las canciones de Sonic R ('Can You Feel the Sunshine?', 'Living in the City') se volvieron muy queridas/odiadas por partes iguales y son un meme cultural."},
  {t:"m",q:"¿Cómo se llama la icónica canción pop de la banda sonora de Sonic R que se convirtió en meme de internet?",o:["Living in the City","Back in Time","Can You Feel the Sunshine?","Number One"],a:2,exp:"'Can You Feel the Sunshine?' de TJ Davis es la canción de apertura de Sonic R, conocida por su melodía pegadiza y letra optimista que contrasta con la intensidad de una carrera.",extra:"Las canciones de Sonic R, aunque inicialmente burladas, tienen hoy un enorme culto. 'Can You Feel the Sunshine?' es citada frecuentemente en listas de canciones de videojuegos."},
  {t:"m",q:"¿Cómo se llama el personaje de Sonic R que se convirtió en leyenda de terror de internet, conocido por su diseño perturbador?",o:["Evil Amy","Dark Egg Robo","Tails Doll","Metal Knuckles Ghost"],a:1,exp:"Tails Doll es un robot con forma de peluche de Tails que aparece como personaje secreto en Sonic R. Su diseño inusual lo convirtió en protagonista de cuentos de terror de internet.",extra:"'The Tails Doll Curse' fue una de las primeras leyendas urbanas de internet vinculadas a un videojuego. Su rareza en el juego potencia la mitología alrededor del personaje."},

  // ── SHADOW THE HEDGEHOG (2005) ────────────────────────────────
  {t:"m",q:"¿Cuántos finales diferentes tiene Shadow the Hedgehog (2005) dependiendo de las elecciones del jugador?",o:["3 finales","5 finales","10 finales","22 finales posibles"],a:2,exp:"Shadow the Hedgehog (2005) tiene 10 finales distintos según las decisiones Hero/Dark que el jugador tome, más un final 'verdadero' que los une a todos.",extra:"El juego propone un árbol de decisiones moral en cada misión: apoyar a G.U.N., a los Black Arms o a ninguno. Cada combinación lleva a un final diferente."},

  // ── SONIC FRONTIERS DETALLES ──────────────────────────────────
  {t:"m",q:"¿Cómo se llama el sistema de mundo abierto que introdujo Sonic Frontiers (2022)?",o:["Open Zone","Free Zone","Cyber Space","Star Zone"],a:0,exp:"El Open Zone es la nueva filosofía de diseño de Sonic Frontiers: islas enormes para explorar libremente, con combate, plataformas, puzzles y cinemáticas.",extra:"Frontiers es el primer Sonic en adoptar el formato de mundo abierto tipo sandbox, siendo la mayor innovación estructural de la saga en muchos años."},
  {t:"m",q:"¿Cómo se llama la entidad cósmica y antagonista definitiva de Sonic Frontiers?",o:["Sage","The Dark Master","The End","Infinite Prime"],a:2,exp:"The End es el antagonista definitivo de Sonic Frontiers: una entidad nihilista de proporciones cósmicas que busca el fin de toda existencia.",extra:"The End entra al planeta a través de Sage (la IA de Eggman) y posee a los titanes. Su filosofía de extinción contrasta directamente con el espíritu optimista de Sonic."},

  // ── PREGUNTAS FINALES 200 ────────────────────────────────────
  {t:"m",q:"¿Cómo se llama el juego de pinball de Sonic lanzado en 1993 para Mega Drive/Genesis donde Sonic actúa como bola de pinball?",o:["Sonic Pop","Sonic Spinball","Sonic Flipper","Sonic Pinball Party"],a:1,exp:"Sonic Spinball (1993) es un juego de pinball donde Sonic rueda por tableros gigantes llenos de bumpers, rampas y minijefes dentro de la fábrica de Eggman.",extra:"Sonic Spinball fue desarrollado por el equipo norteamericano de SEGA en lugar de Sonic Team Japón, lo que le da una estética y dificultad un tanto diferente."},
  {t:"m",q:"¿Cómo se llama el juego de lucha de Sonic lanzado en 1996 en arcades con personajes como Sonic, Tails, Knuckles, Amy y Espio?",o:["Sonic Kombat","Sonic Rivals","Sonic the Fighters","Sonic Brawl"],a:2,exp:"Sonic the Fighters (también llamado Sonic Championship en Occidente) fue un juego de pelea 3D de arcade, con un estilo colorido y carismático.",extra:"El juego llegó a consolas años después como descarga digital. Honey the Cat, un personaje que fue cortado del juego original, fue restaurada en la versión HD."},
  {t:"m",q:"¿Cómo se llama el juego de tablero multijugador para Dreamcast (2000) que Sonic Team desarrolló como alternativa a Mario Party?",o:["Sonic Party","Sonic Shuffle","Sonic Board","Sonic Fiesta"],a:1,exp:"Sonic Shuffle (2000) fue la respuesta de SEGA a Mario Party: un juego de tablero para Dreamcast con mini-juegos, dado y personajes de Sonic.",extra:"Aunque recibió críticas mixtas, Sonic Shuffle introdujo a Lumina Flowlight y Void, dos personajes originales del juego con una narrativa de sueños y pesadillas."},
  {t:"m",q:"¿Cómo se llama el juego de Sonic de vista isométrica lanzado en 1996 para Mega Drive y Saturn, en el que Sonic rescata Flickies?",o:["Sonic 3D","Sonic Flicky","Sonic 3D Blast","Sonic Isometric"],a:2,exp:"Sonic 3D Blast (1996), conocido como Sonic 3D Flickies' Island en Europa, usa una perspectiva isométrica en la que Sonic libera pájaros Flicky atrapados en robots.",extra:"Fue el último juego principal de Sonic en Mega Drive antes de la era Dreamcast. Hubo versiones para Mega Drive y Saturn con algunas diferencias entre sí."},
  {t:"m",q:"¿Qué habilidad especial tiene Amy Rose que la distingue de otros personajes en cuanto a movimientos de combate?",o:["Volar con su martillo","Usar su martillo Piko-Piko como arma principal de ataque","Crear escudos de energía","Disparar proyectiles"],a:1,exp:"Amy usa su martillo Piko-Piko como arma principal: puede golpear a enemigos, romperse la caída y en algunos juegos usarlo para planear brevemente.",extra:"El martillo de Amy se convirtió en su rasgo más característico desde Sonic Adventure. En Sonic Superstars, sus ataques con el martillo tienen un rango mayor."},
  {t:"m",q:"¿Cuál es el nombre del robot jefe de la serie E-Series más poderoso que forma parte de Team Dark junto a Shadow y Rouge?",o:["E-100 Alpha","E-101 Beta","E-102 Gamma","E-123 Omega"],a:3,exp:"E-123 Omega es el último modelo de la serie E-Series de Eggman, diseñado para ser el más poderoso. Fue sellado por Shadow y busca vengarse de Eggman.",extra:"Omega, junto con Shadow y Rouge, forma Team Dark en Sonic Heroes. Sus motivaciones son principalmente la venganza contra Eggman y demostrar su superioridad."},
  {t:"m",q:"¿En qué juego de Sonic para Mega CD usó por primera vez el personaje de Amy Rose su martillo Piko-Piko?",o:["Sonic CD","Sonic 3","Sonic R","Sonic the Fighters"],a:3,exp:"Amy usó su icónico martillo por primera vez en Sonic the Fighters (1996), siendo su arma de combate principal en ese juego de pelea.",extra:"En Sonic CD (1993), Amy aparece como rehén pero sin su martillo. El Piko-Piko Hammer se estableció como su arma definitoria desde Sonic the Fighters."},
  {t:"m",q:"¿Cuántas Chaos Emeralds existen en la franquicia de Sonic?",o:["5","6","7","8"],a:2,exp:"Siempre hay 7 Esmeraldas del Caos en la franquicia, cada una de un color diferente: azul, roja, amarilla, verde, cian, púrpura y blanca (o gris).",extra:"Las 7 Esmeraldas son las que permiten a Sonic transformarse en Super Sonic al poseerlas todas y tener 50 anillos. Este número es consistente en todos los juegos."},
  {t:"f",q:"Sonic puede transformarse en Super Sonic sin necesitar los 50 anillos si ya tiene las 7 Chaos Emeralds en su poder.",o:["Verdadero","Falso"],a:1,exp:"Falso. En los juegos principales, Sonic necesita tanto las 7 Chaos Emeralds como tener 50 o más anillos para activar la transformación Super.",extra:"Los anillos actúan como energía para mantener la forma Super. Sin anillos, Super Sonic no puede mantenerse y Sonic vuelve a su forma normal."},
  {t:"m",q:"¿Cómo se llama el antagonista principal de la serie Sonic X, adaptación del anime basada en el universo Adventure?",o:["Dr. Robotnik","Eggman Nega","Dr. Eggman","Mephiles"],a:2,exp:"En Sonic X, el antagonista principal es Dr. Eggman, igual que en los juegos. La serie adapta principalmente los eventos de Sonic Adventure 1, 2 y Battle.",extra:"Sonic X tuvo 78 episodios divididos en tres temporadas. La tercera temporada introdujo el arco de las Metarex, una historia original de la serie."},
  {t:"m",q:"¿Cuál de estos personajes NO apareció como parte jugable en Sonic Heroes (2003)?",o:["Big the Cat","Silver the Hedgehog","Espio the Chameleon","Rouge the Bat"],a:1,exp:"Silver the Hedgehog no existía en 2003; debutó en Sonic 06 (2006). Heroes incluye a Big (Team Rose), Espio (Team Chaotix) y Rouge (Team Dark).",extra:"Heroes tiene 4 equipos de 3 personajes cada uno: Team Sonic, Team Dark, Team Rose y Team Chaotix, con 12 personajes jugables en total."},
  {t:"m",q:"¿Qué le sucede a los anillos que lleva Sonic cuando recibe un golpe de un enemigo?",o:["Los pierde todos permanentemente","Los suelta y puede recogerlos antes de que desaparezcan","Se divide en dos el contador","Pierde la mitad automáticamente"],a:1,exp:"Al recibir daño, Sonic suelta todos sus anillos que rebotan por el escenario. El jugador tiene unos segundos para recuperar algunos antes de que desaparezcan.",extra:"Esto diferencia a Sonic de otros plataformeros: la vida no es de golpes sino de rings. Sin anillos, cualquier golpe mata. Con uno basta para sobrevivir."},
  {t:"m",q:"¿Cómo se llama la isla flotante donde Knuckles custodia la Master Emerald en los juegos de Sonic?",o:["Floating Island","Knuckles Island","Angel Island","Emerald Isle"],a:2,exp:"Angel Island es la isla flotante que levita gracias al poder de la Master Emerald. Knuckles es su guardián, el último de su clan.",extra:"Cuando la Master Emerald es robada o destruida, Angel Island cae al océano. Esto sucede en Sonic 3, SA1 y SA2 como parte central de sus tramas."},
  {t:"f",q:"La Master Emerald puede neutralizar el poder de las 7 Chaos Emeralds.",o:["Verdadero","Falso"],a:0,exp:"Verdadero. La Master Emerald tiene el poder de controlar y anular las Chaos Emeralds. Por eso Knuckles puede detener a Super Sonic tocando la piedra.",extra:"Tikal enseñó a Knuckles los poderes de la Master Emerald. Esta capacidad la hace más valiosa que las Chaos Emeralds individualmente."},
  {t:"m",q:"¿Cómo se llama la zona del primer Sonic donde el jugador corre por tubos espaciales iluminados con estrellas?",o:["Starfield Zone","Star Light Zone","Cosmos Zone","Galaxy Road"],a:1,exp:"Star Light Zone es la quinta zona de Sonic 1: una zona nocturna con rampas y loopings bajo un cielo estrellado. Su música es una de las más queridas del juego.",extra:"Star Light Zone tiene un ambiente tranquilo y nocturno que contrasta con las zonas industriales que siguen. Es considerada una de las zonas más hermosas del juego clásico."},
  {t:"m",q:"¿Cuál era el subtítulo del juego de Sonic the Hedgehog 3 (1994) que se lanzó sin completar?",o:["Knuckles' Story","& Knuckles","Return of Shadow","Island Conflict"],a:1,exp:"Sonic the Hedgehog 3 fue lanzado sin su segunda mitad por razones de tiempo. La segunda parte fue publicada como 'Sonic & Knuckles' meses después.",extra:"La intención original era un solo juego largo, pero SEGA dividió el contenido en dos cartuchos. La Lock-On Technology fue el ingenioso sistema para reunirlos."},
  {t:"m",q:"¿Qué personaje de Sonic fue originalmente diseñado como mascota alternativa de SEGA antes de que eligieran al erizo?",o:["Knuckles the Echidna","Mighty the Armadillo","Tails the Fox","Nack the Weasel"],a:1,exp:"Mighty the Armadillo fue uno de los primeros diseños que SEGA consideró como posible mascota antes de decidirse por Sonic. Terminó siendo personaje secundario.",extra:"Mighty también apareció en SegaSonic the Hedgehog Arcade (1993) y Knuckles' Chaotix (1995) antes de desaparecer durante décadas hasta Sonic Mania Plus (2018)."},
];
export default sonicQuestions;
