const sonicQuestions = [
  // ── ERA CLÁSICA ──────────────────────────────────────────────
  {t:"m",q:"¿En qué año se lanzó Sonic the Hedgehog por primera vez para Sega Mega Drive?",o:["1989","1991","1993","1995"],a:1,exp:"Sonic the Hedgehog debutó el 23 de junio de 1991 en Japón para la Mega Drive.",extra:"La fecha del 23 de junio se convirtió en el 'Día de Sonic' y se celebra cada año como aniversario oficial del personaje."},
  {t:"m",q:"¿Cuál es el nombre de la primera zona de Sonic the Hedgehog (1991)?",o:["Spring Yard Zone","Marble Zone","Green Hill Zone","Scrap Brain Zone"],a:2,exp:"Green Hill Zone es la icónica primera zona del juego original, famosa por sus loopings y colinas verdes.",extra:"Su música compuesta por Masato Nakamura se convirtió en uno de los temas más reconocibles de los videojuegos."},
  {t:"m",q:"¿Cuál es el nombre completo del Dr. Eggman?",o:["Dr. Albert Robotnik","Dr. Ivo Robotnik","Dr. Gerald Robotnik","Dr. Julian Kintobor"],a:1,exp:"El nombre oficial es Dr. Ivo Robotnik. En Occidente se usó 'Robotnik' como nombre principal hasta Sonic Adventure; 'Eggman' es su apodo.",extra:"En los juegos japoneses siempre fue llamado Eggman/Egguman, mientras que en los occidentales se popularizó el apellido Robotnik."},
  {t:"m",q:"¿Cuántas Esmeraldas del Caos existen en la saga principal de Sonic?",o:["5","6","7","8"],a:2,exp:"Las 7 Esmeraldas del Caos son las piedras preciosas más poderosas del universo Sonic. Recolectarlas permite la transformación en Super Sonic.",extra:"Cada Esmeralda representa un color: amarillo, azul, rojo, verde, gris, cian y morado/blanco según el juego."},
  {t:"m",q:"¿En qué juego apareció por primera vez Knuckles the Echidna?",o:["Sonic CD (1993)","Sonic the Hedgehog 2 (1992)","Sonic the Hedgehog 3 (1994)","Knuckles' Chaotix (1995)"],a:2,exp:"Knuckles hizo su debut en Sonic the Hedgehog 3 (1994) como el guardián de la Master Emerald que inicialmente se opone a Sonic.",extra:"Knuckles fue engañado por Eggman para que creyera que Sonic era el villano, un malentendido que generó uno de los arcos más queridos de la saga."},
  {t:"m",q:"¿Qué reliquia ancestral custodia Knuckles the Echidna en Angel Island?",o:["Las 7 Esmeraldas del Caos","La Power Ring","La Master Emerald","El Chaos Crystal"],a:2,exp:"La Master Emerald es una gema gigante que neutraliza el poder de las Esmeraldas del Caos. Knuckles es el último guardián de su linaje.",extra:"La Master Emerald reposa en la Altar de la Gema en lo alto de Angel Island, que flota en el cielo gracias a su poder."},
  {t:"m",q:"¿Cuál es el nombre completo oficial de Tails?",o:["Thomas 'Tails' Prower","Miles 'Tails' Prower","Max 'Tails' Prower","Felix 'Tails' Prower"],a:1,exp:"Su nombre completo es Miles 'Tails' Prower, un juego de palabras con 'miles per hour' (millas por hora), haciendo referencia a su velocidad.",extra:"El apodo 'Tails' proviene de sus dos colas, que usa como hélice para volar. Es el mejor amigo y compañero inseparable de Sonic."},
  {t:"m",q:"¿Qué habilidad especial tiene Tails que Sonic no posee?",o:["Trepar paredes","Volar usando sus dos colas","Hacerse invisible","Lanzar proyectiles"],a:1,exp:"Tails puede volar durante un tiempo limitado haciendo girar sus dos colas como una hélice, lo que le permite alcanzar plataformas elevadas.",extra:"Esta habilidad debutó como mecánica jugable en Sonic the Hedgehog 2 (1992), donde Tails apareció por primera vez como personaje secundario."},
  {t:"m",q:"¿En qué juego de Mega Drive se puede jugar como Super Sonic por primera vez de forma completa?",o:["Sonic the Hedgehog (1991)","Sonic the Hedgehog 2 (1992)","Sonic CD (1993)","Sonic 3 & Knuckles"],a:1,exp:"Aunque hay referencias en Sonic 1, Super Sonic es plenamente jugable desde Sonic the Hedgehog 2, tras recolectar las 7 Esmeraldas del Caos.",extra:"Super Sonic es invencible, muy rápido y consume 1 anillo por segundo; si se queda sin anillos, regresa a la forma normal."},
  {t:"m",q:"¿Cómo se llama el arma icónica de Amy Rose?",o:["Chaos Hammer","Star Mallet","Piko Piko Hammer","Rose Crusher"],a:2,exp:"El Piko Piko Hammer es el arma característica de Amy Rose. Es desproporcionadamente grande y poderoso para su tamaño.",extra:"Amy lo usa por primera vez como arma en Sonic Adventure (1998), aunque el personaje debutó en Sonic CD (1993) como la 'novia' de Sonic."},
  {t:"m",q:"¿En qué juego de Sonic apareció Amy Rose por primera vez?",o:["Sonic the Hedgehog 2","Sonic the Hedgehog 3","Sonic CD (1993)","Sonic R"],a:2,exp:"Amy Rose debutó en Sonic CD (1993), donde era conocida como 'Princess Sally' en los bocetos previos, aunque fue renombrada Amy.",extra:"En Sonic CD, Amy es secuestrada por Metal Sonic por órdenes de Eggman, siendo el primer personaje femenino recurrente de la saga."},
  {t:"f",q:"Sonic the Hedgehog sabe nadar bien y puede moverse ágilmente bajo el agua sin restricciones.",o:["Verdadero","Falso"],a:1,exp:"Falso. Sonic no sabe nadar; bajo el agua hay un contador que si llega a cero lo mata. Junto al fuego, el agua es su principal debilidad.",extra:"Esta limitación es canónica en la saga: incluso en algunos comics y series animadas se menciona que Sonic tiene miedo o rechazo al agua."},
  {t:"f",q:"Knuckles the Echidna puede planear en el aire extendiendo sus brazos para descender lentamente.",o:["Verdadero","Falso"],a:0,exp:"Verdadero. Knuckles puede planear horizontalmente en el aire al extender sus puños, permitiéndole cubrir grandes distancias.",extra:"Además de planear, Knuckles puede escalar paredes usando sus espinas de nudillos, una habilidad única entre los personajes principales de Sonic."},
  {t:"m",q:"¿Cuál fue la segunda zona de Sonic the Hedgehog (1991), de temática de ruinas antiguas?",o:["Labyrinth Zone","Spring Yard Zone","Star Light Zone","Marble Zone"],a:3,exp:"Marble Zone es la segunda zona del primer Sonic, con estética de ruinas de mármol y lava, presentando un ritmo mucho más lento que Green Hill.",extra:"Marble Zone sorprendió a muchos jugadores que esperaban la misma velocidad de Green Hill, siendo una de las zonas más memorables por su contraste."},

  // ── ERA DREAMCAST / ADVENTURE ────────────────────────────────
  {t:"m",q:"¿En qué consola se lanzó originalmente Sonic Adventure (1998)?",o:["Sega Saturn","Sega Dreamcast","PlayStation","Nintendo 64"],a:1,exp:"Sonic Adventure fue el juego estrella de lanzamiento de la Sega Dreamcast en Japón en 1998, siendo el primer Sonic 3D con historia completa.",extra:"Fue revolucionario en su época por su exploración libre, sistema de historia con múltiples personajes jugables y crianza de Chao."},
  {t:"m",q:"¿Cuál es el antagonista final de Sonic Adventure (1998)?",o:["Chaos Perfecto","Neo Metal Sonic","Biolizard","Dark Gaia"],a:0,exp:"Perfect Chaos es la forma final del ser acuático Chaos, que inunda Station Square. Sonic usa las Esmeraldas para transformarse en Super Sonic y derrotarlo.",extra:"Chaos es un ser antiguo que estuvo encerrado en la Master Emerald por Tikal durante miles de años antes de ser liberado por Eggman."},
  {t:"m",q:"¿En qué juego apareció por primera vez Shadow the Hedgehog?",o:["Sonic Adventure (1998)","Sonic Heroes (2003)","Sonic Adventure 2 (2001)","Sonic Battle (2003)"],a:2,exp:"Shadow the Hedgehog debutó en Sonic Adventure 2 (2001) como el personaje misterioso que comparte aspecto con Sonic pero actúa como rival.",extra:"Shadow fue creado por el Prof. Gerald Robotnik como la 'Forma de Vida Suprema', usando ADN de Black Doom, el líder de los Black Arms."},
  {t:"m",q:"¿Cómo se llama la estación espacial donde transcurre gran parte de Sonic Adventure 2?",o:["Eggman Space Base","Ark Colony","Space Colony ARK","Death Egg"],a:2,exp:"La Space Colony ARK es una estación espacial donde Gerald Robotnik realizó sus investigaciones; también es el hogar de infancia de Maria.",extra:"El ARK fue sellado por G.U.N. años antes del juego. Eggman activa el Eclipse Cannon, un arma dentro del ARK, como parte de su plan."},
  {t:"m",q:"¿Quién es el científico que creó a Shadow the Hedgehog?",o:["Dr. Ivo Robotnik","Professor Robotnik","Gerald Robotnik","Black Doom"],a:2,exp:"El Profesor Gerald Robotnik creó a Shadow como la Forma de Vida Suprema en la Space Colony ARK, utilizando ADN de Black Doom.",extra:"Gerald fue encarcelado y posteriormente ejecutado por G.U.N. tras el sellado del ARK, dejando mensajes cifrados que Shadow descubrirá años después."},
  {t:"m",q:"¿Qué relación familiar existe entre el Profesor Gerald Robotnik y el Dr. Eggman?",o:["Padre e hijo","Hermanos","Abuelo y nieto","Tío y sobrino"],a:2,exp:"Gerald Robotnik es el abuelo del Dr. Ivo Robotnik (Eggman). Esta revelación en SA2 añade profundidad emocional a la historia del ARK.",extra:"Eggman descubre que su abuelo construyó el Eclipse Cannon y programó al ARK para caer sobre la Tierra como venganza contra G.U.N."},
  {t:"m",q:"¿De quién es el ADN que Gerald Robotnik usó para crear a Shadow como Forma de Vida Suprema?",o:["Chaos","Black Doom","Mephiles","Perfect Chaos"],a:1,exp:"Gerald usó ADN de Black Doom, el líder alienígena de los Black Arms, para dar a Shadow sus habilidades únicas. Esto se revela en Shadow the Hedgehog (2005).",extra:"Por eso Shadow puede usar Chaos Control de forma natural, ya que los Black Arms tienen ese poder. También explica por qué Black Doom lo reconoce."},
  {t:"m",q:"¿Cómo se llama la habilidad de Shadow que le permite distorsionar el espacio y el tiempo?",o:["Dark Speed","Shadow Blast","Chaos Control","Dark Warp"],a:2,exp:"Chaos Control es la habilidad que permite manipular el espacio-tiempo usando las Esmeraldas del Caos. Shadow la usa con especial maestría.",extra:"Sonic también puede usar Chaos Control en ciertos momentos, pero Shadow es el usuario más hábil de esta técnica en toda la saga."},
  {t:"m",q:"¿En qué juego hizo su debut Rouge the Bat?",o:["Sonic Adventure (1998)","Sonic Heroes (2003)","Sonic Adventure 2 (2001)","Shadow the Hedgehog (2005)"],a:2,exp:"Rouge the Bat debutó en Sonic Adventure 2 (2001), donde actúa como espía de G.U.N. infiltrada en los planes de Eggman.",extra:"Rouge es una ladrona de joyas que trabaja ocasionalmente para G.U.N. Su relación con Shadow y Omega forma el Team Dark."},
  {t:"f",q:"Rouge the Bat trabaja en secreto como agente espía para la organización G.U.N.",o:["Verdadero","Falso"],a:0,exp:"Verdadero. Aunque actúa como cazadora de joyas independiente, Rouge es una agente encubierta de G.U.N. que investiga a Eggman y el ARK.",extra:"Su doble rol de villana/aliada la convierte en uno de los personajes moralmente más ambiguos de la saga junto a Shadow."},
  {t:"m",q:"¿Cuántos equipos de personajes existen en Sonic Heroes (2003)?",o:["3","4","5","6"],a:1,exp:"Sonic Heroes tiene 4 equipos: Team Sonic (Sonic, Tails, Knuckles), Team Dark (Shadow, Rouge, Omega), Team Rose (Amy, Cream, Big) y Team Chaotix.",extra:"Cada equipo tiene tres clases de personaje: velocidad, vuelo y poder, y todos abordan la misma historia desde perspectivas diferentes."},
  {t:"m",q:"¿Quiénes conforman el Team Dark en Sonic Heroes?",o:["Shadow, Rouge y Gamma","Shadow, Rouge y Omega","Silver, Blaze y Rouge","Shadow, Metal Sonic y Rouge"],a:1,exp:"Team Dark está formado por Shadow the Hedgehog, Rouge the Bat y E-123 Omega, el robot de Eggman que quiere venganza contra su creador.",extra:"E-123 Omega fue sellado junto a Shadow al inicio de Heroes. Su furia contra Eggman lo lleva a aliarse con Shadow y Rouge."},

  // ── PERSONAJES MODERNOS ──────────────────────────────────────
  {t:"m",q:"¿De qué época proviene Silver the Hedgehog?",o:["Del pasado, 200 años antes","Del futuro, 200 años después","De una dimensión paralela","De la Luna"],a:1,exp:"Silver viene del futuro, aproximadamente 200 años después de los eventos presentes, donde el mundo está destruido por el flamante Iblis.",extra:"Silver viaja al pasado para eliminar el 'Mephiles' que causó la catástrofe, lo que lo pone en conflicto directo con Sonic."},
  {t:"m",q:"¿Cuál es el poder especial de Silver the Hedgehog?",o:["Pircinesis (fuego)","Crioquinesis (hielo)","Telequinesis (psíquico)","Electrocinesis (electricidad)"],a:2,exp:"Silver posee poderosas habilidades psíquicas (telequinesis) que le permiten levitar objetos y rivales con su mente.",extra:"En Sonic the Hedgehog (2006), Silver puede suspender a Sonic en el aire usando su telequinesis, siendo uno de los rivales más peligrosos del juego."},
  {t:"m",q:"¿En qué juego apareció por primera vez Blaze the Cat?",o:["Sonic Riders (2006)","Sonic Rush (2005)","Sonic the Hedgehog (2006)","Sonic Unleashed (2008)"],a:1,exp:"Blaze debutó en Sonic Rush (2005) para Nintendo DS, donde colabora con Sonic desde su dimensión paralela.",extra:"En Sonic Rush, Blaze recolecta las Sol Emeralds de su mundo mientras Sonic reúne las Chaos Emeralds, y juntos enfrentan a Eggman y Eggman Nega."},
  {t:"m",q:"¿Cuál es el poder de Blaze the Cat?",o:["Control del hielo","Pirocinesis (control del fuego)","Velocidad supersónica","Invisibilidad"],a:1,exp:"Blaze tiene pirocinesis, la capacidad de generar y controlar el fuego. Es una princesa de la Sol Dimension con este don innato.",extra:"Su forma superpoderosa, Burning Blaze, se activa con las 7 Sol Emeralds y es el equivalente a Super Sonic en su dimensión."},
  {t:"m",q:"¿Cómo se llama la transformación nocturna de Sonic en Sonic Unleashed (2008)?",o:["Dark Sonic","Shadow Form","Werehog","Chaos Sonic"],a:2,exp:"En Sonic Unleashed, Dark Gaia fragmenta el alma de Sonic de noche convirtiéndolo en el Werehog, con cuerpo elástico y fuerza bruta.",extra:"El Werehog juega completamente diferente al Sonic normal: es un juego de acción cuerpo a cuerpo lento, no de velocidad."},
  {t:"m",q:"¿Cómo se llaman los seres extraterrestres que Sonic conoce en Sonic Colors (2010)?",o:["Chao","Wisps","Mobians","Flicky"],a:1,exp:"Los Wisps son alienígenas que Eggman ha capturado para usar su energía como combustible. Sonic los libera y ellos le otorgan poderes temporales.",extra:"Cada color de Wisp da un poder diferente: el Cyan Wisp convierte a Sonic en un láser, el Red Wisp en una roca, el Yellow en un taladro, etc."},
  {t:"m",q:"¿Cuáles son los dos Sonic jugables en Sonic Generations (2011)?",o:["Super Sonic y Hyper Sonic","Sonic y Shadow","Sonic Clásico y Sonic Moderno","Sonic y Metal Sonic"],a:2,exp:"Sonic Generations presenta dos versiones de Sonic: el Clásico de los años 90 (silencioso, con Spin Dash) y el Moderno (con voz y Homing Attack).",extra:"El juego celebra los 20 años de Sonic revisitando zonas icónicas de toda la historia con ambos personajes."},
  {t:"f",q:"Sonic Mania (2017) fue desarrollado en parte por fans de Sonic que se profesionalizaron y fueron contratados por SEGA.",o:["Verdadero","Falso"],a:0,exp:"Verdadero. Christian Whitehead, PagodaWest Games y Headcannon (todos conocidos por sus proyectos fan) lideraron el desarrollo de Sonic Mania.",extra:"Sonic Mania fue muy bien recibido por la crítica, considerado el mejor juego de Sonic en años, y revitalizó el interés en el estilo clásico."},
  {t:"m",q:"¿Qué tipo de mundo introdujo Sonic Frontiers (2022) por primera vez en la saga principal?",o:["Un mundo procedural infinito","Niveles lineales con múltiples caminos","Un mundo abierto de exploración libre (open-zone)","Una ciudad sandbox editable"],a:2,exp:"Sonic Frontiers introdujo el concepto 'open-zone' en la saga: mundos abiertos gigantes que Sonic puede explorar libremente antes de abordar los niveles.",extra:"Fue el primer Sonic 3D en alejarse radicalmente del diseño de etapas lineales, acercándose más a juegos como Breath of the Wild."},
  {t:"m",q:"¿Quién diseñó visualmente a Sonic the Hedgehog originalmente en SEGA?",o:["Yuji Naka","Masato Nakamura","Naoto Ohshima","Hirokazu Yasuhara"],a:2,exp:"Naoto Ohshima diseñó el aspecto visual de Sonic. Yuji Naka programó el motor del juego y Hirokazu Yasuhara diseñó los niveles.",extra:"La banda sonora del primer juego fue compuesta por Masato Nakamura, bajista del grupo musical Dreams Come True."},

  // ── PERSONAJES SECUNDARIOS ───────────────────────────────────
  {t:"m",q:"¿En qué juego apareció por primera vez Metal Sonic?",o:["Sonic the Hedgehog 2","Sonic CD (1993)","Sonic 3 & Knuckles","Sonic Adventure"],a:1,exp:"Metal Sonic debutó en Sonic CD (1993) como la gran creación de Eggman: una versión mecánica de Sonic que le sirve de rival principal.",extra:"Su icónica carrera en Stardust Speedway contra Sonic es una de las secuencias más memorables de la saga clásica."},
  {t:"f",q:"Metal Sonic tiene la capacidad de escanear y copiar datos de otros personajes para replicar sus habilidades.",o:["Verdadero","Falso"],a:0,exp:"Verdadero. Especialmente en Sonic Heroes, Neo Metal Sonic copia datos de Sonic, Shadow y Chaos para transformarse en Metal Overlord.",extra:"Esta habilidad lo convierte en el antagonista oculto de Sonic Heroes, haciéndose pasar por Eggman para manipular a todos los equipos."},
  {t:"m",q:"¿Cómo se llama la chao mascota de Cream the Rabbit?",o:["Froggy","Cheese","Gemerl","Chocola"],a:1,exp:"Cheese es el pequeño chao azul que acompaña siempre a Cream. A diferencia de otros chao, Cheese participa activamente en combate.",extra:"Cream y Cheese debutan en Sonic Advance 2 (2002) y luego aparecen en Sonic Heroes, Sonic Battle, Sonic Rush y otras entregas."},
  {t:"m",q:"¿Qué busca Big the Cat durante toda su historia en Sonic Adventure (1998)?",o:["La Master Emerald","La Power Ring","Su rana llamada Froggy","Las Esmeraldas del Caos"],a:2,exp:"Big the Cat pasa toda su campaña en SA1 buscando a Froggy, su rana mascota que huyó después de tragarse una cola de Chaos.",extra:"La campaña de Big en SA1 es recordada por ser radicalmente diferente al ritmo del resto del juego, centrada en la pesca."},
  {t:"m",q:"¿Cuál es el nombre del robot de Eggman que forma parte del Team Dark junto a Shadow y Rouge?",o:["E-102 Gamma","E-123 Omega","E-10000 G","Metal Sonic"],a:1,exp:"E-123 Omega es el último y más poderoso de los robots E-Series de Eggman, que lo encerró en la misma instalación que a Shadow.",extra:"Omega busca venganza contra Eggman por haberlo sellado. Su implacable fuerza de fuego es clave en las batallas del Team Dark."},
  {t:"m",q:"¿Cuál es el nombre del líder de los Babylon Rogues en Sonic Riders (2006)?",o:["Wave the Swallow","Storm the Albatross","Jet the Hawk","Silver the Hedgehog"],a:2,exp:"Jet the Hawk es el líder de los Babylon Rogues y el rival más directo de Sonic en Sonic Riders, donde compiten en carreras de aeroplanchas.",extra:"Jet se llama a sí mismo el 'Fastest Thing in the World', título que lo pone en conflicto constante con Sonic."},
  {t:"m",q:"¿Quiénes son los tres miembros del Team Chaotix?",o:["Espio, Charmy y Vector","Knuckles, Espio y Vector","Cream, Espio y Vector","Big, Charmy y Vector"],a:0,exp:"El Team Chaotix está formado por Espio the Chameleon, Charmy Bee y Vector the Crocodile, quienes dirigen la agencia detective Chaotix.",extra:"Los Chaotix aparecieron por primera vez en Knuckles' Chaotix (1995) para Sega 32X, siendo uno de los primeros spinoffs importantes de Sonic."},
  {t:"m",q:"¿En qué juego hicieron su debut los personajes del Team Chaotix?",o:["Sonic CD (1993)","Knuckles' Chaotix (1995)","Sonic Heroes (2003)","Sonic Advance 3"],a:1,exp:"Knuckles' Chaotix (1995) para Sega 32X introdujo a Espio, Charmy, Vector, Mighty y Heavy/Bomb. Vector se conoció por primera vez aquí.",extra:"Knuckles' Chaotix tuvo un mechanic único: dos personajes siempre conectados por un elástico de energía, lo que afectaba el movimiento."},

  // ── LORE Y ORGANIZACIONES ────────────────────────────────────
  {t:"m",q:"¿Qué significa la sigla G.U.N. en el universo de Sonic?",o:["Global Union of Nations","Guardian Units of Nations","General United Network","Galactic Universal Nexus"],a:1,exp:"G.U.N. son las Guardian Units of Nations, una organización militar gubernamental que opera en secreto, a veces como antagonista.",extra:"G.U.N. capturó a Gerald Robotnik y mató a Maria. Años después, persigue a Shadow creyéndolo peligroso."},
  {t:"m",q:"¿Quién es Maria Robotnik y qué relación tiene con Shadow?",o:["La hija de Eggman y enemiga de Shadow","La hermana de Gerald y programadora del ARK","La nieta de Gerald Robotnik y mejor amiga de Shadow","Una robot creada para acompañar a Shadow"],a:2,exp:"Maria era la nieta del Prof. Gerald Robotnik y vivía en el ARK due a su enfermedad (NIDS). Era la mejor amiga de Shadow hasta que G.U.N. la mató.",extra:"El deseo de Maria antes de morir era que Shadow protegiera a las personas de la Tierra; esto motiva el arco redentor de Shadow en SA2."},
  {t:"f",q:"Al final de Sonic Adventure 2, Shadow aparentemente muere después de usar el Chaos Control con Super Sonic para salvar la Tierra.",o:["Verdadero","Falso"],a:0,exp:"Verdadero. Shadow usa sus últimas fuerzas junto a Super Sonic para detener el ARK y cae al espacio, dando a entender que muere. Regresa en Sonic Heroes.",extra:"Su 'muerte' al final de SA2 fue un momento emotivo poderoso, aunque posteriormente Eggman reveló que lo había salvado y tenía copias en cápsulas."},
  {t:"m",q:"¿Cómo se llama la forma superpoderosa de Knuckles obtenida con las Super Emeralds en Sonic 3 & Knuckles?",o:["Mega Knuckles","Super Knuckles","Hyper Knuckles","Dark Knuckles"],a:2,exp:"Con las Super Emeralds (versión mejorada de las Chaos Emeralds en Sonic 3 & Knuckles), Knuckles se transforma en Hyper Knuckles.",extra:"Hyper Sonic, Hyper Tails e Hyper Knuckles son más poderosos que sus formas Super. Estas transformaciones solo existen en Sonic 3 & Knuckles."},
  {t:"m",q:"¿Cómo se llaman las versiones mejoradas de las Esmeraldas del Caos disponibles en Sonic 3 & Knuckles?",o:["Chaos Crystals","Hyper Emeralds","Super Emeralds","Master Shards"],a:2,exp:"Las Super Emeralds se obtienen llevando las 7 Chaos Emeralds a las Special Stages gigantes del Mushroom Hill en Sonic 3 & Knuckles.",extra:"Cada Esmeralda del Caos puede potenciarse en una Super Emerald pasándola por un Monitor de Super Emerald en los niveles secretos."},
  {t:"m",q:"¿Cómo se llama el ser de dos partes (Iblis y Mephiles) que es el dios destructor en Sonic the Hedgehog (2006)?",o:["Perfect Dark","Darkspine","Solaris","Iblis Prime"],a:2,exp:"Solaris es la deidad caótica dividida en Iblis (el flamante destructor sin mente) y Mephiles (la sombra consciente). Eggman lo separa accidentalmente.",extra:"Sonic 06 tiene un final donde Sonic y Elise apagan la llama de Solaris borrando toda la línea temporal del juego de la existencia."},

  // ── MECÁNICAS DE JUEGO ───────────────────────────────────────
  {t:"m",q:"¿Cuál fue la primera aparición del Homing Attack, la técnica de Sonic para atacar en el aire hacia enemigos?",o:["Sonic 3 & Knuckles","Sonic CD","Sonic Adventure (1998)","Sonic Spinball"],a:2,exp:"El Homing Attack en su forma moderna debutó en Sonic Adventure (1998) para Dreamcast, siendo clave en la nueva dimensión 3D del juego.",extra:"Esta técnica se volvió tan fundamental que aparece en prácticamente todos los juegos 3D de Sonic y es considerada su movimiento más reconocible en 3D."},
  {t:"m",q:"¿Qué necesita Sonic para transformarse en Super Sonic?",o:["Recolectar 50 anillos solamente","Las 7 Esmeraldas del Caos y al menos 50 anillos","Solo las 7 Esmeraldas del Caos","Un Power Ring especial y las Esmeraldas"],a:1,exp:"Para transformarse en Super Sonic se necesitan las 7 Esmeraldas del Caos y al menos 50 anillos. La transformación consume 1 anillo por segundo.",extra:"Esta mecánica se mantuvo consistente en la mayoría de juegos; Super Sonic es invencible, muy veloz y puede derrotar enemigos con solo tocarlo."},
  {t:"f",q:"En los juegos clásicos de Sonic, si recibes un golpe con al menos un anillo, no pierdes una vida sino que los anillos se dispersan.",o:["Verdadero","Falso"],a:0,exp:"Verdadero. Los anillos funcionan como escudo: al recibir daño, se dispersan y tienes un instante para recuperarlos. Sin anillos, el siguiente golpe es mortal.",extra:"Este sistema de 'escudo de anillos' es uno de los elementos más innovadores del diseño de Sonic, diferenciándolo del sistema de vidas de Mario."},
  {t:"m",q:"¿Cómo se llama la técnica de Sonic que le permite arrancar desde parado acumulando velocidad giratoria?",o:["Spin Jump","Spin Attack","Spin Dash","Rolling Start"],a:2,exp:"El Spin Dash permite a Sonic girar en el lugar para acumular velocidad y lanzarse a alta velocidad. Debutó en Sonic the Hedgehog 2.",extra:"El Spin Dash fue tan popular que no ha faltado en prácticamente ningún juego de Sonic desde su introducción en 1992."},

  // ── BANDA SONORA Y MEDIOS ────────────────────────────────────
  {t:"m",q:"¿Cómo se llama la banda de rock que realizó canciones icónicas para Sonic Adventure 2 como 'Live and Learn'?",o:["Dream Factory","Crush 40","Sonic Rush Band","Jun Force"],a:1,exp:"Crush 40 es la banda formada por Jun Senoue (guitarrista) y Johnny Gioeli (vocalista). Sus temas son emblemáticos de la era Adventure de Sonic.",extra:"'Live and Learn' suena durante el clímax de SA2 cuando Shadow y Sonic se transforman para salvar la Tierra, siendo uno de los momentos más épicos del juego."},
  {t:"m",q:"¿Cómo se llama la canción principal de Sonic Adventure 2?",o:["Open Your Heart","His World","Live and Learn","Escape from the City"],a:2,exp:"'Live and Learn' de Crush 40 es la canción principal de SA2 y suena en el combate final contra el Biolizard/Finalhazard.",extra:"La canción 'Escape from the City' de SA2, aunque no es la principal, es posiblemente la más icónica asociada al juego por la escena de la tabla en la autopista."},
  {t:"m",q:"¿Cómo se llama la canción principal de Sonic Adventure 1?",o:["Live and Learn","Open Your Heart","Believe in Myself","Unknown from M.E."],a:1,exp:"'Open Your Heart' de Crush 40 es la canción principal de Sonic Adventure (1998), cantada en el combate contra Perfect Chaos.",extra:"'Unknown from M.E.' es el rap de Knuckles en SA1. 'Believe in Myself' es el tema de Tails. Cada personaje tiene su propia canción."},
  {t:"m",q:"¿Cómo se llama el anime japonés de Sonic emitido entre 2003 y 2006?",o:["Sonic Underground","Sonic X","Sonic SatAM","Sonic Boom"],a:1,exp:"Sonic X es el anime japonés producido por TMS Entertainment que siguió las aventuras de Sonic y sus amigos junto al joven Chris Thorndyke.",extra:"Sonic X fue doblado a muchos idiomas y presentó adaptaciones del arco de Sonic Adventure, Sonic Adventure 2 y Sonic Battle."},
  {t:"m",q:"¿Quién dio voz a Sonic the Hedgehog en la película live-action de 2020?",o:["Roger Craig Smith","Jason Griffith","Ben Schwartz","Ryan Reynolds"],a:2,exp:"Ben Schwartz (conocido por Parks and Recreation y Jean-Ralphio) da voz al personaje de Sonic en las películas live-action.",extra:"La película fue notoria por cambiar el diseño de Sonic tras el rechazo masivo del tráiler original, rediseñando al personaje antes del estreno."},
  {t:"m",q:"¿Quién interpretó al Dr. Robotnik en la película Sonic the Hedgehog (2020)?",o:["Steve Carell","Jim Carrey","Will Ferrell","Bill Murray"],a:1,exp:"Jim Carrey dio vida al Dr. Robotnik con su característico humor exagerado, siendo uno de los aspectos más elogiados de la película.",extra:"La actuación de Carrey fue tan bien recibida que regresó en Sonic the Hedgehog 2 (2022), mostrando al personaje convertirse en el Eggman clásico."},
  {t:"m",q:"¿En qué año se estrenó la primera película live-action de Sonic the Hedgehog?",o:["2018","2019","2020","2021"],a:2,exp:"Sonic the Hedgehog se estrenó en febrero de 2020 y fue un éxito de taquilla, convirtiéndose en una de las mejores adaptaciones de videojuego al cine.",extra:"Originalmente planeada para noviembre de 2019, fue retrasada para permitir el rediseño completo del personaje tras las críticas al tráiler."},

  // ── CREADORES Y CONTEXTO ─────────────────────────────────────
  {t:"m",q:"¿Qué consola rival de Nintendo motivó la creación de Sonic como mascota para SEGA?",o:["NES (Nintendo Entertainment System)","Super Nintendo / SNES","Game Boy","Virtual Boy"],a:1,exp:"SEGA creó a Sonic para competir directamente con la Super Nintendo de Nintendo y su mascota Mario, que dominaba el mercado.",extra:"En 1991, la SNES superaba en ventas a la Mega Drive. Sonic fue el 'game changer' que cambió la percepción del hardware de SEGA."},
  {t:"f",q:"En Norteamérica, Sonic the Hedgehog se vendía incluido con la Sega Mega Drive como juego pack-in, sustituyendo a otros títulos.",o:["Verdadero","Falso"],a:0,exp:"Verdadero. Desde 1991, SEGA comenzó a incluir Sonic con la Genesis (Mega Drive) en Norteamérica para superar las ventas frente a Nintendo.",extra:"Esta estrategia fue tan exitosa que las ventas de la Mega Drive se dispararon. Sonic fue durante un tiempo el videojuego más vendido del mundo."},
  {t:"m",q:"¿Quién fue el principal programador y líder de Sonic Team durante los primeros juegos de Sonic?",o:["Naoto Ohshima","Hirokazu Yasuhara","Yuji Naka","Masato Nakamura"],a:2,exp:"Yuji Naka fue el programador principal del primer Sonic y líder de Sonic Team durante años. Es considerado el 'padre' de Sonic junto a Ohshima y Yasuhara.",extra:"En 2006, Yuji Naka dejó SEGA para fundar su propio estudio, Prope. Su partida marcó el fin de una era para Sonic Team."},
  {t:"f",q:"Sonic fue el primer personaje de SEGA en aparecer en la serie Super Smash Bros. de Nintendo.",o:["Verdadero","Falso"],a:0,exp:"Verdadero. Sonic fue el primer representante de SEGA en Smash Bros., debutando en Super Smash Bros. Brawl (2008) para Nintendo Wii.",extra:"Su inclusión fue muy solicitada por los fans durante años. Fue anunciado de forma dramática poco antes del lanzamiento de Brawl."},

  // ── JUEGOS ESPECÍFICOS ───────────────────────────────────────
  {t:"m",q:"¿Cómo se llama la zona de casino icónica del primer Sonic 2?",o:["Casinopolis","Spring Yard Zone","Casino Night Zone","Carnival Night Zone"],a:2,exp:"Casino Night Zone en Sonic the Hedgehog 2 es famosa por sus flipper, tragamonedas y bumpers. Es una de las zonas más recordadas de los juegos clásicos.",extra:"Sonic 3 tiene Carnival Night Zone con temática similar pero más enfocada en plataformas y la infame barril que muchos jugadores no sabían cómo superar."},
  {t:"m",q:"¿En qué juego apareció por primera vez la Chemical Plant Zone, luego revisitada en Generations y Mania?",o:["Sonic the Hedgehog (1991)","Sonic the Hedgehog 2 (1992)","Sonic CD (1993)","Sonic 3"],a:1,exp:"Chemical Plant Zone debutó en Sonic 2 (1992) como la icónica zona industrial morada con el líquido Mega Mack en el que Sonic se ahoga.",extra:"Esta zona regresó en Sonic Generations (2011) y Sonic Mania (2017), convirtiéndose en una de las más revisitadas de toda la franquicia."},
  {t:"m",q:"¿En qué zona de Sonic 3 & Knuckles cae Sonic desde el cielo al inicio del juego?",o:["Mushroom Hill Zone","Flying Battery Zone","Angel Island Zone","Hydrocity Zone"],a:2,exp:"Angel Island Zone es la primera zona de Sonic 3. Sonic aterriza en la isla flotante de Knuckles, quien destruye las Esmeraldas del Caos.",extra:"El opening de Sonic 3 es legendario: muestra a Sonic y Tails en el Tornado volando hacia la isla, con la épica música que acompaña la caída."},
  {t:"m",q:"¿En qué juego de Sonic para Nintendo DS aparece Blaze the Cat junto a Sonic por primera vez en la saga principal?",o:["Sonic Advance 2","Sonic Chronicles","Sonic Rush (2005)","Sonic Rush Adventure"],a:2,exp:"Sonic Rush (2005) para Nintendo DS presentó a Blaze the Cat y al villano Eggman Nega, siendo el primer juego exclusivo para DS de Sonic.",extra:"Sonic Rush usó las dos pantallas de la DS de forma creativa: Sonic corría por las dos simultáneamente y podía acumular boost para ir más rápido."},
  {t:"f",q:"Sonic the Hedgehog (2006) fue muy bien recibido por la crítica y los fans tras su lanzamiento.",o:["Verdadero","Falso"],a:1,exp:"Falso. Sonic 06 fue fuertemente criticado por sus bugs técnicos, tiempos de carga excesivos, historia confusa y controles defectuosos.",extra:"'Sonic 06' se convirtió en sinónimo de decepción en la comunidad; el proyecto fue apresurado para coincidir con el 15 aniversario del personaje."},
  {t:"m",q:"¿En qué año se lanzó Sonic Mania, el juego de regreso al estilo clásico?",o:["2015","2016","2017","2018"],a:2,exp:"Sonic Mania se lanzó en agosto de 2017 para PS4, Xbox One, Nintendo Switch y PC, recibiendo críticas muy positivas.",extra:"Sonic Mania Plus (2018) añadió a Mighty the Armadillo y Ray the Flying Squirrel como personajes jugables adicionales."},
  {t:"m",q:"¿Cuál de estas zonas de Sonic Mania (2017) es completamente original y no aparece en ningún juego clásico anterior?",o:["Green Hill Zone","Chemical Plant Zone","Studiopolis Zone","Hydrocity Zone"],a:2,exp:"Studiopolis Zone es una de las zonas nuevas de Sonic Mania, con temática de estudio de televisión. Fue creada completamente para el juego.",extra:"Sonic Mania tiene 12 zonas en total: algunas son remakes de clásicos (revisitadas con nuevas rutas y jefes) y otras son completamente originales."},
  {t:"m",q:"¿Cómo se llama la inteligencia artificial que actúa como aliada de Sonic en Sonic Frontiers (2022)?",o:["Aurora","ARIA","Sage","Nova"],a:2,exp:"Sage es una IA creada por Eggman que actúa como guardiana de las islas Starfall y eventualmente como aliada cuando comprende la amenaza de The End.",extra:"Sage tiene un rol importante en la narrativa de Frontiers, con un arco emocional similar al de Shadow en SA2, sobre la lealtad y la identidad."},

  // ── LORE ADICIONAL ───────────────────────────────────────────
  {t:"m",q:"¿Cuál es el coeficiente intelectual que se atribuye canónicamente al Dr. Eggman?",o:["200","250","300","400"],a:2,exp:"El Dr. Eggman tiene un IQ canónico de 300, lo que lo hace uno de los villanos más inteligentes de los videojuegos pese a sus fracasos constantes.",extra:"Su genialidad contrasta con su incapacidad de derrotar definitivamente a Sonic, lo que ha generado memes sobre su 'competencia selectiva'."},
  {t:"m",q:"¿Qué color son los ojos de Sonic en su diseño moderno (desde Sonic Adventure en adelante)?",o:["Negros","Azules","Verdes","Amarillos"],a:2,exp:"En su diseño moderno desde Sonic Adventure (1998), Sonic tiene ojos verdes brillantes. En el diseño clásico de los 90, sus ojos eran completamente negros.",extra:"El cambio a ojos verdes fue parte del rediseño para el paso a 3D. El color verde se mantiene como seña de identidad de Sonic moderno hasta hoy."},
  {t:"f",q:"En el diseño clásico original de Sonic (años 90), sus ojos eran completamente negros sin iris de color.",o:["Verdadero","Falso"],a:0,exp:"Verdadero. El Sonic clásico tiene ojos negros como los de cualquier personaje de dibujos animados de la época. Los ojos verdes son una característica del diseño moderno.",extra:"Esta diferencia entre el Sonic clásico y el moderno es uno de los contrastes visuales más notables en Sonic Generations."},
  {t:"m",q:"¿Cuál es el poder psíquico especial de Espio the Chameleon en los Chaotix?",o:["Controlar el fuego","Volar como Tails","Volverse invisible","Usar armas de largo alcance"],a:2,exp:"Espio puede volverse invisible usando sus habilidades de camaleón, lo que lo hace ideal para misiones de espionaje e infiltración.",extra:"También puede lanzar shurikens y trepar por paredes. Su personalidad ninja es uno de los rasgos más queridos por los fans de los Chaotix."},
  {t:"m",q:"¿Qué nombre recibe el jardín donde se crían y cuidan las criaturas virtuales en Sonic Adventure?",o:["Animal Kingdom","Chao Garden","Chaos Garden","Flicky Park"],a:1,exp:"El Chao Garden es el área donde los jugadores pueden criar, entrenar y evolucionar a sus Chao, las criaturas de huevo que habitan el universo de Sonic.",extra:"Los Chao pueden evolucionar hacia formas Hero o Dark según con qué personaje pasen más tiempo. El sistema de crianza fue muy popular en SA1 y SA2."},
  {t:"m",q:"¿Cómo se llama el robot de la serie E-Series en Sonic Adventure 1 que tiene un arco redentor, liberando animales atrapados en otros robots?",o:["E-100 Alpha","E-102 Gamma","E-123 Omega","E-104 Epsilon"],a:1,exp:"E-102 Gamma tiene un arco emotivo en SA1: creado por Eggman para cazar, decide en cambio liberar los animales atrapados dentro de sus hermanos robots.",extra:"El personaje de Gamma resonó enormemente con los jugadores por su historia de libre albedrío y sacrificio. Es considerado uno de los mejores arcos de SA1."},
  {t:"m",q:"¿Cómo se llaman las gemas equivalentes a las Esmeraldas del Caos en la dimensión de Blaze the Cat?",o:["Chaos Gems","Sol Emeralds","Fire Crystals","Sun Stones"],a:1,exp:"Las Sol Emeralds son las 7 gemas que Blaze recolecta en Sonic Rush para transformarse en Burning Blaze, el equivalente a Super Sonic.",extra:"Las Sol Emeralds existen en la Sol Dimension, paralela a la de Sonic. La magia de ambas dimensiones está interconectada en los eventos de Sonic Rush."},
  {t:"f",q:"La velocidad de Sonic supera canónicamente la velocidad del sonido (Mach 1, ~1234 km/h).",o:["Verdadero","Falso"],a:0,exp:"Verdadero. Canónicamente Sonic supera la velocidad del sonido, de ahí su nombre 'Sonic' (relacionado con el sonido). En algunos medios se dice que alcanza la velocidad de la luz.",extra:"La velocidad exacta varía según el medio: en los cómics puede acelerar aún más. Lo que está claro es que es el ser más rápido de su universo."},
  {t:"f",q:"Cream the Rabbit puede flotar usando sus largas orejas como si fueran hélices.",o:["Verdadero","Falso"],a:0,exp:"Verdadero. Cream puede volar temporalmente agitando sus grandes orejas, similar a cómo Tails usa sus colas para volar.",extra:"Esta mecánica la hace especialmente útil en juegos como Sonic Advance 2 y Sonic Heroes, donde puede mantener a Amy en el aire en el Team Rose."},

  // ── PREGUNTAS FINALES ────────────────────────────────────────
  {t:"m",q:"¿Cuál es la primera franquicia deportiva oficial donde Sonic y Mario aparecen juntos en un videojuego?",o:["Olimpiadas de Fútbol","Mario & Sonic en los Juegos Olímpicos de Pekín 2008","FIFA con personajes especiales","Sonic & Mario Tennis"],a:1,exp:"Mario & Sonic en los Juegos Olímpicos (2007) para Wii fue la primera vez que ambos personajes compartieron un videojuego oficial.",extra:"El juego fue un evento cultural enorme porque durante décadas Mario y Sonic fueron rivales. Su colaboración fue impensable para los fans de los años 90."},
  {t:"f",q:"Shadow the Hedgehog (2005) fue el primer juego de Sonic donde el personaje podía usar armas de fuego y conducir vehículos.",o:["Verdadero","Falso"],a:0,exp:"Verdadero. Shadow the Hedgehog (2005) fue el primer juego de la saga donde se podía usar pistolas, fusiles, granadas y conducir todo tipo de vehículos.",extra:"El juego intentó dirigirse a un público más maduro con temáticas oscuras y elecciones morales, recibiendo críticas mixtas por este enfoque."},
  {t:"m",q:"¿En qué consola portátil de SEGA se lanzaron varios juegos de Sonic en los años 90, paralelos a la Mega Drive?",o:["Game Gear","Nomad","Master System","Saturn Handheld"],a:0,exp:"La Game Gear de SEGA tuvo varios juegos de Sonic adaptados específicamente para la portátil, con niveles y diseño diferente a los de Mega Drive.",extra:"Sonic portátil para Game Gear incluía Sonic 1, 2, Sonic Chaos, Sonic Triple Trouble y más, todos con niveles diseñados para el formato portátil."},
  {t:"m",q:"¿Cómo se llama la canción principal de Sonic the Hedgehog (2006)?",o:["Live and Learn","Open Your Heart","His World","Endless Possibility"],a:2,exp:"'His World' interpretada por Zebrahead acompaña la historia de Sonic en el juego de 2006, sirviendo como su tema principal.",extra:"'Endless Possibility' es el tema de Sonic Unleashed; 'Reach for the Stars' es de Colors; 'Live and Learn' es de SA2. Cada era tiene su anthem."},
  {t:"m",q:"¿Cuántas zonas tiene Sonic the Hedgehog (1991) en total?",o:["4 zonas","5 zonas","6 zonas","8 zonas"],a:2,exp:"El primer Sonic tiene 6 zonas: Green Hill, Marble, Spring Yard, Labyrinth, Star Light y Scrap Brain. Cada una tiene 3 actos.",extra:"El diseño de 6 zonas con 3 actos cada una se convirtió en la fórmula estándar que Sonic 2 y 3 expandirían y modificarían."},
  {t:"m",q:"¿Qué tecnología especial permitía conectar el cartucho de Sonic & Knuckles con Sonic 2 y Sonic 3 en la Mega Drive?",o:["Sonic Fusion","Pass Through","Lock-On Technology","Combo Cartridge"],a:2,exp:"La Lock-On Technology del cartucho de Sonic & Knuckles permite insertar otros cartuchos en su conector superior para expandir el juego.",extra:"Sonic 3 + Sonic & Knuckles crea la experiencia completa que se pretendía originalmente; con Sonic 2 desbloquea Knuckles in Sonic 2."},
  {t:"m",q:"¿Cuál es la zona de tipo laberinto acuático del primer Sonic (1991) donde el agua puede ahogarlo?",o:["Oil Ocean Zone","Aquatic Ruin Zone","Hydrocity Zone","Labyrinth Zone"],a:3,exp:"Labyrinth Zone en Sonic 1 es la cuarta zona del juego y la primera en introducir el peligro del agua, con burbujas de aire que Sonic necesita para sobrevivir.",extra:"La zona es muy odiada y amada a partes iguales; muchos jugadores la recuerdan como la primera vez que Sonic los hizo perder por ahogamiento."},
  {t:"m",q:"¿En qué año hizo Sonic su debut en Super Smash Bros., convirtiéndose en el primer personaje de SEGA en la saga?",o:["2005","2006","2008","2010"],a:2,exp:"Sonic debutó en Super Smash Bros. Brawl en 2008 para Wii, siendo el primer y durante mucho tiempo único personaje de SEGA en la saga de Nintendo.",extra:"Su inclusión fue una de las más solicitadas por los fans desde Melee. Se anunció de forma dramática en el último Direct antes del lanzamiento de Brawl."},
  {t:"m",q:"¿Cómo se llama la serie animada occidental de los sábados por la mañana (SatAM) de Sonic de los años 90 donde los personajes viven en Knothole y luchan contra Robotnik?",o:["Sonic Underground","Adventures of Sonic the Hedgehog","Sonic the Hedgehog (SatAM)","Sonic Boom"],a:2,exp:"'Sonic the Hedgehog' (conocida como SatAM por emitirse los sábados por la mañana) fue la serie animada seria y dramática de Sonic de 1993-1994.",extra:"A diferencia de la otra serie 'Adventures of Sonic the Hedgehog' (más cómica), SatAM tenía un tono oscuro y fue muy bien recibida por los fans adultos."},
  {t:"f",q:"Sonic Underground (1999) es la serie animada donde Sonic tiene dos hermanos reales llamados Sonia y Manic que tocan instrumentos musicales.",o:["Verdadero","Falso"],a:0,exp:"Verdadero. En Sonic Underground, Sonic tiene dos hermanos perdidos: Sonia (que toca el teclado) y Manic (que toca la batería). Juntos forman una banda.",extra:"La serie tiene un estilo muy diferente a la SatAM, con muchos números musicales y una mitología propia sobre la madre de Sonic, la reina Aleena."},
  {t:"m",q:"¿Cómo se llama la forma final de Neo Metal Sonic en Sonic Heroes (2003)?",o:["Perfect Metal Sonic","Metal Madness / Metal Overlord","Robo Sonic","Mechanized Hedgehog"],a:1,exp:"En Sonic Heroes, Neo Metal Sonic se transforma primero en Metal Madness y luego en Metal Overlord, el jefe final del juego tras copiar los datos de todos.",extra:"Para derrotar a Metal Overlord solo puede usarse la versión Super de los tres equipos principales: Super Sonic, Super Shadow y Super Silver... en realidad Super Sonic, Super Tails y Super Knuckles."},
  {t:"m",q:"¿Qué tipo de juego de rol fue Sonic Chronicles: The Dark Brotherhood (2008)?",o:["JRPG de acción en tiempo real","RPG por turnos isométrico","Beat 'em up con elementos RPG","Estrategia por turnos"],a:1,exp:"Sonic Chronicles fue un RPG táctico por turnos desarrollado por BioWare para Nintendo DS, siendo el único RPG formal de Sonic en la saga principal.",extra:"Aunque fue recibido de forma tibia, fue notable por ser desarrollado por BioWare, el estudio conocido por Mass Effect y Dragon Age."},
  {t:"m",q:"¿Cuántas zonas acumulan en total Sonic 3 y Sonic & Knuckles cuando se conectan mediante Lock-On?",o:["10 zonas","14 zonas","18 zonas","12 zonas"],a:1,exp:"Sonic 3 & Knuckles combinado tiene 14 zonas: las 6 de Sonic 3 más las 8 de Sonic & Knuckles, formando la aventura completa que Sega originalmente planeaba.",extra:"La división en dos cartuchos fue consecuencia de las limitaciones de tiempo y presupuesto. La experiencia completa fue la visión original del equipo."},
  {t:"m",q:"¿Qué personaje de Sonic tiene el poder del hielo y actúa como guardia de Blaze the Cat en Sonic Rush Adventure?",o:["Freeze","Marine the Raccoon","Blizzard","Captain Whisker"],a:1,exp:"Marine the Raccoon es el personaje que Sonic y Tails conocen en la Sol Dimension en Sonic Rush Adventure (2007), siendo la guía local energética y parlanchina.",extra:"Marine no tiene poderes de hielo; el malentendido viene de su color. Captain Whisker es el antagonista pirata de Sonic Rush Adventure."},
  {t:"f",q:"Mighty the Armadillo y Ray the Flying Squirrel aparecieron originalmente en Knuckles' Chaotix (1995) antes de ser rescatados en Sonic Mania Plus.",o:["Verdadero","Falso"],a:0,exp:"Verdadero. Mighty y Ray son personajes de los 90: Mighty apareció en SegaSonic the Hedgehog Arcade y Chaotix; Ray en SegaSonic Arcade. Regresaron en Mania Plus.",extra:"Su regreso en Sonic Mania Plus fue muy celebrado por los fans, ya que ambos llevaban décadas sin aparecer en ningún juego oficial de Sonic."},
  {t:"m",q:"¿Cómo se llama el nivel de música nocturna en la Stardust Speedway de Sonic CD donde Sonic corre contra Metal Sonic?",o:["Robotnik's Base","Quartz Quadrant","Stardust Speedway Bad Future","La carrera de Metal Sonic"],a:3,exp:"La carrera de Metal Sonic en Stardust Speedway (Bad Future) es uno de los momentos más icónicos de Sonic CD: hay que ganar a Metal Sonic o Eggman mata a Amy.",extra:"Stardust Speedway tiene cuatro versiones temporales en Sonic CD: pasado, presente, buen futuro y mal futuro, cada una con diferente música y diseño."},
  {t:"m",q:"¿Qué objeto especial esconde cada zona de nivel en Sonic CD que permite liberar el buen futuro si se usa correctamente?",o:["Chaos Emeralds","Robot Generators y Hologramas de Metal Sonic","Time Stones","Power Rings"],a:1,exp:"En Sonic CD, destruir los Robot Generators y los Holograms de Metal Sonic en el pasado de cada zona es lo que crea el Buen Futuro al recolectarlos todos.",extra:"Alternativamente, conseguir las 7 Time Stones en las Special Stages también asegura el Buen Futuro para todas las zonas. Son los dos métodos válidos."},
  {t:"f",q:"Burning Blaze, la forma superpoderosa de Blaze the Cat, se activa recolectando las 7 Sol Emeralds de su dimensión.",o:["Verdadero","Falso"],a:0,exp:"Verdadero. Burning Blaze es la contraparte de Super Sonic en la Sol Dimension: Blaze necesita las 7 Sol Emeralds para transformarse.",extra:"En Sonic Rush, tanto Super Sonic como Burning Blaze son necesarios para el combate final cooperativo contra el jefe definitivo del juego."},
];
export default sonicQuestions;
